#include "embedded_assets/embedded_image.h"
#include "embedded_assets/pen/pen.hpp"
#include "embedded_assets/pen/pen_images.h"
#include "embedded_assets/pen/pen_sprite.h"

/// @NOTE: Generated embedded assets pen

namespace bongocat::assets {
    static const embedded_image_t pen_images_table[] = {
        {pen_aero_v_dramon_png, pen_aero_v_dramon_png_size, "aero_v_dramon"}, 
        {pen_andromon_png, pen_andromon_png_size, "andromon"}, 
        {pen_angewomon_png, pen_angewomon_png_size, "angewomon"}, 
        {pen_anomalocarimon_png, pen_anomalocarimon_png_size, "anomalocarimon"}, 
        {pen_asuramon_png, pen_asuramon_png_size, "asuramon"}, 
        {pen_atlur_kabuterimon_png, pen_atlur_kabuterimon_png_size, "atlur_kabuterimon"}, 
        {pen_bakemon_png, pen_bakemon_png_size, "bakemon"}, 
        {pen_bakumon_png, pen_bakumon_png_size, "bakumon"}, 
        {pen_big_mamemon_png, pen_big_mamemon_png_size, "big_mamemon"}, 
        {pen_birdramon_png, pen_birdramon_png_size, "birdramon"}, 
        {pen_blossomon_png, pen_blossomon_png_size, "blossomon"}, 
        {pen_boltmon_png, pen_boltmon_png_size, "boltmon"}, 
        {pen_bubbmon_png, pen_bubbmon_png_size, "bubbmon"}, 
        {pen_candmon_png, pen_candmon_png_size, "candmon"}, 
        {pen_caprimon_png, pen_caprimon_png_size, "caprimon"}, 
        {pen_choromon_png, pen_choromon_png_size, "choromon"}, 
        {pen_clockmon_png, pen_clockmon_png_size, "clockmon"}, 
        {pen_coelamon_png, pen_coelamon_png_size, "coelamon"}, 
        {pen_cyberdramon_png, pen_cyberdramon_png_size, "cyberdramon"}, 
        {pen_dagomon_png, pen_dagomon_png_size, "dagomon"}, 
        {pen_death_meramon_png, pen_death_meramon_png_size, "death_meramon"}, 
        {pen_delumon_png, pen_delumon_png_size, "delumon"}, 
        {pen_devimon_png, pen_devimon_png_size, "devimon"}, 
        {pen_dokugumon_png, pen_dokugumon_png_size, "dokugumon"}, 
        {pen_ebidramon_png, pen_ebidramon_png_size, "ebidramon"}, 
        {pen_fantomon_png, pen_fantomon_png_size, "fantomon"}, 
        {pen_floramon_png, pen_floramon_png_size, "floramon"}, 
        {pen_ganimon_png, pen_ganimon_png_size, "ganimon"}, 
        {pen_garudamon_png, pen_garudamon_png_size, "garudamon"}, 
        {pen_garurumon_png, pen_garurumon_png_size, "garurumon"}, 
        {pen_gekomon_png, pen_gekomon_png_size, "gekomon"}, 
        {pen_gerbemon_png, pen_gerbemon_png_size, "gerbemon"}, 
        {pen_gesomon_png, pen_gesomon_png_size, "gesomon"}, 
        {pen_gomamon_png, pen_gomamon_png_size, "gomamon"}, 
        {pen_gottsumon_png, pen_gottsumon_png_size, "gottsumon"}, 
        {pen_greymon_png, pen_greymon_png_size, "greymon"}, 
        {pen_griffomon_png, pen_griffomon_png_size, "griffomon"}, 
        {pen_guardromon_png, pen_guardromon_png_size, "guardromon"}, 
        {pen_hagurumon_png, pen_hagurumon_png_size, "hagurumon"}, 
        {pen_hangymon_png, pen_hangymon_png_size, "hangymon"}, 
        {pen_hangyomon_png, pen_hangyomon_png_size, "hangyomon"}, 
        {pen_hanumon_png, pen_hanumon_png_size, "hanumon"}, 
        {pen_herakle_kabuterimon_png, pen_herakle_kabuterimon_png_size, "herakle_kabuterimon"}, 
        {pen_herkule_kabuterimon_png, pen_herkule_kabuterimon_png_size, "herkule_kabuterimon"}, 
        {pen_holy_angemon_png, pen_holy_angemon_png_size, "holy_angemon"}, 
        {pen_holydramon_png, pen_holydramon_png_size, "holydramon"}, 
        {pen_hououmon_png, pen_hououmon_png_size, "hououmon"}, 
        {pen_ignamon_png, pen_ignamon_png_size, "ignamon"}, 
        {pen_ikkakumon_png, pen_ikkakumon_png_size, "ikkakumon"}, 
        {pen_jyagamon_png, pen_jyagamon_png_size, "jyagamon"}, 
        {pen_jyureimon_png, pen_jyureimon_png_size, "jyureimon"}, 
        {pen_kabuterimon_png, pen_kabuterimon_png_size, "kabuterimon"}, 
        {pen_kiwimon_png, pen_kiwimon_png_size, "kiwimon"}, 
        {pen_knightmon_png, pen_knightmon_png_size, "knightmon"}, 
        {pen_kokuwamon_png, pen_kokuwamon_png_size, "kokuwamon"}, 
        {pen_kuwagamon_png, pen_kuwagamon_png_size, "kuwagamon"}, 
        {pen_lady_devimon_png, pen_lady_devimon_png_size, "lady_devimon"}, 
        {pen_lilimon_png, pen_lilimon_png_size, "lilimon"}, 
        {pen_mammon_png, pen_mammon_png_size, "mammon"}, 
        {pen_marin_angemon_png, pen_marin_angemon_png_size, "marin_angemon"}, 
        {pen_marin_devimon_png, pen_marin_devimon_png_size, "marin_devimon"}, 
        {pen_mechanorimon_png, pen_mechanorimon_png_size, "mechanorimon"}, 
        {pen_megadramon_png, pen_megadramon_png_size, "megadramon"}, 
        {pen_mega_seadramon_png, pen_mega_seadramon_png_size, "mega_seadramon"}, 
        {pen_meramon_png, pen_meramon_png_size, "meramon"}, 
        {pen_metal_etemon_png, pen_metal_etemon_png_size, "metal_etemon"}, 
        {pen_metal_garurumon_png, pen_metal_garurumon_png_size, "metal_garurumon"}, 
        {pen_metal_greymon_png, pen_metal_greymon_png_size, "metal_greymon"}, 
        {pen_metal_mamemon_png, pen_metal_mamemon_png_size, "metal_mamemon"}, 
        {pen_metal_seadramon_png, pen_metal_seadramon_png_size, "metal_seadramon"}, 
        {pen_mochimon_png, pen_mochimon_png_size, "mochimon"}, 
        {pen_mokumon_png, pen_mokumon_png_size, "mokumon"}, 
        {pen_monochromon_png, pen_monochromon_png_size, "monochromon"}, 
        {pen_mugendramon_png, pen_mugendramon_png_size, "mugendramon"}, 
        {pen_mushmon_png, pen_mushmon_png_size, "mushmon"}, 
        {pen_nyokimon_png, pen_nyokimon_png_size, "nyokimon"}, 
        {pen_octmon_png, pen_octmon_png_size, "octmon"}, 
        {pen_okuwamon_png, pen_okuwamon_png_size, "okuwamon"}, 
        {pen_omegamon_png, pen_omegamon_png_size, "omegamon"}, 
        {pen_otamamon_png, pen_otamamon_png_size, "otamamon"}, 
        {pen_palmon_png, pen_palmon_png_size, "palmon"}, 
        {pen_peti_meramon_png, pen_peti_meramon_png_size, "peti_meramon"}, 
        {pen_piccolomon_png, pen_piccolomon_png_size, "piccolomon"}, 
        {pen_pico_devimon_png, pen_pico_devimon_png_size, "pico_devimon"}, 
        {pen_piemon_png, pen_piemon_png_size, "piemon"}, 
        {pen_pinochimon_png, pen_pinochimon_png_size, "pinochimon"}, 
        {pen_piyomon_png, pen_piyomon_png_size, "piyomon"}, 
        {pen_plesiomon_png, pen_plesiomon_png_size, "plesiomon"}, 
        {pen_pukumon_png, pen_pukumon_png_size, "pukumon"}, 
        {pen_pumpmon_png, pen_pumpmon_png_size, "pumpmon"}, 
        {pen_pyocomon_png, pen_pyocomon_png_size, "pyocomon"}, 
        {pen_rakamon_png, pen_rakamon_png_size, "rakamon"}, 
        {pen_red_vegimon_png, pen_red_vegimon_png_size, "red_vegimon"}, 
        {pen_revolmon_png, pen_revolmon_png_size, "revolmon"}, 
        {pen_rosemon_png, pen_rosemon_png_size, "rosemon"}, 
        {pen_rukamon_png, pen_rukamon_png_size, "rukamon"}, 
        {pen_saber_leomon_png, pen_saber_leomon_png_size, "saber_leomon"}, 
        {pen_seadramon_png, pen_seadramon_png_size, "seadramon"}, 
        {pen_shakomon_png, pen_shakomon_png_size, "shakomon"}, 
        {pen_skull_mammon_png, pen_skull_mammon_png_size, "skull_mammon"}, 
        {pen_starmon_png, pen_starmon_png_size, "starmon"}, 
        {pen_tailmon_png, pen_tailmon_png_size, "tailmon"}, 
        {pen_tankmon_png, pen_tankmon_png_size, "tankmon"}, 
        {pen_tentomon_png, pen_tentomon_png_size, "tentomon"}, 
        {pen_thunderballmon_png, pen_thunderballmon_png_size, "thunderballmon"}, 
        {pen_togemon_png, pen_togemon_png_size, "togemon"}, 
        {pen_tonosama_gekomon_png, pen_tonosama_gekomon_png_size, "tonosama_gekomon"}, 
        {pen_tortamon_png, pen_tortamon_png_size, "tortamon"}, 
        {pen_toy_agumon_png, pen_toy_agumon_png_size, "toy_agumon"}, 
        {pen_triceramon_png, pen_triceramon_png_size, "triceramon"}, 
        {pen_vamdemon_png, pen_vamdemon_png_size, "vamdemon"}, 
        {pen_v_dramon_png, pen_v_dramon_png_size, "v_dramon"}, 
        {pen_vemdemon_png, pen_vemdemon_png_size, "vemdemon"}, 
        {pen_venom_vamdemon_png, pen_venom_vamdemon_png_size, "venom_vamdemon"}, 
        {pen_war_greymon_png, pen_war_greymon_png_size, "war_greymon"}, 
        {pen_waru_monzaemon_png, pen_waru_monzaemon_png_size, "waru_monzaemon"}, 
        {pen_waru_mozaemon_png, pen_waru_mozaemon_png_size, "waru_mozaemon"}, 
        {pen_were_garurumon_png, pen_were_garurumon_png_size, "were_garurumon"}, 
        {pen_whamon_png, pen_whamon_png_size, "whamon"}, 
        {pen_wizarmon_png, pen_wizarmon_png_size, "wizarmon"}, 
        {pen_woodmon_png, pen_woodmon_png_size, "woodmon"}, 
        {pen_zudomon_png, pen_zudomon_png_size, "zudomon"}, 
        
    };
    embedded_image_t get_pen_sprite_sheet(size_t index) {
        assert(LEN_ARRAY(pen_images_table) == PEN_ANIM_COUNT);
        assert(index < PEN_ANIM_COUNT);
        return pen_images_table[index];
    }
}

