#include "core/bongocat.h"
#include "utils/memory.h"
#include "graphics/animation_thread_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/dm/dm.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dm/dm_sprite.h"
#include "image_loader/dm/load_images_dm.h"
#include "embedded_assets/dm/dm_images.h"
#include <climits>
#include <cstddef>
#include <cstdint>

/// @NOTE: Generated embedded assets dm


namespace bongocat::animation {
    static constexpr assets::embedded_sprite_sheet_dims_t dm_dims_table[] ASSETS_TABLE2_SECTION = {
        {assets::DM_AGUMON_SPRITE_SHEET_COLS, assets::DM_AGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_AIRDRAMON_SPRITE_SHEET_COLS, assets::DM_AIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_ANDROMON_SPRITE_SHEET_COLS, assets::DM_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_ANGEMON_SPRITE_SHEET_COLS, assets::DM_ANGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_BAKEMON_SPRITE_SHEET_COLS, assets::DM_BAKEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_BETAMON_SPRITE_SHEET_COLS, assets::DM_BETAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_BIRDRAMON_SPRITE_SHEET_COLS, assets::DM_BIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_BOTAMON_SPRITE_SHEET_COLS, assets::DM_BOTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_CENTALMON_SPRITE_SHEET_COLS, assets::DM_CENTALMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_COCKATRIMON_SPRITE_SHEET_COLS, assets::DM_COCKATRIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_COELAMON_SPRITE_SHEET_COLS, assets::DM_COELAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_CORONAMON_SPRITE_SHEET_COLS, assets::DM_CORONAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_CYCLOMON_SPRITE_SHEET_COLS, assets::DM_CYCLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DARK_TYRANOMON_SPRITE_SHEET_COLS, assets::DM_DARK_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DELTAMON_SPRITE_SHEET_COLS, assets::DM_DELTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DEVIDRAMON_SPRITE_SHEET_COLS, assets::DM_DEVIDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DEVIMON_SPRITE_SHEET_COLS, assets::DM_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DIGITAMAMON_SPRITE_SHEET_COLS, assets::DM_DIGITAMAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_DRIMOGEMON_SPRITE_SHEET_COLS, assets::DM_DRIMOGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_ELECMON_SPRITE_SHEET_COLS, assets::DM_ELECMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_ETEMON_SPRITE_SHEET_COLS, assets::DM_ETEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_EX_TYRANOMON_SPRITE_SHEET_COLS, assets::DM_EX_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_FLYMON_SPRITE_SHEET_COLS, assets::DM_FLYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GABUMON_SPRITE_SHEET_COLS, assets::DM_GABUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GARURUMON_SPRITE_SHEET_COLS, assets::DM_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GAZIMON_SPRITE_SHEET_COLS, assets::DM_GAZIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GIROMON_SPRITE_SHEET_COLS, assets::DM_GIROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GIZAMON_SPRITE_SHEET_COLS, assets::DM_GIZAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_GREYMON_SPRITE_SHEET_COLS, assets::DM_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_KABUTERIMON_SPRITE_SHEET_COLS, assets::DM_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_KOROMON_SPRITE_SHEET_COLS, assets::DM_KOROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_KUNEMON_SPRITE_SHEET_COLS, assets::DM_KUNEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_KUWAGAMON_SPRITE_SHEET_COLS, assets::DM_KUWAGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_LEOMON_SPRITE_SHEET_COLS, assets::DM_LEOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MAMEMON_SPRITE_SHEET_COLS, assets::DM_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MEGADRAMON_SPRITE_SHEET_COLS, assets::DM_MEGADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MERAMON_SPRITE_SHEET_COLS, assets::DM_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_METAL_GREYMON_SPRITE_SHEET_COLS, assets::DM_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_METAL_MAMEMON_SPRITE_SHEET_COLS, assets::DM_METAL_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_METAL_TYRANOMON_SPRITE_SHEET_COLS, assets::DM_METAL_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MOJYAMON_SPRITE_SHEET_COLS, assets::DM_MOJYAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MONOCHROMON_SPRITE_SHEET_COLS, assets::DM_MONOCHROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MONZAEMON_SPRITE_SHEET_COLS, assets::DM_MONZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_MUGENDRAMON_SPRITE_SHEET_COLS, assets::DM_MUGENDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_NANIMON_SPRITE_SHEET_COLS, assets::DM_NANIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_NANOMON_SPRITE_SHEET_COLS, assets::DM_NANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_NUMEMON_SPRITE_SHEET_COLS, assets::DM_NUMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_OGREMON_SPRITE_SHEET_COLS, assets::DM_OGREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PAGUMON_SPRITE_SHEET_COLS, assets::DM_PAGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PALMON_SPRITE_SHEET_COLS, assets::DM_PALMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PATAMON_SPRITE_SHEET_COLS, assets::DM_PATAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PICCOLOMON_SPRITE_SHEET_COLS, assets::DM_PICCOLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PIYOMON_SPRITE_SHEET_COLS, assets::DM_PIYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_POYOMON_SPRITE_SHEET_COLS, assets::DM_POYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_PUNIMON_SPRITE_SHEET_COLS, assets::DM_PUNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_RAREMON_SPRITE_SHEET_COLS, assets::DM_RAREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_SCUMON_SPRITE_SHEET_COLS, assets::DM_SCUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_SEADRAMON_SPRITE_SHEET_COLS, assets::DM_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_SHELLMON_SPRITE_SHEET_COLS, assets::DM_SHELLMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_SKULL_GREYMON_SPRITE_SHEET_COLS, assets::DM_SKULL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_TANEMON_SPRITE_SHEET_COLS, assets::DM_TANEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_TOKOMON_SPRITE_SHEET_COLS, assets::DM_TOKOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_TUNOMON_SPRITE_SHEET_COLS, assets::DM_TUNOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_TUSKMON_SPRITE_SHEET_COLS, assets::DM_TUSKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_TYRANOMON_SPRITE_SHEET_COLS, assets::DM_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_UNIMON_SPRITE_SHEET_COLS, assets::DM_UNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_VADEMON_SPRITE_SHEET_COLS, assets::DM_VADEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_VEGIMON_SPRITE_SHEET_COLS, assets::DM_VEGIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_WHAMON_SPRITE_SHEET_COLS, assets::DM_WHAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_YUKIDARUMON_SPRITE_SHEET_COLS, assets::DM_YUKIDARUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM_YURAMON_SPRITE_SHEET_COLS, assets::DM_YURAMON_SPRITE_SHEET_ROWS}, 
        
    };
    static const unsigned char* dm_pngs_table[] ASSETS_TABLE_SECTION = {
        dm_agumon_png, 
        dm_airdramon_png, 
        dm_andromon_png, 
        dm_angemon_png, 
        dm_bakemon_png, 
        dm_betamon_png, 
        dm_birdramon_png, 
        dm_botamon_png, 
        dm_centalmon_png, 
        dm_cockatrimon_png, 
        dm_coelamon_png, 
        dm_coronamon_png, 
        dm_cyclomon_png, 
        dm_dark_tyranomon_png, 
        dm_deltamon_png, 
        dm_devidramon_png, 
        dm_devimon_png, 
        dm_digitamamon_png, 
        dm_drimogemon_png, 
        dm_elecmon_png, 
        dm_etemon_png, 
        dm_ex_tyranomon_png, 
        dm_flymon_png, 
        dm_gabumon_png, 
        dm_garurumon_png, 
        dm_gazimon_png, 
        dm_giromon_png, 
        dm_gizamon_png, 
        dm_greymon_png, 
        dm_kabuterimon_png, 
        dm_koromon_png, 
        dm_kunemon_png, 
        dm_kuwagamon_png, 
        dm_leomon_png, 
        dm_mamemon_png, 
        dm_megadramon_png, 
        dm_meramon_png, 
        dm_metal_greymon_png, 
        dm_metal_mamemon_png, 
        dm_metal_tyranomon_png, 
        dm_mojyamon_png, 
        dm_monochromon_png, 
        dm_monzaemon_png, 
        dm_mugendramon_png, 
        dm_nanimon_png, 
        dm_nanomon_png, 
        dm_numemon_png, 
        dm_ogremon_png, 
        dm_pagumon_png, 
        dm_palmon_png, 
        dm_patamon_png, 
        dm_piccolomon_png, 
        dm_piyomon_png, 
        dm_poyomon_png, 
        dm_punimon_png, 
        dm_raremon_png, 
        dm_scumon_png, 
        dm_seadramon_png, 
        dm_shellmon_png, 
        dm_skull_greymon_png, 
        dm_tanemon_png, 
        dm_tokomon_png, 
        dm_tunomon_png, 
        dm_tuskmon_png, 
        dm_tyranomon_png, 
        dm_unimon_png, 
        dm_vademon_png, 
        dm_vegimon_png, 
        dm_whamon_png, 
        dm_yukidarumon_png, 
        dm_yuramon_png, 
        
    };
    static const size_t dm_png_sizes_table[] ASSETS_TABLE_SECTION = {
        dm_agumon_png_size, 
        dm_airdramon_png_size, 
        dm_andromon_png_size, 
        dm_angemon_png_size, 
        dm_bakemon_png_size, 
        dm_betamon_png_size, 
        dm_birdramon_png_size, 
        dm_botamon_png_size, 
        dm_centalmon_png_size, 
        dm_cockatrimon_png_size, 
        dm_coelamon_png_size, 
        dm_coronamon_png_size, 
        dm_cyclomon_png_size, 
        dm_dark_tyranomon_png_size, 
        dm_deltamon_png_size, 
        dm_devidramon_png_size, 
        dm_devimon_png_size, 
        dm_digitamamon_png_size, 
        dm_drimogemon_png_size, 
        dm_elecmon_png_size, 
        dm_etemon_png_size, 
        dm_ex_tyranomon_png_size, 
        dm_flymon_png_size, 
        dm_gabumon_png_size, 
        dm_garurumon_png_size, 
        dm_gazimon_png_size, 
        dm_giromon_png_size, 
        dm_gizamon_png_size, 
        dm_greymon_png_size, 
        dm_kabuterimon_png_size, 
        dm_koromon_png_size, 
        dm_kunemon_png_size, 
        dm_kuwagamon_png_size, 
        dm_leomon_png_size, 
        dm_mamemon_png_size, 
        dm_megadramon_png_size, 
        dm_meramon_png_size, 
        dm_metal_greymon_png_size, 
        dm_metal_mamemon_png_size, 
        dm_metal_tyranomon_png_size, 
        dm_mojyamon_png_size, 
        dm_monochromon_png_size, 
        dm_monzaemon_png_size, 
        dm_mugendramon_png_size, 
        dm_nanimon_png_size, 
        dm_nanomon_png_size, 
        dm_numemon_png_size, 
        dm_ogremon_png_size, 
        dm_pagumon_png_size, 
        dm_palmon_png_size, 
        dm_patamon_png_size, 
        dm_piccolomon_png_size, 
        dm_piyomon_png_size, 
        dm_poyomon_png_size, 
        dm_punimon_png_size, 
        dm_raremon_png_size, 
        dm_scumon_png_size, 
        dm_seadramon_png_size, 
        dm_shellmon_png_size, 
        dm_skull_greymon_png_size, 
        dm_tanemon_png_size, 
        dm_tokomon_png_size, 
        dm_tunomon_png_size, 
        dm_tuskmon_png_size, 
        dm_tyranomon_png_size, 
        dm_unimon_png_size, 
        dm_vademon_png_size, 
        dm_vegimon_png_size, 
        dm_whamon_png_size, 
        dm_yukidarumon_png_size, 
        dm_yuramon_png_size, 
        
    };
    static const char* dm_names_table[] ASSETS_TABLE_SECTION = {
        "agumon", 
        "airdramon", 
        "andromon", 
        "angemon", 
        "bakemon", 
        "betamon", 
        "birdramon", 
        "botamon", 
        "centalmon", 
        "cockatrimon", 
        "coelamon", 
        "coronamon", 
        "cyclomon", 
        "dark_tyranomon", 
        "deltamon", 
        "devidramon", 
        "devimon", 
        "digitamamon", 
        "drimogemon", 
        "elecmon", 
        "etemon", 
        "ex_tyranomon", 
        "flymon", 
        "gabumon", 
        "garurumon", 
        "gazimon", 
        "giromon", 
        "gizamon", 
        "greymon", 
        "kabuterimon", 
        "koromon", 
        "kunemon", 
        "kuwagamon", 
        "leomon", 
        "mamemon", 
        "megadramon", 
        "meramon", 
        "metal_greymon", 
        "metal_mamemon", 
        "metal_tyranomon", 
        "mojyamon", 
        "monochromon", 
        "monzaemon", 
        "mugendramon", 
        "nanimon", 
        "nanomon", 
        "numemon", 
        "ogremon", 
        "pagumon", 
        "palmon", 
        "patamon", 
        "piccolomon", 
        "piyomon", 
        "poyomon", 
        "punimon", 
        "raremon", 
        "scumon", 
        "seadramon", 
        "shellmon", 
        "skull_greymon", 
        "tanemon", 
        "tokomon", 
        "tunomon", 
        "tuskmon", 
        "tyranomon", 
        "unimon", 
        "vademon", 
        "vegimon", 
        "whamon", 
        "yukidarumon", 
        "yuramon", 
        
    };
    created_result_t<dm_sprite_sheet_t> load_dm_sprite_sheet(const animation_thread_context_t& ctx, size_t index) {
        using namespace assets;
        assert(LEN_ARRAY(dm_dims_table) == DM_ANIM_COUNT);
        assert(LEN_ARRAY(dm_pngs_table) == DM_ANIM_COUNT);
        assert(LEN_ARRAY(dm_png_sizes_table) == DM_ANIM_COUNT);
        assert(LEN_ARRAY(dm_names_table) == DM_ANIM_COUNT);
        assert(index < DM_ANIM_COUNT);
        auto result = load_base_dm_anim(ctx, index, {dm_pngs_table[index], dm_png_sizes_table[index], dm_names_table[index]}, dm_dims_table[index].cols, dm_dims_table[index].rows);
        platform::details::asset_unload(dm_pngs_table[index], dm_png_sizes_table[index]);
        return result;
    }
    void init_all_dm_anim(animation_thread_context_t& ctx) {
        using namespace assets;
        for (size_t i = 0;i < DM_ANIM_COUNT;++i) {
            init_dm_anim(ctx, i, {dm_pngs_table[i], dm_png_sizes_table[i], dm_names_table[i]}, dm_dims_table[i].cols, dm_dims_table[i].rows);
        }
        platform::details::asset_unload_all(dm_pngs_table, dm_png_sizes_table, DM_ANIM_COUNT);
    }
}

