#include "core/bongocat.h"
#include "graphics/animation_thread_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/dm/dm.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dm/dm_sprite.h"
#include "image_loader/dm/load_images_dm.h"

namespace bongocat::animation {
    created_result_t<dm_sprite_sheet_t> load_dm_sprite_sheet(const animation_thread_context_t& ctx, int index) {
        using namespace assets;
        switch (index) {
            case DM_AGUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_AGUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_AGUMON_ANIM_INDEX), DM_AGUMON_SPRITE_SHEET_COLS, DM_AGUMON_SPRITE_SHEET_ROWS);
            case DM_AIRDRAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_AIRDRAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_AIRDRAMON_ANIM_INDEX), DM_AIRDRAMON_SPRITE_SHEET_COLS, DM_AIRDRAMON_SPRITE_SHEET_ROWS);
            case DM_ANDROMON_ANIM_INDEX: return load_dm_anim(ctx, DM_ANDROMON_ANIM_INDEX, get_dm_sprite_sheet(DM_ANDROMON_ANIM_INDEX), DM_ANDROMON_SPRITE_SHEET_COLS, DM_ANDROMON_SPRITE_SHEET_ROWS);
            case DM_ANGEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_ANGEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_ANGEMON_ANIM_INDEX), DM_ANGEMON_SPRITE_SHEET_COLS, DM_ANGEMON_SPRITE_SHEET_ROWS);
            case DM_BAKEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_BAKEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_BAKEMON_ANIM_INDEX), DM_BAKEMON_SPRITE_SHEET_COLS, DM_BAKEMON_SPRITE_SHEET_ROWS);
            case DM_BETAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_BETAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_BETAMON_ANIM_INDEX), DM_BETAMON_SPRITE_SHEET_COLS, DM_BETAMON_SPRITE_SHEET_ROWS);
            case DM_BIRDRAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_BIRDRAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_BIRDRAMON_ANIM_INDEX), DM_BIRDRAMON_SPRITE_SHEET_COLS, DM_BIRDRAMON_SPRITE_SHEET_ROWS);
            case DM_BOTAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_BOTAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_BOTAMON_ANIM_INDEX), DM_BOTAMON_SPRITE_SHEET_COLS, DM_BOTAMON_SPRITE_SHEET_ROWS);
            case DM_CENTALMON_ANIM_INDEX: return load_dm_anim(ctx, DM_CENTALMON_ANIM_INDEX, get_dm_sprite_sheet(DM_CENTALMON_ANIM_INDEX), DM_CENTALMON_SPRITE_SHEET_COLS, DM_CENTALMON_SPRITE_SHEET_ROWS);
            case DM_COCKATRIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_COCKATRIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_COCKATRIMON_ANIM_INDEX), DM_COCKATRIMON_SPRITE_SHEET_COLS, DM_COCKATRIMON_SPRITE_SHEET_ROWS);
            case DM_COELAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_COELAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_COELAMON_ANIM_INDEX), DM_COELAMON_SPRITE_SHEET_COLS, DM_COELAMON_SPRITE_SHEET_ROWS);
            case DM_CORONAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_CORONAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_CORONAMON_ANIM_INDEX), DM_CORONAMON_SPRITE_SHEET_COLS, DM_CORONAMON_SPRITE_SHEET_ROWS);
            case DM_CYCLOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_CYCLOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_CYCLOMON_ANIM_INDEX), DM_CYCLOMON_SPRITE_SHEET_COLS, DM_CYCLOMON_SPRITE_SHEET_ROWS);
            case DM_DARK_TYRANOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DARK_TYRANOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DARK_TYRANOMON_ANIM_INDEX), DM_DARK_TYRANOMON_SPRITE_SHEET_COLS, DM_DARK_TYRANOMON_SPRITE_SHEET_ROWS);
            case DM_DELTAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DELTAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DELTAMON_ANIM_INDEX), DM_DELTAMON_SPRITE_SHEET_COLS, DM_DELTAMON_SPRITE_SHEET_ROWS);
            case DM_DEVIDRAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DEVIDRAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DEVIDRAMON_ANIM_INDEX), DM_DEVIDRAMON_SPRITE_SHEET_COLS, DM_DEVIDRAMON_SPRITE_SHEET_ROWS);
            case DM_DEVIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DEVIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DEVIMON_ANIM_INDEX), DM_DEVIMON_SPRITE_SHEET_COLS, DM_DEVIMON_SPRITE_SHEET_ROWS);
            case DM_DIGITAMAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DIGITAMAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DIGITAMAMON_ANIM_INDEX), DM_DIGITAMAMON_SPRITE_SHEET_COLS, DM_DIGITAMAMON_SPRITE_SHEET_ROWS);
            case DM_DRIMOGEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_DRIMOGEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_DRIMOGEMON_ANIM_INDEX), DM_DRIMOGEMON_SPRITE_SHEET_COLS, DM_DRIMOGEMON_SPRITE_SHEET_ROWS);
            case DM_ELECMON_ANIM_INDEX: return load_dm_anim(ctx, DM_ELECMON_ANIM_INDEX, get_dm_sprite_sheet(DM_ELECMON_ANIM_INDEX), DM_ELECMON_SPRITE_SHEET_COLS, DM_ELECMON_SPRITE_SHEET_ROWS);
            case DM_ETEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_ETEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_ETEMON_ANIM_INDEX), DM_ETEMON_SPRITE_SHEET_COLS, DM_ETEMON_SPRITE_SHEET_ROWS);
            case DM_EX_TYRANOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_EX_TYRANOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_EX_TYRANOMON_ANIM_INDEX), DM_EX_TYRANOMON_SPRITE_SHEET_COLS, DM_EX_TYRANOMON_SPRITE_SHEET_ROWS);
            case DM_FLYMON_ANIM_INDEX: return load_dm_anim(ctx, DM_FLYMON_ANIM_INDEX, get_dm_sprite_sheet(DM_FLYMON_ANIM_INDEX), DM_FLYMON_SPRITE_SHEET_COLS, DM_FLYMON_SPRITE_SHEET_ROWS);
            case DM_GABUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GABUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GABUMON_ANIM_INDEX), DM_GABUMON_SPRITE_SHEET_COLS, DM_GABUMON_SPRITE_SHEET_ROWS);
            case DM_GARURUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GARURUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GARURUMON_ANIM_INDEX), DM_GARURUMON_SPRITE_SHEET_COLS, DM_GARURUMON_SPRITE_SHEET_ROWS);
            case DM_GAZIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GAZIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GAZIMON_ANIM_INDEX), DM_GAZIMON_SPRITE_SHEET_COLS, DM_GAZIMON_SPRITE_SHEET_ROWS);
            case DM_GIROMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GIROMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GIROMON_ANIM_INDEX), DM_GIROMON_SPRITE_SHEET_COLS, DM_GIROMON_SPRITE_SHEET_ROWS);
            case DM_GIZAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GIZAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GIZAMON_ANIM_INDEX), DM_GIZAMON_SPRITE_SHEET_COLS, DM_GIZAMON_SPRITE_SHEET_ROWS);
            case DM_GREYMON_ANIM_INDEX: return load_dm_anim(ctx, DM_GREYMON_ANIM_INDEX, get_dm_sprite_sheet(DM_GREYMON_ANIM_INDEX), DM_GREYMON_SPRITE_SHEET_COLS, DM_GREYMON_SPRITE_SHEET_ROWS);
            case DM_KABUTERIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_KABUTERIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_KABUTERIMON_ANIM_INDEX), DM_KABUTERIMON_SPRITE_SHEET_COLS, DM_KABUTERIMON_SPRITE_SHEET_ROWS);
            case DM_KOROMON_ANIM_INDEX: return load_dm_anim(ctx, DM_KOROMON_ANIM_INDEX, get_dm_sprite_sheet(DM_KOROMON_ANIM_INDEX), DM_KOROMON_SPRITE_SHEET_COLS, DM_KOROMON_SPRITE_SHEET_ROWS);
            case DM_KUNEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_KUNEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_KUNEMON_ANIM_INDEX), DM_KUNEMON_SPRITE_SHEET_COLS, DM_KUNEMON_SPRITE_SHEET_ROWS);
            case DM_KUWAGAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_KUWAGAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_KUWAGAMON_ANIM_INDEX), DM_KUWAGAMON_SPRITE_SHEET_COLS, DM_KUWAGAMON_SPRITE_SHEET_ROWS);
            case DM_LEOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_LEOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_LEOMON_ANIM_INDEX), DM_LEOMON_SPRITE_SHEET_COLS, DM_LEOMON_SPRITE_SHEET_ROWS);
            case DM_MAMEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MAMEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MAMEMON_ANIM_INDEX), DM_MAMEMON_SPRITE_SHEET_COLS, DM_MAMEMON_SPRITE_SHEET_ROWS);
            case DM_MEGADRAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MEGADRAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MEGADRAMON_ANIM_INDEX), DM_MEGADRAMON_SPRITE_SHEET_COLS, DM_MEGADRAMON_SPRITE_SHEET_ROWS);
            case DM_MERAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MERAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MERAMON_ANIM_INDEX), DM_MERAMON_SPRITE_SHEET_COLS, DM_MERAMON_SPRITE_SHEET_ROWS);
            case DM_METAL_GREYMON_ANIM_INDEX: return load_dm_anim(ctx, DM_METAL_GREYMON_ANIM_INDEX, get_dm_sprite_sheet(DM_METAL_GREYMON_ANIM_INDEX), DM_METAL_GREYMON_SPRITE_SHEET_COLS, DM_METAL_GREYMON_SPRITE_SHEET_ROWS);
            case DM_METAL_MAMEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_METAL_MAMEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_METAL_MAMEMON_ANIM_INDEX), DM_METAL_MAMEMON_SPRITE_SHEET_COLS, DM_METAL_MAMEMON_SPRITE_SHEET_ROWS);
            case DM_METAL_TYRANOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_METAL_TYRANOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_METAL_TYRANOMON_ANIM_INDEX), DM_METAL_TYRANOMON_SPRITE_SHEET_COLS, DM_METAL_TYRANOMON_SPRITE_SHEET_ROWS);
            case DM_MOJYAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MOJYAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MOJYAMON_ANIM_INDEX), DM_MOJYAMON_SPRITE_SHEET_COLS, DM_MOJYAMON_SPRITE_SHEET_ROWS);
            case DM_MONOCHROMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MONOCHROMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MONOCHROMON_ANIM_INDEX), DM_MONOCHROMON_SPRITE_SHEET_COLS, DM_MONOCHROMON_SPRITE_SHEET_ROWS);
            case DM_MONZAEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_MONZAEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_MONZAEMON_ANIM_INDEX), DM_MONZAEMON_SPRITE_SHEET_COLS, DM_MONZAEMON_SPRITE_SHEET_ROWS);
            case DM_NANIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_NANIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_NANIMON_ANIM_INDEX), DM_NANIMON_SPRITE_SHEET_COLS, DM_NANIMON_SPRITE_SHEET_ROWS);
            case DM_NANOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_NANOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_NANOMON_ANIM_INDEX), DM_NANOMON_SPRITE_SHEET_COLS, DM_NANOMON_SPRITE_SHEET_ROWS);
            case DM_NUMEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_NUMEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_NUMEMON_ANIM_INDEX), DM_NUMEMON_SPRITE_SHEET_COLS, DM_NUMEMON_SPRITE_SHEET_ROWS);
            case DM_OGREMON_ANIM_INDEX: return load_dm_anim(ctx, DM_OGREMON_ANIM_INDEX, get_dm_sprite_sheet(DM_OGREMON_ANIM_INDEX), DM_OGREMON_SPRITE_SHEET_COLS, DM_OGREMON_SPRITE_SHEET_ROWS);
            case DM_PAGUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PAGUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PAGUMON_ANIM_INDEX), DM_PAGUMON_SPRITE_SHEET_COLS, DM_PAGUMON_SPRITE_SHEET_ROWS);
            case DM_PALMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PALMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PALMON_ANIM_INDEX), DM_PALMON_SPRITE_SHEET_COLS, DM_PALMON_SPRITE_SHEET_ROWS);
            case DM_PATAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PATAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PATAMON_ANIM_INDEX), DM_PATAMON_SPRITE_SHEET_COLS, DM_PATAMON_SPRITE_SHEET_ROWS);
            case DM_PICCOLOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PICCOLOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PICCOLOMON_ANIM_INDEX), DM_PICCOLOMON_SPRITE_SHEET_COLS, DM_PICCOLOMON_SPRITE_SHEET_ROWS);
            case DM_PIYOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PIYOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PIYOMON_ANIM_INDEX), DM_PIYOMON_SPRITE_SHEET_COLS, DM_PIYOMON_SPRITE_SHEET_ROWS);
            case DM_POYOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_POYOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_POYOMON_ANIM_INDEX), DM_POYOMON_SPRITE_SHEET_COLS, DM_POYOMON_SPRITE_SHEET_ROWS);
            case DM_PUNIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_PUNIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_PUNIMON_ANIM_INDEX), DM_PUNIMON_SPRITE_SHEET_COLS, DM_PUNIMON_SPRITE_SHEET_ROWS);
            case DM_RAREMON_ANIM_INDEX: return load_dm_anim(ctx, DM_RAREMON_ANIM_INDEX, get_dm_sprite_sheet(DM_RAREMON_ANIM_INDEX), DM_RAREMON_SPRITE_SHEET_COLS, DM_RAREMON_SPRITE_SHEET_ROWS);
            case DM_SCUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_SCUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_SCUMON_ANIM_INDEX), DM_SCUMON_SPRITE_SHEET_COLS, DM_SCUMON_SPRITE_SHEET_ROWS);
            case DM_SEADRAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_SEADRAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_SEADRAMON_ANIM_INDEX), DM_SEADRAMON_SPRITE_SHEET_COLS, DM_SEADRAMON_SPRITE_SHEET_ROWS);
            case DM_SHELLMON_ANIM_INDEX: return load_dm_anim(ctx, DM_SHELLMON_ANIM_INDEX, get_dm_sprite_sheet(DM_SHELLMON_ANIM_INDEX), DM_SHELLMON_SPRITE_SHEET_COLS, DM_SHELLMON_SPRITE_SHEET_ROWS);
            case DM_SKULL_GREYMON_ANIM_INDEX: return load_dm_anim(ctx, DM_SKULL_GREYMON_ANIM_INDEX, get_dm_sprite_sheet(DM_SKULL_GREYMON_ANIM_INDEX), DM_SKULL_GREYMON_SPRITE_SHEET_COLS, DM_SKULL_GREYMON_SPRITE_SHEET_ROWS);
            case DM_TANEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_TANEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_TANEMON_ANIM_INDEX), DM_TANEMON_SPRITE_SHEET_COLS, DM_TANEMON_SPRITE_SHEET_ROWS);
            case DM_TOKOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_TOKOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_TOKOMON_ANIM_INDEX), DM_TOKOMON_SPRITE_SHEET_COLS, DM_TOKOMON_SPRITE_SHEET_ROWS);
            case DM_TUNOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_TUNOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_TUNOMON_ANIM_INDEX), DM_TUNOMON_SPRITE_SHEET_COLS, DM_TUNOMON_SPRITE_SHEET_ROWS);
            case DM_TUSKMON_ANIM_INDEX: return load_dm_anim(ctx, DM_TUSKMON_ANIM_INDEX, get_dm_sprite_sheet(DM_TUSKMON_ANIM_INDEX), DM_TUSKMON_SPRITE_SHEET_COLS, DM_TUSKMON_SPRITE_SHEET_ROWS);
            case DM_TYRANOMON_ANIM_INDEX: return load_dm_anim(ctx, DM_TYRANOMON_ANIM_INDEX, get_dm_sprite_sheet(DM_TYRANOMON_ANIM_INDEX), DM_TYRANOMON_SPRITE_SHEET_COLS, DM_TYRANOMON_SPRITE_SHEET_ROWS);
            case DM_UNIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_UNIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_UNIMON_ANIM_INDEX), DM_UNIMON_SPRITE_SHEET_COLS, DM_UNIMON_SPRITE_SHEET_ROWS);
            case DM_VADEMON_ANIM_INDEX: return load_dm_anim(ctx, DM_VADEMON_ANIM_INDEX, get_dm_sprite_sheet(DM_VADEMON_ANIM_INDEX), DM_VADEMON_SPRITE_SHEET_COLS, DM_VADEMON_SPRITE_SHEET_ROWS);
            case DM_VEGIMON_ANIM_INDEX: return load_dm_anim(ctx, DM_VEGIMON_ANIM_INDEX, get_dm_sprite_sheet(DM_VEGIMON_ANIM_INDEX), DM_VEGIMON_SPRITE_SHEET_COLS, DM_VEGIMON_SPRITE_SHEET_ROWS);
            case DM_WHAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_WHAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_WHAMON_ANIM_INDEX), DM_WHAMON_SPRITE_SHEET_COLS, DM_WHAMON_SPRITE_SHEET_ROWS);
            case DM_YUKIDARUMON_ANIM_INDEX: return load_dm_anim(ctx, DM_YUKIDARUMON_ANIM_INDEX, get_dm_sprite_sheet(DM_YUKIDARUMON_ANIM_INDEX), DM_YUKIDARUMON_SPRITE_SHEET_COLS, DM_YUKIDARUMON_SPRITE_SHEET_ROWS);
            case DM_YURAMON_ANIM_INDEX: return load_dm_anim(ctx, DM_YURAMON_ANIM_INDEX, get_dm_sprite_sheet(DM_YURAMON_ANIM_INDEX), DM_YURAMON_SPRITE_SHEET_COLS, DM_YURAMON_SPRITE_SHEET_ROWS);
            default: return bongocat_error_t::BONGOCAT_ERROR_INVALID_PARAM;
        }
        return bongocat_error_t::BONGOCAT_ERROR_INVALID_PARAM;
    }
}

