#include "core/bongocat.h"
#include "graphics/animation_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/pen/pen.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/pen/pen_sprite.h"
#include "image_loader/pen/load_images_pen.h"

namespace bongocat::animation {
    created_result_t<dm_animation_t> load_pen_sprite_sheet(const animation_context_t& ctx, int index) {
        using namespace assets;
        switch (index) {
            case PEN_AERO_V_DRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_AERO_V_DRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_AERO_V_DRAMON_ANIM_INDEX), PEN_AERO_V_DRAMON_SPRITE_SHEET_COLS, PEN_AERO_V_DRAMON_SPRITE_SHEET_ROWS);
            case PEN_ANGEWOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_ANGEWOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_ANGEWOMON_ANIM_INDEX), PEN_ANGEWOMON_SPRITE_SHEET_COLS, PEN_ANGEWOMON_SPRITE_SHEET_ROWS);
            case PEN_ANOMALOCARIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_ANOMALOCARIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_ANOMALOCARIMON_ANIM_INDEX), PEN_ANOMALOCARIMON_SPRITE_SHEET_COLS, PEN_ANOMALOCARIMON_SPRITE_SHEET_ROWS);
            case PEN_ASURAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_ASURAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_ASURAMON_ANIM_INDEX), PEN_ASURAMON_SPRITE_SHEET_COLS, PEN_ASURAMON_SPRITE_SHEET_ROWS);
            case PEN_ATLUR_KABUTERIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_ATLUR_KABUTERIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_ATLUR_KABUTERIMON_ANIM_INDEX), PEN_ATLUR_KABUTERIMON_SPRITE_SHEET_COLS, PEN_ATLUR_KABUTERIMON_SPRITE_SHEET_ROWS);
            case PEN_BAKUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_BAKUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_BAKUMON_ANIM_INDEX), PEN_BAKUMON_SPRITE_SHEET_COLS, PEN_BAKUMON_SPRITE_SHEET_ROWS);
            case PEN_BIG_MAMEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_BIG_MAMEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_BIG_MAMEMON_ANIM_INDEX), PEN_BIG_MAMEMON_SPRITE_SHEET_COLS, PEN_BIG_MAMEMON_SPRITE_SHEET_ROWS);
            case PEN_BLOSSOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_BLOSSOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_BLOSSOMON_ANIM_INDEX), PEN_BLOSSOMON_SPRITE_SHEET_COLS, PEN_BLOSSOMON_SPRITE_SHEET_ROWS);
            case PEN_BOLTMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_BOLTMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_BOLTMON_ANIM_INDEX), PEN_BOLTMON_SPRITE_SHEET_COLS, PEN_BOLTMON_SPRITE_SHEET_ROWS);
            case PEN_BUBBMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_BUBBMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_BUBBMON_ANIM_INDEX), PEN_BUBBMON_SPRITE_SHEET_COLS, PEN_BUBBMON_SPRITE_SHEET_ROWS);
            case PEN_CANDMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_CANDMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_CANDMON_ANIM_INDEX), PEN_CANDMON_SPRITE_SHEET_COLS, PEN_CANDMON_SPRITE_SHEET_ROWS);
            case PEN_CAPRIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_CAPRIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_CAPRIMON_ANIM_INDEX), PEN_CAPRIMON_SPRITE_SHEET_COLS, PEN_CAPRIMON_SPRITE_SHEET_ROWS);
            case PEN_CHOROMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_CHOROMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_CHOROMON_ANIM_INDEX), PEN_CHOROMON_SPRITE_SHEET_COLS, PEN_CHOROMON_SPRITE_SHEET_ROWS);
            case PEN_CLOCKMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_CLOCKMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_CLOCKMON_ANIM_INDEX), PEN_CLOCKMON_SPRITE_SHEET_COLS, PEN_CLOCKMON_SPRITE_SHEET_ROWS);
            case PEN_CYBERDRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_CYBERDRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_CYBERDRAMON_ANIM_INDEX), PEN_CYBERDRAMON_SPRITE_SHEET_COLS, PEN_CYBERDRAMON_SPRITE_SHEET_ROWS);
            case PEN_DAGOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_DAGOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_DAGOMON_ANIM_INDEX), PEN_DAGOMON_SPRITE_SHEET_COLS, PEN_DAGOMON_SPRITE_SHEET_ROWS);
            case PEN_DEATH_MERAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_DEATH_MERAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_DEATH_MERAMON_ANIM_INDEX), PEN_DEATH_MERAMON_SPRITE_SHEET_COLS, PEN_DEATH_MERAMON_SPRITE_SHEET_ROWS);
            case PEN_DELUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_DELUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_DELUMON_ANIM_INDEX), PEN_DELUMON_SPRITE_SHEET_COLS, PEN_DELUMON_SPRITE_SHEET_ROWS);
            case PEN_DOKUGUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_DOKUGUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_DOKUGUMON_ANIM_INDEX), PEN_DOKUGUMON_SPRITE_SHEET_COLS, PEN_DOKUGUMON_SPRITE_SHEET_ROWS);
            case PEN_EBIDRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_EBIDRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_EBIDRAMON_ANIM_INDEX), PEN_EBIDRAMON_SPRITE_SHEET_COLS, PEN_EBIDRAMON_SPRITE_SHEET_ROWS);
            case PEN_FANTOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_FANTOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_FANTOMON_ANIM_INDEX), PEN_FANTOMON_SPRITE_SHEET_COLS, PEN_FANTOMON_SPRITE_SHEET_ROWS);
            case PEN_FLORAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_FLORAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_FLORAMON_ANIM_INDEX), PEN_FLORAMON_SPRITE_SHEET_COLS, PEN_FLORAMON_SPRITE_SHEET_ROWS);
            case PEN_GANIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GANIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GANIMON_ANIM_INDEX), PEN_GANIMON_SPRITE_SHEET_COLS, PEN_GANIMON_SPRITE_SHEET_ROWS);
            case PEN_GARUDAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GARUDAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GARUDAMON_ANIM_INDEX), PEN_GARUDAMON_SPRITE_SHEET_COLS, PEN_GARUDAMON_SPRITE_SHEET_ROWS);
            case PEN_GEKOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GEKOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GEKOMON_ANIM_INDEX), PEN_GEKOMON_SPRITE_SHEET_COLS, PEN_GEKOMON_SPRITE_SHEET_ROWS);
            case PEN_GERBEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GERBEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GERBEMON_ANIM_INDEX), PEN_GERBEMON_SPRITE_SHEET_COLS, PEN_GERBEMON_SPRITE_SHEET_ROWS);
            case PEN_GESOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GESOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GESOMON_ANIM_INDEX), PEN_GESOMON_SPRITE_SHEET_COLS, PEN_GESOMON_SPRITE_SHEET_ROWS);
            case PEN_GOMAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GOMAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GOMAMON_ANIM_INDEX), PEN_GOMAMON_SPRITE_SHEET_COLS, PEN_GOMAMON_SPRITE_SHEET_ROWS);
            case PEN_GOTTSUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GOTTSUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GOTTSUMON_ANIM_INDEX), PEN_GOTTSUMON_SPRITE_SHEET_COLS, PEN_GOTTSUMON_SPRITE_SHEET_ROWS);
            case PEN_GRIFFOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GRIFFOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GRIFFOMON_ANIM_INDEX), PEN_GRIFFOMON_SPRITE_SHEET_COLS, PEN_GRIFFOMON_SPRITE_SHEET_ROWS);
            case PEN_GUARDROMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_GUARDROMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_GUARDROMON_ANIM_INDEX), PEN_GUARDROMON_SPRITE_SHEET_COLS, PEN_GUARDROMON_SPRITE_SHEET_ROWS);
            case PEN_HAGURUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HAGURUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HAGURUMON_ANIM_INDEX), PEN_HAGURUMON_SPRITE_SHEET_COLS, PEN_HAGURUMON_SPRITE_SHEET_ROWS);
            case PEN_HANGYMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HANGYMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HANGYMON_ANIM_INDEX), PEN_HANGYMON_SPRITE_SHEET_COLS, PEN_HANGYMON_SPRITE_SHEET_ROWS);
            case PEN_HANUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HANUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HANUMON_ANIM_INDEX), PEN_HANUMON_SPRITE_SHEET_COLS, PEN_HANUMON_SPRITE_SHEET_ROWS);
            case PEN_HERKULE_KABUTERIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HERKULE_KABUTERIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HERKULE_KABUTERIMON_ANIM_INDEX), PEN_HERKULE_KABUTERIMON_SPRITE_SHEET_COLS, PEN_HERKULE_KABUTERIMON_SPRITE_SHEET_ROWS);
            case PEN_HOLY_ANGEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HOLY_ANGEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HOLY_ANGEMON_ANIM_INDEX), PEN_HOLY_ANGEMON_SPRITE_SHEET_COLS, PEN_HOLY_ANGEMON_SPRITE_SHEET_ROWS);
            case PEN_HOLYDRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HOLYDRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HOLYDRAMON_ANIM_INDEX), PEN_HOLYDRAMON_SPRITE_SHEET_COLS, PEN_HOLYDRAMON_SPRITE_SHEET_ROWS);
            case PEN_HOUOUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_HOUOUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_HOUOUMON_ANIM_INDEX), PEN_HOUOUMON_SPRITE_SHEET_COLS, PEN_HOUOUMON_SPRITE_SHEET_ROWS);
            case PEN_IGNAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_IGNAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_IGNAMON_ANIM_INDEX), PEN_IGNAMON_SPRITE_SHEET_COLS, PEN_IGNAMON_SPRITE_SHEET_ROWS);
            case PEN_IKKAKUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_IKKAKUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_IKKAKUMON_ANIM_INDEX), PEN_IKKAKUMON_SPRITE_SHEET_COLS, PEN_IKKAKUMON_SPRITE_SHEET_ROWS);
            case PEN_JYAGAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_JYAGAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_JYAGAMON_ANIM_INDEX), PEN_JYAGAMON_SPRITE_SHEET_COLS, PEN_JYAGAMON_SPRITE_SHEET_ROWS);
            case PEN_JYUREIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_JYUREIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_JYUREIMON_ANIM_INDEX), PEN_JYUREIMON_SPRITE_SHEET_COLS, PEN_JYUREIMON_SPRITE_SHEET_ROWS);
            case PEN_KIWIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_KIWIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_KIWIMON_ANIM_INDEX), PEN_KIWIMON_SPRITE_SHEET_COLS, PEN_KIWIMON_SPRITE_SHEET_ROWS);
            case PEN_KNIGHTMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_KNIGHTMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_KNIGHTMON_ANIM_INDEX), PEN_KNIGHTMON_SPRITE_SHEET_COLS, PEN_KNIGHTMON_SPRITE_SHEET_ROWS);
            case PEN_KOKUWAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_KOKUWAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_KOKUWAMON_ANIM_INDEX), PEN_KOKUWAMON_SPRITE_SHEET_COLS, PEN_KOKUWAMON_SPRITE_SHEET_ROWS);
            case PEN_LADY_DEVIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_LADY_DEVIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_LADY_DEVIMON_ANIM_INDEX), PEN_LADY_DEVIMON_SPRITE_SHEET_COLS, PEN_LADY_DEVIMON_SPRITE_SHEET_ROWS);
            case PEN_LILIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_LILIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_LILIMON_ANIM_INDEX), PEN_LILIMON_SPRITE_SHEET_COLS, PEN_LILIMON_SPRITE_SHEET_ROWS);
            case PEN_MAMMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MAMMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MAMMON_ANIM_INDEX), PEN_MAMMON_SPRITE_SHEET_COLS, PEN_MAMMON_SPRITE_SHEET_ROWS);
            case PEN_MARIN_ANGEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MARIN_ANGEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MARIN_ANGEMON_ANIM_INDEX), PEN_MARIN_ANGEMON_SPRITE_SHEET_COLS, PEN_MARIN_ANGEMON_SPRITE_SHEET_ROWS);
            case PEN_MARIN_DEVIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MARIN_DEVIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MARIN_DEVIMON_ANIM_INDEX), PEN_MARIN_DEVIMON_SPRITE_SHEET_COLS, PEN_MARIN_DEVIMON_SPRITE_SHEET_ROWS);
            case PEN_MECHANORIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MECHANORIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MECHANORIMON_ANIM_INDEX), PEN_MECHANORIMON_SPRITE_SHEET_COLS, PEN_MECHANORIMON_SPRITE_SHEET_ROWS);
            case PEN_MEGA_SEADRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MEGA_SEADRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MEGA_SEADRAMON_ANIM_INDEX), PEN_MEGA_SEADRAMON_SPRITE_SHEET_COLS, PEN_MEGA_SEADRAMON_SPRITE_SHEET_ROWS);
            case PEN_METAL_ETEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_METAL_ETEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_METAL_ETEMON_ANIM_INDEX), PEN_METAL_ETEMON_SPRITE_SHEET_COLS, PEN_METAL_ETEMON_SPRITE_SHEET_ROWS);
            case PEN_METAL_SEADRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_METAL_SEADRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_METAL_SEADRAMON_ANIM_INDEX), PEN_METAL_SEADRAMON_SPRITE_SHEET_COLS, PEN_METAL_SEADRAMON_SPRITE_SHEET_ROWS);
            case PEN_MOCHIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MOCHIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MOCHIMON_ANIM_INDEX), PEN_MOCHIMON_SPRITE_SHEET_COLS, PEN_MOCHIMON_SPRITE_SHEET_ROWS);
            case PEN_MOKUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MOKUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MOKUMON_ANIM_INDEX), PEN_MOKUMON_SPRITE_SHEET_COLS, PEN_MOKUMON_SPRITE_SHEET_ROWS);
            case PEN_MUSHMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_MUSHMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_MUSHMON_ANIM_INDEX), PEN_MUSHMON_SPRITE_SHEET_COLS, PEN_MUSHMON_SPRITE_SHEET_ROWS);
            case PEN_NYOKIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_NYOKIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_NYOKIMON_ANIM_INDEX), PEN_NYOKIMON_SPRITE_SHEET_COLS, PEN_NYOKIMON_SPRITE_SHEET_ROWS);
            case PEN_OCTMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_OCTMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_OCTMON_ANIM_INDEX), PEN_OCTMON_SPRITE_SHEET_COLS, PEN_OCTMON_SPRITE_SHEET_ROWS);
            case PEN_OKUWAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_OKUWAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_OKUWAMON_ANIM_INDEX), PEN_OKUWAMON_SPRITE_SHEET_COLS, PEN_OKUWAMON_SPRITE_SHEET_ROWS);
            case PEN_OTAMAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_OTAMAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_OTAMAMON_ANIM_INDEX), PEN_OTAMAMON_SPRITE_SHEET_COLS, PEN_OTAMAMON_SPRITE_SHEET_ROWS);
            case PEN_PETI_MERAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PETI_MERAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PETI_MERAMON_ANIM_INDEX), PEN_PETI_MERAMON_SPRITE_SHEET_COLS, PEN_PETI_MERAMON_SPRITE_SHEET_ROWS);
            case PEN_PICO_DEVIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PICO_DEVIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PICO_DEVIMON_ANIM_INDEX), PEN_PICO_DEVIMON_SPRITE_SHEET_COLS, PEN_PICO_DEVIMON_SPRITE_SHEET_ROWS);
            case PEN_PIEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PIEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PIEMON_ANIM_INDEX), PEN_PIEMON_SPRITE_SHEET_COLS, PEN_PIEMON_SPRITE_SHEET_ROWS);
            case PEN_PLESIOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PLESIOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PLESIOMON_ANIM_INDEX), PEN_PLESIOMON_SPRITE_SHEET_COLS, PEN_PLESIOMON_SPRITE_SHEET_ROWS);
            case PEN_PUKUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PUKUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PUKUMON_ANIM_INDEX), PEN_PUKUMON_SPRITE_SHEET_COLS, PEN_PUKUMON_SPRITE_SHEET_ROWS);
            case PEN_PUMPMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PUMPMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PUMPMON_ANIM_INDEX), PEN_PUMPMON_SPRITE_SHEET_COLS, PEN_PUMPMON_SPRITE_SHEET_ROWS);
            case PEN_PYOCOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_PYOCOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_PYOCOMON_ANIM_INDEX), PEN_PYOCOMON_SPRITE_SHEET_COLS, PEN_PYOCOMON_SPRITE_SHEET_ROWS);
            case PEN_RAKAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_RAKAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_RAKAMON_ANIM_INDEX), PEN_RAKAMON_SPRITE_SHEET_COLS, PEN_RAKAMON_SPRITE_SHEET_ROWS);
            case PEN_RED_VEGIMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_RED_VEGIMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_RED_VEGIMON_ANIM_INDEX), PEN_RED_VEGIMON_SPRITE_SHEET_COLS, PEN_RED_VEGIMON_SPRITE_SHEET_ROWS);
            case PEN_REVOLMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_REVOLMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_REVOLMON_ANIM_INDEX), PEN_REVOLMON_SPRITE_SHEET_COLS, PEN_REVOLMON_SPRITE_SHEET_ROWS);
            case PEN_ROSEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_ROSEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_ROSEMON_ANIM_INDEX), PEN_ROSEMON_SPRITE_SHEET_COLS, PEN_ROSEMON_SPRITE_SHEET_ROWS);
            case PEN_SABER_LEOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_SABER_LEOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_SABER_LEOMON_ANIM_INDEX), PEN_SABER_LEOMON_SPRITE_SHEET_COLS, PEN_SABER_LEOMON_SPRITE_SHEET_ROWS);
            case PEN_SHAKOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_SHAKOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_SHAKOMON_ANIM_INDEX), PEN_SHAKOMON_SPRITE_SHEET_COLS, PEN_SHAKOMON_SPRITE_SHEET_ROWS);
            case PEN_STARMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_STARMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_STARMON_ANIM_INDEX), PEN_STARMON_SPRITE_SHEET_COLS, PEN_STARMON_SPRITE_SHEET_ROWS);
            case PEN_TAILMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TAILMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TAILMON_ANIM_INDEX), PEN_TAILMON_SPRITE_SHEET_COLS, PEN_TAILMON_SPRITE_SHEET_ROWS);
            case PEN_TANKMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TANKMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TANKMON_ANIM_INDEX), PEN_TANKMON_SPRITE_SHEET_COLS, PEN_TANKMON_SPRITE_SHEET_ROWS);
            case PEN_TENTOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TENTOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TENTOMON_ANIM_INDEX), PEN_TENTOMON_SPRITE_SHEET_COLS, PEN_TENTOMON_SPRITE_SHEET_ROWS);
            case PEN_THUNDERBALLMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_THUNDERBALLMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_THUNDERBALLMON_ANIM_INDEX), PEN_THUNDERBALLMON_SPRITE_SHEET_COLS, PEN_THUNDERBALLMON_SPRITE_SHEET_ROWS);
            case PEN_TOGEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TOGEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TOGEMON_ANIM_INDEX), PEN_TOGEMON_SPRITE_SHEET_COLS, PEN_TOGEMON_SPRITE_SHEET_ROWS);
            case PEN_TONOSAMA_GEKOMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TONOSAMA_GEKOMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TONOSAMA_GEKOMON_ANIM_INDEX), PEN_TONOSAMA_GEKOMON_SPRITE_SHEET_COLS, PEN_TONOSAMA_GEKOMON_SPRITE_SHEET_ROWS);
            case PEN_TORTAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TORTAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TORTAMON_ANIM_INDEX), PEN_TORTAMON_SPRITE_SHEET_COLS, PEN_TORTAMON_SPRITE_SHEET_ROWS);
            case PEN_TOY_AGUMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TOY_AGUMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TOY_AGUMON_ANIM_INDEX), PEN_TOY_AGUMON_SPRITE_SHEET_COLS, PEN_TOY_AGUMON_SPRITE_SHEET_ROWS);
            case PEN_TRICERAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_TRICERAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_TRICERAMON_ANIM_INDEX), PEN_TRICERAMON_SPRITE_SHEET_COLS, PEN_TRICERAMON_SPRITE_SHEET_ROWS);
            case PEN_V_DRAMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_V_DRAMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_V_DRAMON_ANIM_INDEX), PEN_V_DRAMON_SPRITE_SHEET_COLS, PEN_V_DRAMON_SPRITE_SHEET_ROWS);
            case PEN_VEMDEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_VEMDEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_VEMDEMON_ANIM_INDEX), PEN_VEMDEMON_SPRITE_SHEET_COLS, PEN_VEMDEMON_SPRITE_SHEET_ROWS);
            case PEN_VENOM_VAMDEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_VENOM_VAMDEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_VENOM_VAMDEMON_ANIM_INDEX), PEN_VENOM_VAMDEMON_SPRITE_SHEET_COLS, PEN_VENOM_VAMDEMON_SPRITE_SHEET_ROWS);
            case PEN_WARU_MOZAEMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_WARU_MOZAEMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_WARU_MOZAEMON_ANIM_INDEX), PEN_WARU_MOZAEMON_SPRITE_SHEET_COLS, PEN_WARU_MOZAEMON_SPRITE_SHEET_ROWS);
            case PEN_WIZARMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_WIZARMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_WIZARMON_ANIM_INDEX), PEN_WIZARMON_SPRITE_SHEET_COLS, PEN_WIZARMON_SPRITE_SHEET_ROWS);
            case PEN_WOODMON_ANIM_INDEX: return load_dm_anim(ctx, PEN_WOODMON_ANIM_INDEX, get_pen_sprite_sheet(PEN_WOODMON_ANIM_INDEX), PEN_WOODMON_SPRITE_SHEET_COLS, PEN_WOODMON_SPRITE_SHEET_ROWS);
            case PEN_ZUDOMOM_ANIM_INDEX: return load_dm_anim(ctx, PEN_ZUDOMOM_ANIM_INDEX, get_pen_sprite_sheet(PEN_ZUDOMOM_ANIM_INDEX), PEN_ZUDOMOM_SPRITE_SHEET_COLS, PEN_ZUDOMOM_SPRITE_SHEET_ROWS);
            default: return bongocat_error_t::BONGOCAT_ERROR_INVALID_PARAM;
        }
        return bongocat_error_t::BONGOCAT_ERROR_INVALID_PARAM;
    }
}

