#include "core/bongocat.h"
#include "utils/memory.h"
#include "graphics/animation_thread_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/pen/pen.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/pen/pen_sprite.h"
#include "image_loader/pen/load_images_pen.h"
#include "embedded_assets/pen/pen_images.h"
#include <climits>
#include <cstddef>
#include <cstdint>

/// @NOTE: Generated embedded assets pen

namespace bongocat::animation {
    static constexpr assets::embedded_sprite_sheet_dims_t pen_dims_table[] = {
        {assets::PEN_AERO_V_DRAMON_SPRITE_SHEET_COLS, assets::PEN_AERO_V_DRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ANDROMON_SPRITE_SHEET_COLS, assets::PEN_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ANGEWOMON_SPRITE_SHEET_COLS, assets::PEN_ANGEWOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ANOMALOCARIMON_SPRITE_SHEET_COLS, assets::PEN_ANOMALOCARIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ASURAMON_SPRITE_SHEET_COLS, assets::PEN_ASURAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ATLUR_KABUTERIMON_SPRITE_SHEET_COLS, assets::PEN_ATLUR_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BAKEMON_SPRITE_SHEET_COLS, assets::PEN_BAKEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BAKUMON_SPRITE_SHEET_COLS, assets::PEN_BAKUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BIG_MAMEMON_SPRITE_SHEET_COLS, assets::PEN_BIG_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BIRDRAMON_SPRITE_SHEET_COLS, assets::PEN_BIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BLOSSOMON_SPRITE_SHEET_COLS, assets::PEN_BLOSSOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BOLTMON_SPRITE_SHEET_COLS, assets::PEN_BOLTMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_BUBBMON_SPRITE_SHEET_COLS, assets::PEN_BUBBMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_CANDMON_SPRITE_SHEET_COLS, assets::PEN_CANDMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_CAPRIMON_SPRITE_SHEET_COLS, assets::PEN_CAPRIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_CHOROMON_SPRITE_SHEET_COLS, assets::PEN_CHOROMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_CLOCKMON_SPRITE_SHEET_COLS, assets::PEN_CLOCKMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_COELAMON_SPRITE_SHEET_COLS, assets::PEN_COELAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_CYBERDRAMON_SPRITE_SHEET_COLS, assets::PEN_CYBERDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_DAGOMON_SPRITE_SHEET_COLS, assets::PEN_DAGOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_DEATH_MERAMON_SPRITE_SHEET_COLS, assets::PEN_DEATH_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_DELUMON_SPRITE_SHEET_COLS, assets::PEN_DELUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_DEVIMON_SPRITE_SHEET_COLS, assets::PEN_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_DOKUGUMON_SPRITE_SHEET_COLS, assets::PEN_DOKUGUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_EBIDRAMON_SPRITE_SHEET_COLS, assets::PEN_EBIDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_FANTOMON_SPRITE_SHEET_COLS, assets::PEN_FANTOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_FLORAMON_SPRITE_SHEET_COLS, assets::PEN_FLORAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GANIMON_SPRITE_SHEET_COLS, assets::PEN_GANIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GARUDAMON_SPRITE_SHEET_COLS, assets::PEN_GARUDAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GARURUMON_SPRITE_SHEET_COLS, assets::PEN_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GEKOMON_SPRITE_SHEET_COLS, assets::PEN_GEKOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GERBEMON_SPRITE_SHEET_COLS, assets::PEN_GERBEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GESOMON_SPRITE_SHEET_COLS, assets::PEN_GESOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GOMAMON_SPRITE_SHEET_COLS, assets::PEN_GOMAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GOTTSUMON_SPRITE_SHEET_COLS, assets::PEN_GOTTSUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GREYMON_SPRITE_SHEET_COLS, assets::PEN_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GRIFFOMON_SPRITE_SHEET_COLS, assets::PEN_GRIFFOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_GUARDROMON_SPRITE_SHEET_COLS, assets::PEN_GUARDROMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HAGURUMON_SPRITE_SHEET_COLS, assets::PEN_HAGURUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HANGYMON_SPRITE_SHEET_COLS, assets::PEN_HANGYMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HANGYOMON_SPRITE_SHEET_COLS, assets::PEN_HANGYOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HANUMON_SPRITE_SHEET_COLS, assets::PEN_HANUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HERAKLE_KABUTERIMON_SPRITE_SHEET_COLS, assets::PEN_HERAKLE_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HERKULE_KABUTERIMON_SPRITE_SHEET_COLS, assets::PEN_HERKULE_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HOLY_ANGEMON_SPRITE_SHEET_COLS, assets::PEN_HOLY_ANGEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HOLYDRAMON_SPRITE_SHEET_COLS, assets::PEN_HOLYDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_HOUOUMON_SPRITE_SHEET_COLS, assets::PEN_HOUOUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_IGNAMON_SPRITE_SHEET_COLS, assets::PEN_IGNAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_IKKAKUMON_SPRITE_SHEET_COLS, assets::PEN_IKKAKUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_JYAGAMON_SPRITE_SHEET_COLS, assets::PEN_JYAGAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_JYUREIMON_SPRITE_SHEET_COLS, assets::PEN_JYUREIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_KABUTERIMON_SPRITE_SHEET_COLS, assets::PEN_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_KIWIMON_SPRITE_SHEET_COLS, assets::PEN_KIWIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_KNIGHTMON_SPRITE_SHEET_COLS, assets::PEN_KNIGHTMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_KOKUWAMON_SPRITE_SHEET_COLS, assets::PEN_KOKUWAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_KUWAGAMON_SPRITE_SHEET_COLS, assets::PEN_KUWAGAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_LADY_DEVIMON_SPRITE_SHEET_COLS, assets::PEN_LADY_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_LILIMON_SPRITE_SHEET_COLS, assets::PEN_LILIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MAMMON_SPRITE_SHEET_COLS, assets::PEN_MAMMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MARIN_ANGEMON_SPRITE_SHEET_COLS, assets::PEN_MARIN_ANGEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MARIN_DEVIMON_SPRITE_SHEET_COLS, assets::PEN_MARIN_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MECHANORIMON_SPRITE_SHEET_COLS, assets::PEN_MECHANORIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MEGADRAMON_SPRITE_SHEET_COLS, assets::PEN_MEGADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MEGA_SEADRAMON_SPRITE_SHEET_COLS, assets::PEN_MEGA_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MERAMON_SPRITE_SHEET_COLS, assets::PEN_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_METAL_ETEMON_SPRITE_SHEET_COLS, assets::PEN_METAL_ETEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_METAL_GARURUMON_SPRITE_SHEET_COLS, assets::PEN_METAL_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_METAL_GREYMON_SPRITE_SHEET_COLS, assets::PEN_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_METAL_MAMEMON_SPRITE_SHEET_COLS, assets::PEN_METAL_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_METAL_SEADRAMON_SPRITE_SHEET_COLS, assets::PEN_METAL_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MOCHIMON_SPRITE_SHEET_COLS, assets::PEN_MOCHIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MOKUMON_SPRITE_SHEET_COLS, assets::PEN_MOKUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MONOCHROMON_SPRITE_SHEET_COLS, assets::PEN_MONOCHROMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MUGENDRAMON_SPRITE_SHEET_COLS, assets::PEN_MUGENDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_MUSHMON_SPRITE_SHEET_COLS, assets::PEN_MUSHMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_NYOKIMON_SPRITE_SHEET_COLS, assets::PEN_NYOKIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_OCTMON_SPRITE_SHEET_COLS, assets::PEN_OCTMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_OKUWAMON_SPRITE_SHEET_COLS, assets::PEN_OKUWAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_OMEGAMON_SPRITE_SHEET_COLS, assets::PEN_OMEGAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_OTAMAMON_SPRITE_SHEET_COLS, assets::PEN_OTAMAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PALMON_SPRITE_SHEET_COLS, assets::PEN_PALMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PETI_MERAMON_SPRITE_SHEET_COLS, assets::PEN_PETI_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PICCOLOMON_SPRITE_SHEET_COLS, assets::PEN_PICCOLOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PICO_DEVIMON_SPRITE_SHEET_COLS, assets::PEN_PICO_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PIEMON_SPRITE_SHEET_COLS, assets::PEN_PIEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PINOCHIMON_SPRITE_SHEET_COLS, assets::PEN_PINOCHIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PIYOMON_SPRITE_SHEET_COLS, assets::PEN_PIYOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PLESIOMON_SPRITE_SHEET_COLS, assets::PEN_PLESIOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PUKUMON_SPRITE_SHEET_COLS, assets::PEN_PUKUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PUMPMON_SPRITE_SHEET_COLS, assets::PEN_PUMPMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_PYOCOMON_SPRITE_SHEET_COLS, assets::PEN_PYOCOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_RAKAMON_SPRITE_SHEET_COLS, assets::PEN_RAKAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_RED_VEGIMON_SPRITE_SHEET_COLS, assets::PEN_RED_VEGIMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_REVOLMON_SPRITE_SHEET_COLS, assets::PEN_REVOLMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ROSEMON_SPRITE_SHEET_COLS, assets::PEN_ROSEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_RUKAMON_SPRITE_SHEET_COLS, assets::PEN_RUKAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_SABER_LEOMON_SPRITE_SHEET_COLS, assets::PEN_SABER_LEOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_SEADRAMON_SPRITE_SHEET_COLS, assets::PEN_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_SHAKOMON_SPRITE_SHEET_COLS, assets::PEN_SHAKOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_SKULL_MAMMON_SPRITE_SHEET_COLS, assets::PEN_SKULL_MAMMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_STARMON_SPRITE_SHEET_COLS, assets::PEN_STARMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TAILMON_SPRITE_SHEET_COLS, assets::PEN_TAILMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TANKMON_SPRITE_SHEET_COLS, assets::PEN_TANKMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TENTOMON_SPRITE_SHEET_COLS, assets::PEN_TENTOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_THUNDERBALLMON_SPRITE_SHEET_COLS, assets::PEN_THUNDERBALLMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TOGEMON_SPRITE_SHEET_COLS, assets::PEN_TOGEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TONOSAMA_GEKOMON_SPRITE_SHEET_COLS, assets::PEN_TONOSAMA_GEKOMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TORTAMON_SPRITE_SHEET_COLS, assets::PEN_TORTAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TOY_AGUMON_SPRITE_SHEET_COLS, assets::PEN_TOY_AGUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_TRICERAMON_SPRITE_SHEET_COLS, assets::PEN_TRICERAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_VAMDEMON_SPRITE_SHEET_COLS, assets::PEN_VAMDEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_V_DRAMON_SPRITE_SHEET_COLS, assets::PEN_V_DRAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_VEMDEMON_SPRITE_SHEET_COLS, assets::PEN_VEMDEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_VENOM_VAMDEMON_SPRITE_SHEET_COLS, assets::PEN_VENOM_VAMDEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WAR_GREYMON_SPRITE_SHEET_COLS, assets::PEN_WAR_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WARU_MONZAEMON_SPRITE_SHEET_COLS, assets::PEN_WARU_MONZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WARU_MOZAEMON_SPRITE_SHEET_COLS, assets::PEN_WARU_MOZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WERE_GARURUMON_SPRITE_SHEET_COLS, assets::PEN_WERE_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WHAMON_SPRITE_SHEET_COLS, assets::PEN_WHAMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WIZARMON_SPRITE_SHEET_COLS, assets::PEN_WIZARMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_WOODMON_SPRITE_SHEET_COLS, assets::PEN_WOODMON_SPRITE_SHEET_ROWS}, 
        {assets::PEN_ZUDOMON_SPRITE_SHEET_COLS, assets::PEN_ZUDOMON_SPRITE_SHEET_ROWS}, 
        
    };
    static const unsigned char* pen_pngs_table[] = {
        pen_aero_v_dramon_png, 
        pen_andromon_png, 
        pen_angewomon_png, 
        pen_anomalocarimon_png, 
        pen_asuramon_png, 
        pen_atlur_kabuterimon_png, 
        pen_bakemon_png, 
        pen_bakumon_png, 
        pen_big_mamemon_png, 
        pen_birdramon_png, 
        pen_blossomon_png, 
        pen_boltmon_png, 
        pen_bubbmon_png, 
        pen_candmon_png, 
        pen_caprimon_png, 
        pen_choromon_png, 
        pen_clockmon_png, 
        pen_coelamon_png, 
        pen_cyberdramon_png, 
        pen_dagomon_png, 
        pen_death_meramon_png, 
        pen_delumon_png, 
        pen_devimon_png, 
        pen_dokugumon_png, 
        pen_ebidramon_png, 
        pen_fantomon_png, 
        pen_floramon_png, 
        pen_ganimon_png, 
        pen_garudamon_png, 
        pen_garurumon_png, 
        pen_gekomon_png, 
        pen_gerbemon_png, 
        pen_gesomon_png, 
        pen_gomamon_png, 
        pen_gottsumon_png, 
        pen_greymon_png, 
        pen_griffomon_png, 
        pen_guardromon_png, 
        pen_hagurumon_png, 
        pen_hangymon_png, 
        pen_hangyomon_png, 
        pen_hanumon_png, 
        pen_herakle_kabuterimon_png, 
        pen_herkule_kabuterimon_png, 
        pen_holy_angemon_png, 
        pen_holydramon_png, 
        pen_hououmon_png, 
        pen_ignamon_png, 
        pen_ikkakumon_png, 
        pen_jyagamon_png, 
        pen_jyureimon_png, 
        pen_kabuterimon_png, 
        pen_kiwimon_png, 
        pen_knightmon_png, 
        pen_kokuwamon_png, 
        pen_kuwagamon_png, 
        pen_lady_devimon_png, 
        pen_lilimon_png, 
        pen_mammon_png, 
        pen_marin_angemon_png, 
        pen_marin_devimon_png, 
        pen_mechanorimon_png, 
        pen_megadramon_png, 
        pen_mega_seadramon_png, 
        pen_meramon_png, 
        pen_metal_etemon_png, 
        pen_metal_garurumon_png, 
        pen_metal_greymon_png, 
        pen_metal_mamemon_png, 
        pen_metal_seadramon_png, 
        pen_mochimon_png, 
        pen_mokumon_png, 
        pen_monochromon_png, 
        pen_mugendramon_png, 
        pen_mushmon_png, 
        pen_nyokimon_png, 
        pen_octmon_png, 
        pen_okuwamon_png, 
        pen_omegamon_png, 
        pen_otamamon_png, 
        pen_palmon_png, 
        pen_peti_meramon_png, 
        pen_piccolomon_png, 
        pen_pico_devimon_png, 
        pen_piemon_png, 
        pen_pinochimon_png, 
        pen_piyomon_png, 
        pen_plesiomon_png, 
        pen_pukumon_png, 
        pen_pumpmon_png, 
        pen_pyocomon_png, 
        pen_rakamon_png, 
        pen_red_vegimon_png, 
        pen_revolmon_png, 
        pen_rosemon_png, 
        pen_rukamon_png, 
        pen_saber_leomon_png, 
        pen_seadramon_png, 
        pen_shakomon_png, 
        pen_skull_mammon_png, 
        pen_starmon_png, 
        pen_tailmon_png, 
        pen_tankmon_png, 
        pen_tentomon_png, 
        pen_thunderballmon_png, 
        pen_togemon_png, 
        pen_tonosama_gekomon_png, 
        pen_tortamon_png, 
        pen_toy_agumon_png, 
        pen_triceramon_png, 
        pen_vamdemon_png, 
        pen_v_dramon_png, 
        pen_vemdemon_png, 
        pen_venom_vamdemon_png, 
        pen_war_greymon_png, 
        pen_waru_monzaemon_png, 
        pen_waru_mozaemon_png, 
        pen_were_garurumon_png, 
        pen_whamon_png, 
        pen_wizarmon_png, 
        pen_woodmon_png, 
        pen_zudomon_png, 
        
    };
    static const size_t pen_png_sizes_table[] = {
        pen_aero_v_dramon_png_size, 
        pen_andromon_png_size, 
        pen_angewomon_png_size, 
        pen_anomalocarimon_png_size, 
        pen_asuramon_png_size, 
        pen_atlur_kabuterimon_png_size, 
        pen_bakemon_png_size, 
        pen_bakumon_png_size, 
        pen_big_mamemon_png_size, 
        pen_birdramon_png_size, 
        pen_blossomon_png_size, 
        pen_boltmon_png_size, 
        pen_bubbmon_png_size, 
        pen_candmon_png_size, 
        pen_caprimon_png_size, 
        pen_choromon_png_size, 
        pen_clockmon_png_size, 
        pen_coelamon_png_size, 
        pen_cyberdramon_png_size, 
        pen_dagomon_png_size, 
        pen_death_meramon_png_size, 
        pen_delumon_png_size, 
        pen_devimon_png_size, 
        pen_dokugumon_png_size, 
        pen_ebidramon_png_size, 
        pen_fantomon_png_size, 
        pen_floramon_png_size, 
        pen_ganimon_png_size, 
        pen_garudamon_png_size, 
        pen_garurumon_png_size, 
        pen_gekomon_png_size, 
        pen_gerbemon_png_size, 
        pen_gesomon_png_size, 
        pen_gomamon_png_size, 
        pen_gottsumon_png_size, 
        pen_greymon_png_size, 
        pen_griffomon_png_size, 
        pen_guardromon_png_size, 
        pen_hagurumon_png_size, 
        pen_hangymon_png_size, 
        pen_hangyomon_png_size, 
        pen_hanumon_png_size, 
        pen_herakle_kabuterimon_png_size, 
        pen_herkule_kabuterimon_png_size, 
        pen_holy_angemon_png_size, 
        pen_holydramon_png_size, 
        pen_hououmon_png_size, 
        pen_ignamon_png_size, 
        pen_ikkakumon_png_size, 
        pen_jyagamon_png_size, 
        pen_jyureimon_png_size, 
        pen_kabuterimon_png_size, 
        pen_kiwimon_png_size, 
        pen_knightmon_png_size, 
        pen_kokuwamon_png_size, 
        pen_kuwagamon_png_size, 
        pen_lady_devimon_png_size, 
        pen_lilimon_png_size, 
        pen_mammon_png_size, 
        pen_marin_angemon_png_size, 
        pen_marin_devimon_png_size, 
        pen_mechanorimon_png_size, 
        pen_megadramon_png_size, 
        pen_mega_seadramon_png_size, 
        pen_meramon_png_size, 
        pen_metal_etemon_png_size, 
        pen_metal_garurumon_png_size, 
        pen_metal_greymon_png_size, 
        pen_metal_mamemon_png_size, 
        pen_metal_seadramon_png_size, 
        pen_mochimon_png_size, 
        pen_mokumon_png_size, 
        pen_monochromon_png_size, 
        pen_mugendramon_png_size, 
        pen_mushmon_png_size, 
        pen_nyokimon_png_size, 
        pen_octmon_png_size, 
        pen_okuwamon_png_size, 
        pen_omegamon_png_size, 
        pen_otamamon_png_size, 
        pen_palmon_png_size, 
        pen_peti_meramon_png_size, 
        pen_piccolomon_png_size, 
        pen_pico_devimon_png_size, 
        pen_piemon_png_size, 
        pen_pinochimon_png_size, 
        pen_piyomon_png_size, 
        pen_plesiomon_png_size, 
        pen_pukumon_png_size, 
        pen_pumpmon_png_size, 
        pen_pyocomon_png_size, 
        pen_rakamon_png_size, 
        pen_red_vegimon_png_size, 
        pen_revolmon_png_size, 
        pen_rosemon_png_size, 
        pen_rukamon_png_size, 
        pen_saber_leomon_png_size, 
        pen_seadramon_png_size, 
        pen_shakomon_png_size, 
        pen_skull_mammon_png_size, 
        pen_starmon_png_size, 
        pen_tailmon_png_size, 
        pen_tankmon_png_size, 
        pen_tentomon_png_size, 
        pen_thunderballmon_png_size, 
        pen_togemon_png_size, 
        pen_tonosama_gekomon_png_size, 
        pen_tortamon_png_size, 
        pen_toy_agumon_png_size, 
        pen_triceramon_png_size, 
        pen_vamdemon_png_size, 
        pen_v_dramon_png_size, 
        pen_vemdemon_png_size, 
        pen_venom_vamdemon_png_size, 
        pen_war_greymon_png_size, 
        pen_waru_monzaemon_png_size, 
        pen_waru_mozaemon_png_size, 
        pen_were_garurumon_png_size, 
        pen_whamon_png_size, 
        pen_wizarmon_png_size, 
        pen_woodmon_png_size, 
        pen_zudomon_png_size, 
        
    };
    static const char* pen_names_table[] = {
        "aero_v_dramon", 
        "andromon", 
        "angewomon", 
        "anomalocarimon", 
        "asuramon", 
        "atlur_kabuterimon", 
        "bakemon", 
        "bakumon", 
        "big_mamemon", 
        "birdramon", 
        "blossomon", 
        "boltmon", 
        "bubbmon", 
        "candmon", 
        "caprimon", 
        "choromon", 
        "clockmon", 
        "coelamon", 
        "cyberdramon", 
        "dagomon", 
        "death_meramon", 
        "delumon", 
        "devimon", 
        "dokugumon", 
        "ebidramon", 
        "fantomon", 
        "floramon", 
        "ganimon", 
        "garudamon", 
        "garurumon", 
        "gekomon", 
        "gerbemon", 
        "gesomon", 
        "gomamon", 
        "gottsumon", 
        "greymon", 
        "griffomon", 
        "guardromon", 
        "hagurumon", 
        "hangymon", 
        "hangyomon", 
        "hanumon", 
        "herakle_kabuterimon", 
        "herkule_kabuterimon", 
        "holy_angemon", 
        "holydramon", 
        "hououmon", 
        "ignamon", 
        "ikkakumon", 
        "jyagamon", 
        "jyureimon", 
        "kabuterimon", 
        "kiwimon", 
        "knightmon", 
        "kokuwamon", 
        "kuwagamon", 
        "lady_devimon", 
        "lilimon", 
        "mammon", 
        "marin_angemon", 
        "marin_devimon", 
        "mechanorimon", 
        "megadramon", 
        "mega_seadramon", 
        "meramon", 
        "metal_etemon", 
        "metal_garurumon", 
        "metal_greymon", 
        "metal_mamemon", 
        "metal_seadramon", 
        "mochimon", 
        "mokumon", 
        "monochromon", 
        "mugendramon", 
        "mushmon", 
        "nyokimon", 
        "octmon", 
        "okuwamon", 
        "omegamon", 
        "otamamon", 
        "palmon", 
        "peti_meramon", 
        "piccolomon", 
        "pico_devimon", 
        "piemon", 
        "pinochimon", 
        "piyomon", 
        "plesiomon", 
        "pukumon", 
        "pumpmon", 
        "pyocomon", 
        "rakamon", 
        "red_vegimon", 
        "revolmon", 
        "rosemon", 
        "rukamon", 
        "saber_leomon", 
        "seadramon", 
        "shakomon", 
        "skull_mammon", 
        "starmon", 
        "tailmon", 
        "tankmon", 
        "tentomon", 
        "thunderballmon", 
        "togemon", 
        "tonosama_gekomon", 
        "tortamon", 
        "toy_agumon", 
        "triceramon", 
        "vamdemon", 
        "v_dramon", 
        "vemdemon", 
        "venom_vamdemon", 
        "war_greymon", 
        "waru_monzaemon", 
        "waru_mozaemon", 
        "were_garurumon", 
        "whamon", 
        "wizarmon", 
        "woodmon", 
        "zudomon", 
        
    };
    created_result_t<dm_sprite_sheet_t> load_pen_sprite_sheet(const animation_thread_context_t& ctx, size_t index) {
        using namespace assets;
        assert(LEN_ARRAY(pen_dims_table) == PEN_ANIM_COUNT);
        assert(LEN_ARRAY(pen_pngs_table) == PEN_ANIM_COUNT);
        assert(LEN_ARRAY(pen_png_sizes_table) == PEN_ANIM_COUNT);
        assert(LEN_ARRAY(pen_names_table) == PEN_ANIM_COUNT);
        assert(index < PEN_ANIM_COUNT);
        auto result = load_base_dm_anim(ctx, index, {pen_pngs_table[index], pen_png_sizes_table[index], pen_names_table[index]}, pen_dims_table[index].cols, pen_dims_table[index].rows);
        platform::details::asset_unload(pen_pngs_table[index], pen_png_sizes_table[index]);
        return result;
    }
    void init_all_pen_anim(animation_thread_context_t& ctx) {
        using namespace assets;
        for (size_t i = 0;i < PEN_ANIM_COUNT;++i) {
            init_pen_anim(ctx, i, {pen_pngs_table[i], pen_png_sizes_table[i], pen_names_table[i]}, pen_dims_table[i].cols, pen_dims_table[i].rows);
        }
        platform::details::asset_unload_all(pen_pngs_table, pen_png_sizes_table, PEN_ANIM_COUNT);
    }
}

