#include "core/bongocat.h"
#include "utils/memory.h"
#include "graphics/animation_thread_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/dmc/dmc.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dmc/dmc_sprite.h"
#include "image_loader/dmc/load_images_dmc.h"
#include "embedded_assets/dmc/dmc_images.h"
#include <climits>
#include <cstddef>
#include <cstdint>

/// @NOTE: Generated embedded assets dmc

namespace bongocat::animation {
    static constexpr assets::embedded_sprite_sheet_dims_t dmc_dims_table[] = {
        {assets::DMC_AGUMON_SPRITE_SHEET_COLS, assets::DMC_AGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_AIRDRAMON_SPRITE_SHEET_COLS, assets::DMC_AIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ANDROMON_SPRITE_SHEET_COLS, assets::DMC_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ANGEMON_SPRITE_SHEET_COLS, assets::DMC_ANGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BABYDMON_SPRITE_SHEET_COLS, assets::DMC_BABYDMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BAKEMON_SPRITE_SHEET_COLS, assets::DMC_BAKEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BANCHO_LEOMON_SPRITE_SHEET_COLS, assets::DMC_BANCHO_LEOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BANCHO_MAMEMON_SPRITE_SHEET_COLS, assets::DMC_BANCHO_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BETAMON_SPRITE_SHEET_COLS, assets::DMC_BETAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BIRDRAMON_SPRITE_SHEET_COLS, assets::DMC_BIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BLITZ_GREYMON_SPRITE_SHEET_COLS, assets::DMC_BLITZ_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BLOOM_LORDMON_SPRITE_SHEET_COLS, assets::DMC_BLOOM_LORDMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_BOTAMON_SPRITE_SHEET_COLS, assets::DMC_BOTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CENTALMON_SPRITE_SHEET_COLS, assets::DMC_CENTALMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CHAOSDRAMON_SPRITE_SHEET_COLS, assets::DMC_CHAOSDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CHAOSMON_SPRITE_SHEET_COLS, assets::DMC_CHAOSMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CHIMAIRAMON_SPRITE_SHEET_COLS, assets::DMC_CHIMAIRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_COCKATRIMON_SPRITE_SHEET_COLS, assets::DMC_COCKATRIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_COELAMON_SPRITE_SHEET_COLS, assets::DMC_COELAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CORONAMON_SPRITE_SHEET_COLS, assets::DMC_CORONAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CRES_GARURUMON_SPRITE_SHEET_COLS, assets::DMC_CRES_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_CYCLOMON_SPRITE_SHEET_COLS, assets::DMC_CYCLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DARKDRAMON_SPRITE_SHEET_COLS, assets::DMC_DARKDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DARK_TYRANOMON_SPRITE_SHEET_COLS, assets::DMC_DARK_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DELTAMON_SPRITE_SHEET_COLS, assets::DMC_DELTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DEVIDRAMON_SPRITE_SHEET_COLS, assets::DMC_DEVIDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DEVIMON_SPRITE_SHEET_COLS, assets::DMC_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DIGITAMAMON_SPRITE_SHEET_COLS, assets::DMC_DIGITAMAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_DRIMOGEMON_SPRITE_SHEET_COLS, assets::DMC_DRIMOGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_EBEMON_SPRITE_SHEET_COLS, assets::DMC_EBEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ELECMON_SPRITE_SHEET_COLS, assets::DMC_ELECMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ETEMON_SPRITE_SHEET_COLS, assets::DMC_ETEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_EX_TYRANOMON_SPRITE_SHEET_COLS, assets::DMC_EX_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_FLYMON_SPRITE_SHEET_COLS, assets::DMC_FLYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GABUMON_SPRITE_SHEET_COLS, assets::DMC_GABUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GAIOUMON_SPRITE_SHEET_COLS, assets::DMC_GAIOUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GANKOOMON_SPRITE_SHEET_COLS, assets::DMC_GANKOOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GARURUMON_SPRITE_SHEET_COLS, assets::DMC_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GAZIMON_SPRITE_SHEET_COLS, assets::DMC_GAZIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GIROMON_SPRITE_SHEET_COLS, assets::DMC_GIROMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GIZAMON_SPRITE_SHEET_COLS, assets::DMC_GIZAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GOKUMON_SPRITE_SHEET_COLS, assets::DMC_GOKUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_GREYMON_SPRITE_SHEET_COLS, assets::DMC_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_HI_ANDROMON_SPRITE_SHEET_COLS, assets::DMC_HI_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_KABUTERIMON_SPRITE_SHEET_COLS, assets::DMC_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_KOROMON_SPRITE_SHEET_COLS, assets::DMC_KOROMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_KUNEMON_SPRITE_SHEET_COLS, assets::DMC_KUNEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_KUWAGAMON_SPRITE_SHEET_COLS, assets::DMC_KUWAGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_LEOMON_SPRITE_SHEET_COLS, assets::DMC_LEOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MAMEMON_SPRITE_SHEET_COLS, assets::DMC_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MEGADRAMON_SPRITE_SHEET_COLS, assets::DMC_MEGADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MERAMON_SPRITE_SHEET_COLS, assets::DMC_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_METAL_GARURUMON_SPRITE_SHEET_COLS, assets::DMC_METAL_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_METAL_GREYMON_SPRITE_SHEET_COLS, assets::DMC_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_METAL_GREYMON_VIRUS_SPRITE_SHEET_COLS, assets::DMC_METAL_GREYMON_VIRUS_SPRITE_SHEET_ROWS}, 
        {assets::DMC_METAL_MAMEMON_SPRITE_SHEET_COLS, assets::DMC_METAL_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_METAL_TYRANOMON_SPRITE_SHEET_COLS, assets::DMC_METAL_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MILLENNIUMON_SPRITE_SHEET_COLS, assets::DMC_MILLENNIUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MOJYAMON_SPRITE_SHEET_COLS, assets::DMC_MOJYAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MOJYMON_SPRITE_SHEET_COLS, assets::DMC_MOJYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MONOCHROMON_SPRITE_SHEET_COLS, assets::DMC_MONOCHROMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MONZAEMON_SPRITE_SHEET_COLS, assets::DMC_MONZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MOZAEMON_SPRITE_SHEET_COLS, assets::DMC_MOZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_MUGENDRAMON_SPRITE_SHEET_COLS, assets::DMC_MUGENDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_NANIMON_SPRITE_SHEET_COLS, assets::DMC_NANIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_NANOMON_SPRITE_SHEET_COLS, assets::DMC_NANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_NUMEMON_SPRITE_SHEET_COLS, assets::DMC_NUMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_OGREMON_SPRITE_SHEET_COLS, assets::DMC_OGREMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_OMEGAMON_ALTER_S_SPRITE_SHEET_COLS, assets::DMC_OMEGAMON_ALTER_S_SPRITE_SHEET_ROWS}, 
        {assets::DMC_OMEGAMON_SPRITE_SHEET_COLS, assets::DMC_OMEGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ORGEMON_SPRITE_SHEET_COLS, assets::DMC_ORGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PAGUMON_SPRITE_SHEET_COLS, assets::DMC_PAGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PALMON_SPRITE_SHEET_COLS, assets::DMC_PALMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PATAMON_SPRITE_SHEET_COLS, assets::DMC_PATAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PETITMON_SPRITE_SHEET_COLS, assets::DMC_PETITMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PICCOLOMON_SPRITE_SHEET_COLS, assets::DMC_PICCOLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PIYOMON_SPRITE_SHEET_COLS, assets::DMC_PIYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_POYOMON_SPRITE_SHEET_COLS, assets::DMC_POYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_PUNIMON_SPRITE_SHEET_COLS, assets::DMC_PUNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_RAIDENMON_SPRITE_SHEET_COLS, assets::DMC_RAIDENMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_RAREMON_SPRITE_SHEET_COLS, assets::DMC_RAREMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_RUST_TYRANOMON_SPRITE_SHEET_COLS, assets::DMC_RUST_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SCUMON_SPRITE_SHEET_COLS, assets::DMC_SCUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SEADRAMON_SPRITE_SHEET_COLS, assets::DMC_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SHELLMON_SPRITE_SHEET_COLS, assets::DMC_SHELLMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SHIN_MONZAEMON_SPRITE_SHEET_COLS, assets::DMC_SHIN_MONZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SKULL_GREYMON_SPRITE_SHEET_COLS, assets::DMC_SKULL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_SKULL_MAMMON_SPRITE_SHEET_COLS, assets::DMC_SKULL_MAMMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TANEMON_SPRITE_SHEET_COLS, assets::DMC_TANEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TITAMON_SPRITE_SHEET_COLS, assets::DMC_TITAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TOKOMON_SPRITE_SHEET_COLS, assets::DMC_TOKOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TSUNOMON_SPRITE_SHEET_COLS, assets::DMC_TSUNOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TUNOMON_SPRITE_SHEET_COLS, assets::DMC_TUNOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TUSKMON_SPRITE_SHEET_COLS, assets::DMC_TUSKMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_TYRANOMON_SPRITE_SHEET_COLS, assets::DMC_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_UNIMON_SPRITE_SHEET_COLS, assets::DMC_UNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_VADEMON_SPRITE_SHEET_COLS, assets::DMC_VADEMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_VEGIMON_SPRITE_SHEET_COLS, assets::DMC_VEGIMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_WAR_GREYMON_SPRITE_SHEET_COLS, assets::DMC_WAR_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_WERE_GARURUMON_SPRITE_SHEET_COLS, assets::DMC_WERE_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_WHAMON_SPRITE_SHEET_COLS, assets::DMC_WHAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_YUKIDARUMON_SPRITE_SHEET_COLS, assets::DMC_YUKIDARUMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_YURAMON_SPRITE_SHEET_COLS, assets::DMC_YURAMON_SPRITE_SHEET_ROWS}, 
        {assets::DMC_ZURUMON_SPRITE_SHEET_COLS, assets::DMC_ZURUMON_SPRITE_SHEET_ROWS}, 
        
    };
    static const unsigned char* dmc_pngs_table[] = {
        dmc_agumon_png, 
        dmc_airdramon_png, 
        dmc_andromon_png, 
        dmc_angemon_png, 
        dmc_babydmon_png, 
        dmc_bakemon_png, 
        dmc_bancho_leomon_png, 
        dmc_bancho_mamemon_png, 
        dmc_betamon_png, 
        dmc_birdramon_png, 
        dmc_blitz_greymon_png, 
        dmc_bloom_lordmon_png, 
        dmc_botamon_png, 
        dmc_centalmon_png, 
        dmc_chaosdramon_png, 
        dmc_chaosmon_png, 
        dmc_chimairamon_png, 
        dmc_cockatrimon_png, 
        dmc_coelamon_png, 
        dmc_coronamon_png, 
        dmc_cres_garurumon_png, 
        dmc_cyclomon_png, 
        dmc_darkdramon_png, 
        dmc_dark_tyranomon_png, 
        dmc_deltamon_png, 
        dmc_devidramon_png, 
        dmc_devimon_png, 
        dmc_digitamamon_png, 
        dmc_drimogemon_png, 
        dmc_ebemon_png, 
        dmc_elecmon_png, 
        dmc_etemon_png, 
        dmc_ex_tyranomon_png, 
        dmc_flymon_png, 
        dmc_gabumon_png, 
        dmc_gaioumon_png, 
        dmc_gankoomon_png, 
        dmc_garurumon_png, 
        dmc_gazimon_png, 
        dmc_giromon_png, 
        dmc_gizamon_png, 
        dmc_gokumon_png, 
        dmc_greymon_png, 
        dmc_hi_andromon_png, 
        dmc_kabuterimon_png, 
        dmc_koromon_png, 
        dmc_kunemon_png, 
        dmc_kuwagamon_png, 
        dmc_leomon_png, 
        dmc_mamemon_png, 
        dmc_megadramon_png, 
        dmc_meramon_png, 
        dmc_metal_garurumon_png, 
        dmc_metal_greymon_png, 
        dmc_metal_greymon_virus_png, 
        dmc_metal_mamemon_png, 
        dmc_metal_tyranomon_png, 
        dmc_millenniumon_png, 
        dmc_mojyamon_png, 
        dmc_mojymon_png, 
        dmc_monochromon_png, 
        dmc_monzaemon_png, 
        dmc_mozaemon_png, 
        dmc_mugendramon_png, 
        dmc_nanimon_png, 
        dmc_nanomon_png, 
        dmc_numemon_png, 
        dmc_ogremon_png, 
        dmc_omegamon_alter_s_png, 
        dmc_omegamon_png, 
        dmc_orgemon_png, 
        dmc_pagumon_png, 
        dmc_palmon_png, 
        dmc_patamon_png, 
        dmc_petitmon_png, 
        dmc_piccolomon_png, 
        dmc_piyomon_png, 
        dmc_poyomon_png, 
        dmc_punimon_png, 
        dmc_raidenmon_png, 
        dmc_raremon_png, 
        dmc_rust_tyranomon_png, 
        dmc_scumon_png, 
        dmc_seadramon_png, 
        dmc_shellmon_png, 
        dmc_shin_monzaemon_png, 
        dmc_skull_greymon_png, 
        dmc_skull_mammon_png, 
        dmc_tanemon_png, 
        dmc_titamon_png, 
        dmc_tokomon_png, 
        dmc_tsunomon_png, 
        dmc_tunomon_png, 
        dmc_tuskmon_png, 
        dmc_tyranomon_png, 
        dmc_unimon_png, 
        dmc_vademon_png, 
        dmc_vegimon_png, 
        dmc_war_greymon_png, 
        dmc_were_garurumon_png, 
        dmc_whamon_png, 
        dmc_yukidarumon_png, 
        dmc_yuramon_png, 
        dmc_zurumon_png, 
        
    };
    static const size_t dmc_png_sizes_table[] = {
        dmc_agumon_png_size, 
        dmc_airdramon_png_size, 
        dmc_andromon_png_size, 
        dmc_angemon_png_size, 
        dmc_babydmon_png_size, 
        dmc_bakemon_png_size, 
        dmc_bancho_leomon_png_size, 
        dmc_bancho_mamemon_png_size, 
        dmc_betamon_png_size, 
        dmc_birdramon_png_size, 
        dmc_blitz_greymon_png_size, 
        dmc_bloom_lordmon_png_size, 
        dmc_botamon_png_size, 
        dmc_centalmon_png_size, 
        dmc_chaosdramon_png_size, 
        dmc_chaosmon_png_size, 
        dmc_chimairamon_png_size, 
        dmc_cockatrimon_png_size, 
        dmc_coelamon_png_size, 
        dmc_coronamon_png_size, 
        dmc_cres_garurumon_png_size, 
        dmc_cyclomon_png_size, 
        dmc_darkdramon_png_size, 
        dmc_dark_tyranomon_png_size, 
        dmc_deltamon_png_size, 
        dmc_devidramon_png_size, 
        dmc_devimon_png_size, 
        dmc_digitamamon_png_size, 
        dmc_drimogemon_png_size, 
        dmc_ebemon_png_size, 
        dmc_elecmon_png_size, 
        dmc_etemon_png_size, 
        dmc_ex_tyranomon_png_size, 
        dmc_flymon_png_size, 
        dmc_gabumon_png_size, 
        dmc_gaioumon_png_size, 
        dmc_gankoomon_png_size, 
        dmc_garurumon_png_size, 
        dmc_gazimon_png_size, 
        dmc_giromon_png_size, 
        dmc_gizamon_png_size, 
        dmc_gokumon_png_size, 
        dmc_greymon_png_size, 
        dmc_hi_andromon_png_size, 
        dmc_kabuterimon_png_size, 
        dmc_koromon_png_size, 
        dmc_kunemon_png_size, 
        dmc_kuwagamon_png_size, 
        dmc_leomon_png_size, 
        dmc_mamemon_png_size, 
        dmc_megadramon_png_size, 
        dmc_meramon_png_size, 
        dmc_metal_garurumon_png_size, 
        dmc_metal_greymon_png_size, 
        dmc_metal_greymon_virus_png_size, 
        dmc_metal_mamemon_png_size, 
        dmc_metal_tyranomon_png_size, 
        dmc_millenniumon_png_size, 
        dmc_mojyamon_png_size, 
        dmc_mojymon_png_size, 
        dmc_monochromon_png_size, 
        dmc_monzaemon_png_size, 
        dmc_mozaemon_png_size, 
        dmc_mugendramon_png_size, 
        dmc_nanimon_png_size, 
        dmc_nanomon_png_size, 
        dmc_numemon_png_size, 
        dmc_ogremon_png_size, 
        dmc_omegamon_alter_s_png_size, 
        dmc_omegamon_png_size, 
        dmc_orgemon_png_size, 
        dmc_pagumon_png_size, 
        dmc_palmon_png_size, 
        dmc_patamon_png_size, 
        dmc_petitmon_png_size, 
        dmc_piccolomon_png_size, 
        dmc_piyomon_png_size, 
        dmc_poyomon_png_size, 
        dmc_punimon_png_size, 
        dmc_raidenmon_png_size, 
        dmc_raremon_png_size, 
        dmc_rust_tyranomon_png_size, 
        dmc_scumon_png_size, 
        dmc_seadramon_png_size, 
        dmc_shellmon_png_size, 
        dmc_shin_monzaemon_png_size, 
        dmc_skull_greymon_png_size, 
        dmc_skull_mammon_png_size, 
        dmc_tanemon_png_size, 
        dmc_titamon_png_size, 
        dmc_tokomon_png_size, 
        dmc_tsunomon_png_size, 
        dmc_tunomon_png_size, 
        dmc_tuskmon_png_size, 
        dmc_tyranomon_png_size, 
        dmc_unimon_png_size, 
        dmc_vademon_png_size, 
        dmc_vegimon_png_size, 
        dmc_war_greymon_png_size, 
        dmc_were_garurumon_png_size, 
        dmc_whamon_png_size, 
        dmc_yukidarumon_png_size, 
        dmc_yuramon_png_size, 
        dmc_zurumon_png_size, 
        
    };
    static const char* dmc_names_table[] = {
        "agumon", 
        "airdramon", 
        "andromon", 
        "angemon", 
        "babydmon", 
        "bakemon", 
        "bancho_leomon", 
        "bancho_mamemon", 
        "betamon", 
        "birdramon", 
        "blitz_greymon", 
        "bloom_lordmon", 
        "botamon", 
        "centalmon", 
        "chaosdramon", 
        "chaosmon", 
        "chimairamon", 
        "cockatrimon", 
        "coelamon", 
        "coronamon", 
        "cres_garurumon", 
        "cyclomon", 
        "darkdramon", 
        "dark_tyranomon", 
        "deltamon", 
        "devidramon", 
        "devimon", 
        "digitamamon", 
        "drimogemon", 
        "ebemon", 
        "elecmon", 
        "etemon", 
        "ex_tyranomon", 
        "flymon", 
        "gabumon", 
        "gaioumon", 
        "gankoomon", 
        "garurumon", 
        "gazimon", 
        "giromon", 
        "gizamon", 
        "gokumon", 
        "greymon", 
        "hi_andromon", 
        "kabuterimon", 
        "koromon", 
        "kunemon", 
        "kuwagamon", 
        "leomon", 
        "mamemon", 
        "megadramon", 
        "meramon", 
        "metal_garurumon", 
        "metal_greymon", 
        "metal_greymon_virus", 
        "metal_mamemon", 
        "metal_tyranomon", 
        "millenniumon", 
        "mojyamon", 
        "mojymon", 
        "monochromon", 
        "monzaemon", 
        "mozaemon", 
        "mugendramon", 
        "nanimon", 
        "nanomon", 
        "numemon", 
        "ogremon", 
        "omegamon_alter_s", 
        "omegamon", 
        "orgemon", 
        "pagumon", 
        "palmon", 
        "patamon", 
        "petitmon", 
        "piccolomon", 
        "piyomon", 
        "poyomon", 
        "punimon", 
        "raidenmon", 
        "raremon", 
        "rust_tyranomon", 
        "scumon", 
        "seadramon", 
        "shellmon", 
        "shin_monzaemon", 
        "skull_greymon", 
        "skull_mammon", 
        "tanemon", 
        "titamon", 
        "tokomon", 
        "tsunomon", 
        "tunomon", 
        "tuskmon", 
        "tyranomon", 
        "unimon", 
        "vademon", 
        "vegimon", 
        "war_greymon", 
        "were_garurumon", 
        "whamon", 
        "yukidarumon", 
        "yuramon", 
        "zurumon", 
        
    };
    created_result_t<dm_sprite_sheet_t> load_dmc_sprite_sheet(const animation_thread_context_t& ctx, size_t index) {
        using namespace assets;
        assert(LEN_ARRAY(dmc_dims_table) == DMC_ANIM_COUNT);
        assert(LEN_ARRAY(dmc_pngs_table) == DMC_ANIM_COUNT);
        assert(LEN_ARRAY(dmc_png_sizes_table) == DMC_ANIM_COUNT);
        assert(LEN_ARRAY(dmc_names_table) == DMC_ANIM_COUNT);
        assert(index < DMC_ANIM_COUNT);
        return load_base_dm_anim(ctx, index, {dmc_pngs_table[index], dmc_png_sizes_table[index], dmc_names_table[index]}, dmc_dims_table[index].cols, dmc_dims_table[index].rows);
    }
    void init_all_dmc_anim(animation_thread_context_t& ctx) {
        using namespace assets;
        for (size_t i = 0;i < DMC_ANIM_COUNT;++i) {
            init_dmc_anim(ctx, i, {dmc_pngs_table[i], dmc_png_sizes_table[i], dmc_names_table[i]}, dmc_dims_table[i].cols, dmc_dims_table[i].rows);
        }
    }
}

