#ifndef BONGOCAT_ANIMATION_CONST_H
#define BONGOCAT_ANIMATION_CONST_H

// Bongocat Frames
#define BONGOCAT_FRAME_BOTH_UP 0
#define BONGOCAT_FRAME_LEFT_DOWN 1
#define BONGOCAT_FRAME_RIGHT_DOWN 2
#define BONGOCAT_FRAME_BOTH_DOWN 3

#ifndef FEATURE_INCLUDE_ONLY_BONGOCAT_EMBEDDED_ASSETS
// Digimon (Sprite Sheet) Frames
#define DIGIMON_FRAME_IDLE1 0
#define DIGIMON_FRAME_IDLE2 1
#define DIGIMON_FRAME_ANGRY 2 // Angry/Refuse or Hit (Fallback), Eat Frame Fallback
#define DIGIMON_FRAME_DOWN1 3 // Sleep/Discipline Fallback
#define DIGIMON_FRAME_HAPPY 4
#define DIGIMON_FRAME_EAT1 5
#define DIGIMON_FRAME_SLEEP1 6
#define DIGIMON_FRAME_REFUSE 7
#define DIGIMON_FRAME_SAD 8

// optional frames
#define DIGIMON_FRAME_DOWN2 9
#define DIGIMON_FRAME_EAT2 10
#define DIGIMON_FRAME_SLEEP2 11
#define DIGIMON_FRAME_ATTACK 12

#define DIGIMON_FRAME_MOVEMENT1 13
#define DIGIMON_FRAME_MOVEMENT2 14

#define HAPPY_CHANCE_PERCENT 60
#endif

#endif