#include "core/bongocat.h"
#include "utils/memory.h"
#include "graphics/animation_thread_context.h"
#include "graphics/sprite_sheet.h"
#include "image_loader/base_dm/load_dm.h"
#include "embedded_assets/dm20/dm20.hpp"
#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dm20/dm20_sprite.h"
#include "image_loader/dm20/load_images_dm20.h"
#include "embedded_assets/dm20/dm20_images.h"
#include "image_loader/dm/load_images_dm.h"

#include <climits>
#include <cstddef>
#include <cstdint>

/// @NOTE: Generated embedded assets dm20

namespace bongocat::animation {
    static constexpr assets::embedded_sprite_sheet_dims_t dm20_dims_table[] = {
        {assets::DM20_AEGISDRAMON_SPRITE_SHEET_COLS, assets::DM20_AEGISDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_AGUMON_SPRITE_SHEET_COLS, assets::DM20_AGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_AIRDRAMON_SPRITE_SHEET_COLS, assets::DM20_AIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ALPHAMON_SPRITE_SHEET_COLS, assets::DM20_ALPHAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ANDROMON_SPRITE_SHEET_COLS, assets::DM20_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ANGEMON_SPRITE_SHEET_COLS, assets::DM20_ANGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_APOLLOMON_SPRITE_SHEET_COLS, assets::DM20_APOLLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BABYDMON_SPRITE_SHEET_COLS, assets::DM20_BABYDMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BAKEMON_SPRITE_SHEET_COLS, assets::DM20_BAKEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BANCHO_MAMEMON_SPRITE_SHEET_COLS, assets::DM20_BANCHO_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BAO_HACKMON_SPRITE_SHEET_COLS, assets::DM20_BAO_HACKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BETAMON_SPRITE_SHEET_COLS, assets::DM20_BETAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BIRDRAMON_SPRITE_SHEET_COLS, assets::DM20_BIRDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BLITZ_GREYMON_SPRITE_SHEET_COLS, assets::DM20_BLITZ_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BOTAMON_SPRITE_SHEET_COLS, assets::DM20_BOTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_BREAKDRAMON_SPRITE_SHEET_COLS, assets::DM20_BREAKDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_CENTALMON_SPRITE_SHEET_COLS, assets::DM20_CENTALMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_COCKATRIMON_SPRITE_SHEET_COLS, assets::DM20_COCKATRIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_COELAMON_SPRITE_SHEET_COLS, assets::DM20_COELAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_COREDRAMON_BLUE_SPRITE_SHEET_COLS, assets::DM20_COREDRAMON_BLUE_SPRITE_SHEET_ROWS}, 
        {assets::DM20_COREDRAMON_GREEN_SPRITE_SHEET_COLS, assets::DM20_COREDRAMON_GREEN_SPRITE_SHEET_ROWS}, 
        {assets::DM20_CORONAMON_SPRITE_SHEET_COLS, assets::DM20_CORONAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_CRESCEMON_SPRITE_SHEET_COLS, assets::DM20_CRESCEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_CRES_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_CRES_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_CYCLOMON_SPRITE_SHEET_COLS, assets::DM20_CYCLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DARK_TYRANOMON_SPRITE_SHEET_COLS, assets::DM20_DARK_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DELTAMON_SPRITE_SHEET_COLS, assets::DM20_DELTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DEVIDRAMON_SPRITE_SHEET_COLS, assets::DM20_DEVIDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DEVIMON_SPRITE_SHEET_COLS, assets::DM20_DEVIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DIANAMON_SPRITE_SHEET_COLS, assets::DM20_DIANAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DIGITAMAMON_SPRITE_SHEET_COLS, assets::DM20_DIGITAMAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DODOMON_SPRITE_SHEET_COLS, assets::DM20_DODOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DORIMON_SPRITE_SHEET_COLS, assets::DM20_DORIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DORUGAMON_SPRITE_SHEET_COLS, assets::DM20_DORUGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DORUGUREMON_SPRITE_SHEET_COLS, assets::DM20_DORUGUREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DORUMON_SPRITE_SHEET_COLS, assets::DM20_DORUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DRACOMON_SPRITE_SHEET_COLS, assets::DM20_DRACOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DRIMOGEMON_SPRITE_SHEET_COLS, assets::DM20_DRIMOGEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DURAMON_SPRITE_SHEET_COLS, assets::DM20_DURAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DURANDAMON_SPRITE_SHEET_COLS, assets::DM20_DURANDAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_DURANDRAMON_SPRITE_SHEET_COLS, assets::DM20_DURANDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ELECMON_SPRITE_SHEET_COLS, assets::DM20_ELECMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ETEMON_SPRITE_SHEET_COLS, assets::DM20_ETEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_EXAMON_SPRITE_SHEET_COLS, assets::DM20_EXAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_EX_TYRANOMON_SPRITE_SHEET_COLS, assets::DM20_EX_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_FIRAMON_SPRITE_SHEET_COLS, assets::DM20_FIRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_FLAREMON_SPRITE_SHEET_COLS, assets::DM20_FLAREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_FLYMON_SPRITE_SHEET_COLS, assets::DM20_FLYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GABUMON_SPRITE_SHEET_COLS, assets::DM20_GABUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GAZIMON_SPRITE_SHEET_COLS, assets::DM20_GAZIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GIROMON_SPRITE_SHEET_COLS, assets::DM20_GIROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GIZAMON_SPRITE_SHEET_COLS, assets::DM20_GIZAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GRACE_NOVAMON_SPRITE_SHEET_COLS, assets::DM20_GRACE_NOVAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GREYMON_SPRITE_SHEET_COLS, assets::DM20_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_GROUNDRAMON_SPRITE_SHEET_COLS, assets::DM20_GROUNDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_HACKMON_SPRITE_SHEET_COLS, assets::DM20_HACKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_HI_ANDROMON_SPRITE_SHEET_COLS, assets::DM20_HI_ANDROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_JESMON_SPRITE_SHEET_COLS, assets::DM20_JESMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_JIJIMON_SPRITE_SHEET_COLS, assets::DM20_JIJIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_KABUTERIMON_SPRITE_SHEET_COLS, assets::DM20_KABUTERIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_KING_ETEMON_SPRITE_SHEET_COLS, assets::DM20_KING_ETEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_KOROMON_SPRITE_SHEET_COLS, assets::DM20_KOROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_KUNEMON_SPRITE_SHEET_COLS, assets::DM20_KUNEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_KUWAGAMON_SPRITE_SHEET_COLS, assets::DM20_KUWAGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_LEKISMON_SPRITE_SHEET_COLS, assets::DM20_LEKISMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_LEOMON_SPRITE_SHEET_COLS, assets::DM20_LEOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_LUNAMON_SPRITE_SHEET_COLS, assets::DM20_LUNAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MAMEMON_SPRITE_SHEET_COLS, assets::DM20_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MEGADRAMON_SPRITE_SHEET_COLS, assets::DM20_MEGADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MEICOOMON_SPRITE_SHEET_COLS, assets::DM20_MEICOOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MEICRACKMON_SPRITE_SHEET_COLS, assets::DM20_MEICRACKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MERAMON_SPRITE_SHEET_COLS, assets::DM20_MERAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_METAL_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_METAL_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_METAL_GREYMON_SPRITE_SHEET_COLS, assets::DM20_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_METAL_MAMEMON_SPRITE_SHEET_COLS, assets::DM20_METAL_MAMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_METAL_TYRANOMON_SPRITE_SHEET_COLS, assets::DM20_METAL_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MOJYAMON_SPRITE_SHEET_COLS, assets::DM20_MOJYAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MONCHROMON_SPRITE_SHEET_COLS, assets::DM20_MONCHROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MONOCHROMON_SPRITE_SHEET_COLS, assets::DM20_MONOCHROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MONZAEMON_SPRITE_SHEET_COLS, assets::DM20_MONZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MOZAEMON_SPRITE_SHEET_COLS, assets::DM20_MOZAEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_MUGENDRAMON_SPRITE_SHEET_COLS, assets::DM20_MUGENDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_NANIMON_SPRITE_SHEET_COLS, assets::DM20_NANIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_NANOMON_SPRITE_SHEET_COLS, assets::DM20_NANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_NUMEMON_SPRITE_SHEET_COLS, assets::DM20_NUMEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_NYAROMON_SPRITE_SHEET_COLS, assets::DM20_NYAROMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_OGREMON_SPRITE_SHEET_COLS, assets::DM20_OGREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_OMEGAMON_ALTER_S_SPRITE_SHEET_COLS, assets::DM20_OMEGAMON_ALTER_S_SPRITE_SHEET_ROWS}, 
        {assets::DM20_OMEGAMON_SPRITE_SHEET_COLS, assets::DM20_OMEGAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PAGUMON_SPRITE_SHEET_COLS, assets::DM20_PAGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PAKUMON_SPRITE_SHEET_COLS, assets::DM20_PAKUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PALMON_SPRITE_SHEET_COLS, assets::DM20_PALMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PATAMON_SPRITE_SHEET_COLS, assets::DM20_PATAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PETITMON_SPRITE_SHEET_COLS, assets::DM20_PETITMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PICCOLOMON_SPRITE_SHEET_COLS, assets::DM20_PICCOLOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PINOCHIMON_SPRITE_SHEET_COLS, assets::DM20_PINOCHIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PITCHMON_SPRITE_SHEET_COLS, assets::DM20_PITCHMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PIYOMON_SPRITE_SHEET_COLS, assets::DM20_PIYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PLOTMON_SPRITE_SHEET_COLS, assets::DM20_PLOTMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_POYOMON_SPRITE_SHEET_COLS, assets::DM20_POYOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PUKAMON_SPRITE_SHEET_COLS, assets::DM20_PUKAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_PUNIMON_SPRITE_SHEET_COLS, assets::DM20_PUNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_RAREMON_SPRITE_SHEET_COLS, assets::DM20_RAREMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_RASIELMON_SPRITE_SHEET_COLS, assets::DM20_RASIELMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_RUST_TYRANOMON_SPRITE_SHEET_COLS, assets::DM20_RUST_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SAKUMON_SPRITE_SHEET_COLS, assets::DM20_SAKUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SAKUTTOMON_SPRITE_SHEET_COLS, assets::DM20_SAKUTTOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SAVIOR_HACKMON_SPRITE_SHEET_COLS, assets::DM20_SAVIOR_HACKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SCUMON_SPRITE_SHEET_COLS, assets::DM20_SCUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SEADRAMON_SPRITE_SHEET_COLS, assets::DM20_SEADRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SHELLMON_SPRITE_SHEET_COLS, assets::DM20_SHELLMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SKULL_GREYMON_SPRITE_SHEET_COLS, assets::DM20_SKULL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SKULL_MAMMON_SPRITE_SHEET_COLS, assets::DM20_SKULL_MAMMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_SLAYERDRAMON_SPRITE_SHEET_COLS, assets::DM20_SLAYERDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TAICHI_METAL_GREYMON_SPRITE_SHEET_COLS, assets::DM20_TAICHI_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TAICHIS_AGUMON_SPRITE_SHEET_COLS, assets::DM20_TAICHIS_AGUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TAICHIS_GREYMON_SPRITE_SHEET_COLS, assets::DM20_TAICHIS_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TAICHIS_METAL_GREYMON_SPRITE_SHEET_COLS, assets::DM20_TAICHIS_METAL_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TAICHIS_WAR_GREYMON_SPRITE_SHEET_COLS, assets::DM20_TAICHIS_WAR_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TANEMON_SPRITE_SHEET_COLS, assets::DM20_TANEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TITAMON_SPRITE_SHEET_COLS, assets::DM20_TITAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TOKOMON_SPRITE_SHEET_COLS, assets::DM20_TOKOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TSUNOMON_SPRITE_SHEET_COLS, assets::DM20_TSUNOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TUNOMON_SPRITE_SHEET_COLS, assets::DM20_TUNOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TUSKMON_SPRITE_SHEET_COLS, assets::DM20_TUSKMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_TYRANOMON_SPRITE_SHEET_COLS, assets::DM20_TYRANOMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_UNIMON_SPRITE_SHEET_COLS, assets::DM20_UNIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_VADEMON_SPRITE_SHEET_COLS, assets::DM20_VADEMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_VEGIMON_SPRITE_SHEET_COLS, assets::DM20_VEGIMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_WAR_GREYMON_SPRITE_SHEET_COLS, assets::DM20_WAR_GREYMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_WERE_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_WERE_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_WHAMON_SPRITE_SHEET_COLS, assets::DM20_WHAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_WINGDRAMON_SPRITE_SHEET_COLS, assets::DM20_WINGDRAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YAMATO_GABUMON_SPRITE_SHEET_COLS, assets::DM20_YAMATO_GABUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YAMATOS_GABUMON_SPRITE_SHEET_COLS, assets::DM20_YAMATOS_GABUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YAMATOS_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_YAMATOS_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YAMATOS_METAL_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_YAMATOS_METAL_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YAMATOS_WERE_GARURUMON_SPRITE_SHEET_COLS, assets::DM20_YAMATOS_WERE_GARURUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YUKIDARUMON_SPRITE_SHEET_COLS, assets::DM20_YUKIDARUMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YUKIMI_BOTAMON_SPRITE_SHEET_COLS, assets::DM20_YUKIMI_BOTAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_YURAMON_SPRITE_SHEET_COLS, assets::DM20_YURAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ZUBAEAGERMON_SPRITE_SHEET_COLS, assets::DM20_ZUBAEAGERMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ZUBAMON_SPRITE_SHEET_COLS, assets::DM20_ZUBAMON_SPRITE_SHEET_ROWS}, 
        {assets::DM20_ZURUMON_SPRITE_SHEET_COLS, assets::DM20_ZURUMON_SPRITE_SHEET_ROWS}, 
        
    };
    static const unsigned char* dm20_pngs_table[] = {
        dm20_aegisdramon_png, 
        dm20_agumon_png, 
        dm20_airdramon_png, 
        dm20_alphamon_png, 
        dm20_andromon_png, 
        dm20_angemon_png, 
        dm20_apollomon_png, 
        dm20_babydmon_png, 
        dm20_bakemon_png, 
        dm20_bancho_mamemon_png, 
        dm20_bao_hackmon_png, 
        dm20_betamon_png, 
        dm20_birdramon_png, 
        dm20_blitz_greymon_png, 
        dm20_botamon_png, 
        dm20_breakdramon_png, 
        dm20_centalmon_png, 
        dm20_cockatrimon_png, 
        dm20_coelamon_png, 
        dm20_coredramon_blue_png, 
        dm20_coredramon_green_png, 
        dm20_coronamon_png, 
        dm20_crescemon_png, 
        dm20_cres_garurumon_png, 
        dm20_cyclomon_png, 
        dm20_dark_tyranomon_png, 
        dm20_deltamon_png, 
        dm20_devidramon_png, 
        dm20_devimon_png, 
        dm20_dianamon_png, 
        dm20_digitamamon_png, 
        dm20_dodomon_png, 
        dm20_dorimon_png, 
        dm20_dorugamon_png, 
        dm20_doruguremon_png, 
        dm20_dorumon_png, 
        dm20_dracomon_png, 
        dm20_drimogemon_png, 
        dm20_duramon_png, 
        dm20_durandamon_png, 
        dm20_durandramon_png, 
        dm20_elecmon_png, 
        dm20_etemon_png, 
        dm20_examon_png, 
        dm20_ex_tyranomon_png, 
        dm20_firamon_png, 
        dm20_flaremon_png, 
        dm20_flymon_png, 
        dm20_gabumon_png, 
        dm20_garurumon_png, 
        dm20_gazimon_png, 
        dm20_giromon_png, 
        dm20_gizamon_png, 
        dm20_grace_novamon_png, 
        dm20_greymon_png, 
        dm20_groundramon_png, 
        dm20_hackmon_png, 
        dm20_hi_andromon_png, 
        dm20_jesmon_png, 
        dm20_jijimon_png, 
        dm20_kabuterimon_png, 
        dm20_king_etemon_png, 
        dm20_koromon_png, 
        dm20_kunemon_png, 
        dm20_kuwagamon_png, 
        dm20_lekismon_png, 
        dm20_leomon_png, 
        dm20_lunamon_png, 
        dm20_mamemon_png, 
        dm20_megadramon_png, 
        dm20_meicoomon_png, 
        dm20_meicrackmon_png, 
        dm20_meramon_png, 
        dm20_metal_garurumon_png, 
        dm20_metal_greymon_png, 
        dm20_metal_mamemon_png, 
        dm20_metal_tyranomon_png, 
        dm20_mojyamon_png, 
        dm20_monchromon_png, 
        dm20_monochromon_png, 
        dm20_monzaemon_png, 
        dm20_mozaemon_png, 
        dm20_mugendramon_png, 
        dm20_nanimon_png, 
        dm20_nanomon_png, 
        dm20_numemon_png, 
        dm20_nyaromon_png, 
        dm20_ogremon_png, 
        dm20_omegamon_alter_s_png, 
        dm20_omegamon_png, 
        dm20_pagumon_png, 
        dm20_pakumon_png, 
        dm20_palmon_png, 
        dm20_patamon_png, 
        dm20_petitmon_png, 
        dm20_piccolomon_png, 
        dm20_pinochimon_png, 
        dm20_pitchmon_png, 
        dm20_piyomon_png, 
        dm20_plotmon_png, 
        dm20_poyomon_png, 
        dm20_pukamon_png, 
        dm20_punimon_png, 
        dm20_raremon_png, 
        dm20_rasielmon_png, 
        dm20_rust_tyranomon_png, 
        dm20_sakumon_png, 
        dm20_sakuttomon_png, 
        dm20_savior_hackmon_png, 
        dm20_scumon_png, 
        dm20_seadramon_png, 
        dm20_shellmon_png, 
        dm20_skull_greymon_png, 
        dm20_skull_mammon_png, 
        dm20_slayerdramon_png, 
        dm20_taichi_metal_greymon_png, 
        dm20_taichis_agumon_png, 
        dm20_taichis_greymon_png, 
        dm20_taichis_metal_greymon_png, 
        dm20_taichis_war_greymon_png, 
        dm20_tanemon_png, 
        dm20_titamon_png, 
        dm20_tokomon_png, 
        dm20_tsunomon_png, 
        dm20_tunomon_png, 
        dm20_tuskmon_png, 
        dm20_tyranomon_png, 
        dm20_unimon_png, 
        dm20_vademon_png, 
        dm20_vegimon_png, 
        dm20_war_greymon_png, 
        dm20_were_garurumon_png, 
        dm20_whamon_png, 
        dm20_wingdramon_png, 
        dm20_yamato_gabumon_png, 
        dm20_yamatos_gabumon_png, 
        dm20_yamatos_garurumon_png, 
        dm20_yamatos_metal_garurumon_png, 
        dm20_yamatos_were_garurumon_png, 
        dm20_yukidarumon_png, 
        dm20_yukimi_botamon_png, 
        dm20_yuramon_png, 
        dm20_zubaeagermon_png, 
        dm20_zubamon_png, 
        dm20_zurumon_png, 
        
    };
    static const size_t dm20_png_sizes_table[] = {
        dm20_aegisdramon_png_size, 
        dm20_agumon_png_size, 
        dm20_airdramon_png_size, 
        dm20_alphamon_png_size, 
        dm20_andromon_png_size, 
        dm20_angemon_png_size, 
        dm20_apollomon_png_size, 
        dm20_babydmon_png_size, 
        dm20_bakemon_png_size, 
        dm20_bancho_mamemon_png_size, 
        dm20_bao_hackmon_png_size, 
        dm20_betamon_png_size, 
        dm20_birdramon_png_size, 
        dm20_blitz_greymon_png_size, 
        dm20_botamon_png_size, 
        dm20_breakdramon_png_size, 
        dm20_centalmon_png_size, 
        dm20_cockatrimon_png_size, 
        dm20_coelamon_png_size, 
        dm20_coredramon_blue_png_size, 
        dm20_coredramon_green_png_size, 
        dm20_coronamon_png_size, 
        dm20_crescemon_png_size, 
        dm20_cres_garurumon_png_size, 
        dm20_cyclomon_png_size, 
        dm20_dark_tyranomon_png_size, 
        dm20_deltamon_png_size, 
        dm20_devidramon_png_size, 
        dm20_devimon_png_size, 
        dm20_dianamon_png_size, 
        dm20_digitamamon_png_size, 
        dm20_dodomon_png_size, 
        dm20_dorimon_png_size, 
        dm20_dorugamon_png_size, 
        dm20_doruguremon_png_size, 
        dm20_dorumon_png_size, 
        dm20_dracomon_png_size, 
        dm20_drimogemon_png_size, 
        dm20_duramon_png_size, 
        dm20_durandamon_png_size, 
        dm20_durandramon_png_size, 
        dm20_elecmon_png_size, 
        dm20_etemon_png_size, 
        dm20_examon_png_size, 
        dm20_ex_tyranomon_png_size, 
        dm20_firamon_png_size, 
        dm20_flaremon_png_size, 
        dm20_flymon_png_size, 
        dm20_gabumon_png_size, 
        dm20_garurumon_png_size, 
        dm20_gazimon_png_size, 
        dm20_giromon_png_size, 
        dm20_gizamon_png_size, 
        dm20_grace_novamon_png_size, 
        dm20_greymon_png_size, 
        dm20_groundramon_png_size, 
        dm20_hackmon_png_size, 
        dm20_hi_andromon_png_size, 
        dm20_jesmon_png_size, 
        dm20_jijimon_png_size, 
        dm20_kabuterimon_png_size, 
        dm20_king_etemon_png_size, 
        dm20_koromon_png_size, 
        dm20_kunemon_png_size, 
        dm20_kuwagamon_png_size, 
        dm20_lekismon_png_size, 
        dm20_leomon_png_size, 
        dm20_lunamon_png_size, 
        dm20_mamemon_png_size, 
        dm20_megadramon_png_size, 
        dm20_meicoomon_png_size, 
        dm20_meicrackmon_png_size, 
        dm20_meramon_png_size, 
        dm20_metal_garurumon_png_size, 
        dm20_metal_greymon_png_size, 
        dm20_metal_mamemon_png_size, 
        dm20_metal_tyranomon_png_size, 
        dm20_mojyamon_png_size, 
        dm20_monchromon_png_size, 
        dm20_monochromon_png_size, 
        dm20_monzaemon_png_size, 
        dm20_mozaemon_png_size, 
        dm20_mugendramon_png_size, 
        dm20_nanimon_png_size, 
        dm20_nanomon_png_size, 
        dm20_numemon_png_size, 
        dm20_nyaromon_png_size, 
        dm20_ogremon_png_size, 
        dm20_omegamon_alter_s_png_size, 
        dm20_omegamon_png_size, 
        dm20_pagumon_png_size, 
        dm20_pakumon_png_size, 
        dm20_palmon_png_size, 
        dm20_patamon_png_size, 
        dm20_petitmon_png_size, 
        dm20_piccolomon_png_size, 
        dm20_pinochimon_png_size, 
        dm20_pitchmon_png_size, 
        dm20_piyomon_png_size, 
        dm20_plotmon_png_size, 
        dm20_poyomon_png_size, 
        dm20_pukamon_png_size, 
        dm20_punimon_png_size, 
        dm20_raremon_png_size, 
        dm20_rasielmon_png_size, 
        dm20_rust_tyranomon_png_size, 
        dm20_sakumon_png_size, 
        dm20_sakuttomon_png_size, 
        dm20_savior_hackmon_png_size, 
        dm20_scumon_png_size, 
        dm20_seadramon_png_size, 
        dm20_shellmon_png_size, 
        dm20_skull_greymon_png_size, 
        dm20_skull_mammon_png_size, 
        dm20_slayerdramon_png_size, 
        dm20_taichi_metal_greymon_png_size, 
        dm20_taichis_agumon_png_size, 
        dm20_taichis_greymon_png_size, 
        dm20_taichis_metal_greymon_png_size, 
        dm20_taichis_war_greymon_png_size, 
        dm20_tanemon_png_size, 
        dm20_titamon_png_size, 
        dm20_tokomon_png_size, 
        dm20_tsunomon_png_size, 
        dm20_tunomon_png_size, 
        dm20_tuskmon_png_size, 
        dm20_tyranomon_png_size, 
        dm20_unimon_png_size, 
        dm20_vademon_png_size, 
        dm20_vegimon_png_size, 
        dm20_war_greymon_png_size, 
        dm20_were_garurumon_png_size, 
        dm20_whamon_png_size, 
        dm20_wingdramon_png_size, 
        dm20_yamato_gabumon_png_size, 
        dm20_yamatos_gabumon_png_size, 
        dm20_yamatos_garurumon_png_size, 
        dm20_yamatos_metal_garurumon_png_size, 
        dm20_yamatos_were_garurumon_png_size, 
        dm20_yukidarumon_png_size, 
        dm20_yukimi_botamon_png_size, 
        dm20_yuramon_png_size, 
        dm20_zubaeagermon_png_size, 
        dm20_zubamon_png_size, 
        dm20_zurumon_png_size, 
        
    };
    static const char* dm20_names_table[] = {
        "aegisdramon", 
        "agumon", 
        "airdramon", 
        "alphamon", 
        "andromon", 
        "angemon", 
        "apollomon", 
        "babydmon", 
        "bakemon", 
        "bancho_mamemon", 
        "bao_hackmon", 
        "betamon", 
        "birdramon", 
        "blitz_greymon", 
        "botamon", 
        "breakdramon", 
        "centalmon", 
        "cockatrimon", 
        "coelamon", 
        "coredramon_blue", 
        "coredramon_green", 
        "coronamon", 
        "crescemon", 
        "cres_garurumon", 
        "cyclomon", 
        "dark_tyranomon", 
        "deltamon", 
        "devidramon", 
        "devimon", 
        "dianamon", 
        "digitamamon", 
        "dodomon", 
        "dorimon", 
        "dorugamon", 
        "doruguremon", 
        "dorumon", 
        "dracomon", 
        "drimogemon", 
        "duramon", 
        "durandamon", 
        "durandramon", 
        "elecmon", 
        "etemon", 
        "examon", 
        "ex_tyranomon", 
        "firamon", 
        "flaremon", 
        "flymon", 
        "gabumon", 
        "garurumon", 
        "gazimon", 
        "giromon", 
        "gizamon", 
        "grace_novamon", 
        "greymon", 
        "groundramon", 
        "hackmon", 
        "hi_andromon", 
        "jesmon", 
        "jijimon", 
        "kabuterimon", 
        "king_etemon", 
        "koromon", 
        "kunemon", 
        "kuwagamon", 
        "lekismon", 
        "leomon", 
        "lunamon", 
        "mamemon", 
        "megadramon", 
        "meicoomon", 
        "meicrackmon", 
        "meramon", 
        "metal_garurumon", 
        "metal_greymon", 
        "metal_mamemon", 
        "metal_tyranomon", 
        "mojyamon", 
        "monchromon", 
        "monochromon", 
        "monzaemon", 
        "mozaemon", 
        "mugendramon", 
        "nanimon", 
        "nanomon", 
        "numemon", 
        "nyaromon", 
        "ogremon", 
        "omegamon_alter_s", 
        "omegamon", 
        "pagumon", 
        "pakumon", 
        "palmon", 
        "patamon", 
        "petitmon", 
        "piccolomon", 
        "pinochimon", 
        "pitchmon", 
        "piyomon", 
        "plotmon", 
        "poyomon", 
        "pukamon", 
        "punimon", 
        "raremon", 
        "rasielmon", 
        "rust_tyranomon", 
        "sakumon", 
        "sakuttomon", 
        "savior_hackmon", 
        "scumon", 
        "seadramon", 
        "shellmon", 
        "skull_greymon", 
        "skull_mammon", 
        "slayerdramon", 
        "taichi_metal_greymon", 
        "taichis_agumon", 
        "taichis_greymon", 
        "taichis_metal_greymon", 
        "taichis_war_greymon", 
        "tanemon", 
        "titamon", 
        "tokomon", 
        "tsunomon", 
        "tunomon", 
        "tuskmon", 
        "tyranomon", 
        "unimon", 
        "vademon", 
        "vegimon", 
        "war_greymon", 
        "were_garurumon", 
        "whamon", 
        "wingdramon", 
        "yamato_gabumon", 
        "yamatos_gabumon", 
        "yamatos_garurumon", 
        "yamatos_metal_garurumon", 
        "yamatos_were_garurumon", 
        "yukidarumon", 
        "yukimi_botamon", 
        "yuramon", 
        "zubaeagermon", 
        "zubamon", 
        "zurumon", 
        
    };
    created_result_t<dm_sprite_sheet_t> load_dm20_sprite_sheet(const animation_thread_context_t& ctx, size_t index) {
        using namespace assets;
        assert(LEN_ARRAY(dm20_dims_table) == DM20_ANIM_COUNT);
        assert(LEN_ARRAY(dm20_pngs_table) == DM20_ANIM_COUNT);
        assert(LEN_ARRAY(dm20_png_sizes_table) == DM20_ANIM_COUNT);
        assert(LEN_ARRAY(dm20_names_table) == DM20_ANIM_COUNT);
        assert(index < DM20_ANIM_COUNT);
        assert(LEN_ARRAY(dm20_pngs_table) <= INT32_MAX);
        assert(index < INT32_MAX);
        return load_base_dm_anim(ctx, index, {dm20_pngs_table[index], dm20_png_sizes_table[index], dm20_names_table[index]}, dm20_dims_table[index].cols, dm20_dims_table[index].rows);
    }
    void init_all_dm20_anim(animation_thread_context_t& ctx) {
        using namespace assets;
        for (size_t i = 0;i < DM20_ANIM_COUNT;++i) {
            init_dm20_anim(ctx, i, {dm20_pngs_table[i], dm20_png_sizes_table[i], dm20_names_table[i]}, dm20_dims_table[i].cols, dm20_dims_table[i].rows);
        }
    }
}

