#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dm20/dm20.hpp"
#include "dm20_config_parse_animation_name.h"

namespace bongocat::assets {
    static const config_animation_entry_t dm20_animation_table[] = {
        { DM20_AEGISDRAMON_NAME, DM20_AEGISDRAMON_ID, DM20_AEGISDRAMON_FQID, DM20_AEGISDRAMON_FQNAME, DM20_AEGISDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_AEGISDRAMON_NAME, DM20_AEGISDRAMON_ID, "dm:aegisdramon", "dm:Aegisdramon", DM20_AEGISDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Aegisdramon
        { DM20_AGUMON_NAME, DM20_AGUMON_ID, DM20_AGUMON_FQID, DM20_AGUMON_FQNAME, DM20_AGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_AGUMON_NAME, DM20_AGUMON_ID, "dm:agumon", "dm:Agumon", DM20_AGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Agumon
        { DM20_AIRDRAMON_NAME, DM20_AIRDRAMON_ID, DM20_AIRDRAMON_FQID, DM20_AIRDRAMON_FQNAME, DM20_AIRDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_AIRDRAMON_NAME, DM20_AIRDRAMON_ID, "dm:airdramon", "dm:Airdramon", DM20_AIRDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Airdramon
        { DM20_ALPHAMON_NAME, DM20_ALPHAMON_ID, DM20_ALPHAMON_FQID, DM20_ALPHAMON_FQNAME, DM20_ALPHAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ALPHAMON_NAME, DM20_ALPHAMON_ID, "dm:alphamon", "dm:Alphamon", DM20_ALPHAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Alphamon
        { DM20_ANDROMON_NAME, DM20_ANDROMON_ID, DM20_ANDROMON_FQID, DM20_ANDROMON_FQNAME, DM20_ANDROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ANDROMON_NAME, DM20_ANDROMON_ID, "dm:andromon", "dm:Andromon", DM20_ANDROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Andromon
        { DM20_ANGEMON_NAME, DM20_ANGEMON_ID, DM20_ANGEMON_FQID, DM20_ANGEMON_FQNAME, DM20_ANGEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ANGEMON_NAME, DM20_ANGEMON_ID, "dm:angemon", "dm:Angemon", DM20_ANGEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Angemon
        { DM20_APOLLOMON_NAME, DM20_APOLLOMON_ID, DM20_APOLLOMON_FQID, DM20_APOLLOMON_FQNAME, DM20_APOLLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_APOLLOMON_NAME, DM20_APOLLOMON_ID, "dm:apollomon", "dm:Apollomon", DM20_APOLLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Apollomon
        { DM20_BABYDMON_NAME, DM20_BABYDMON_ID, DM20_BABYDMON_FQID, DM20_BABYDMON_FQNAME, DM20_BABYDMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BABYDMON_NAME, DM20_BABYDMON_ID, "dm:babydmon", "dm:Babydmon", DM20_BABYDMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Babydmon
        { DM20_BAKEMON_NAME, DM20_BAKEMON_ID, DM20_BAKEMON_FQID, DM20_BAKEMON_FQNAME, DM20_BAKEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BAKEMON_NAME, DM20_BAKEMON_ID, "dm:bakemon", "dm:Bakemon", DM20_BAKEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Bakemon
        { DM20_BANCHO_MAMEMON_NAME, DM20_BANCHO_MAMEMON_ID, DM20_BANCHO_MAMEMON_FQID, DM20_BANCHO_MAMEMON_FQNAME, DM20_BANCHO_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BANCHO_MAMEMON_NAME, DM20_BANCHO_MAMEMON_ID, "dm:bancho_mamemon", "dm:Bancho Mamemon", DM20_BANCHO_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Bancho Mamemon
        { DM20_BAO_HACKMON_NAME, DM20_BAO_HACKMON_ID, DM20_BAO_HACKMON_FQID, DM20_BAO_HACKMON_FQNAME, DM20_BAO_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BAO_HACKMON_NAME, DM20_BAO_HACKMON_ID, "dm:bao_hackmon", "dm:Bao Hackmon", DM20_BAO_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Bao Hackmon
        { DM20_BETAMON_NAME, DM20_BETAMON_ID, DM20_BETAMON_FQID, DM20_BETAMON_FQNAME, DM20_BETAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BETAMON_NAME, DM20_BETAMON_ID, "dm:betamon", "dm:Betamon", DM20_BETAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Betamon
        { DM20_BIRDRAMON_NAME, DM20_BIRDRAMON_ID, DM20_BIRDRAMON_FQID, DM20_BIRDRAMON_FQNAME, DM20_BIRDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BIRDRAMON_NAME, DM20_BIRDRAMON_ID, "dm:birdramon", "dm:Birdramon", DM20_BIRDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Birdramon
        { DM20_BLITZ_GREYMON_NAME, DM20_BLITZ_GREYMON_ID, DM20_BLITZ_GREYMON_FQID, DM20_BLITZ_GREYMON_FQNAME, DM20_BLITZ_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BLITZ_GREYMON_NAME, DM20_BLITZ_GREYMON_ID, "dm:blitz_greymon", "dm:Blitz Greymon", DM20_BLITZ_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Blitz Greymon
        { DM20_BOTAMON_NAME, DM20_BOTAMON_ID, DM20_BOTAMON_FQID, DM20_BOTAMON_FQNAME, DM20_BOTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BOTAMON_NAME, DM20_BOTAMON_ID, "dm:botamon", "dm:Botamon", DM20_BOTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Botamon
        { DM20_BREAKDRAMON_NAME, DM20_BREAKDRAMON_ID, DM20_BREAKDRAMON_FQID, DM20_BREAKDRAMON_FQNAME, DM20_BREAKDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_BREAKDRAMON_NAME, DM20_BREAKDRAMON_ID, "dm:breakdramon", "dm:Breakdramon", DM20_BREAKDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Breakdramon
        { DM20_CENTALMON_NAME, DM20_CENTALMON_ID, DM20_CENTALMON_FQID, DM20_CENTALMON_FQNAME, DM20_CENTALMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_CENTALMON_NAME, DM20_CENTALMON_ID, "dm:centalmon", "dm:Centalmon", DM20_CENTALMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Centalmon
        { DM20_COCKATRIMON_NAME, DM20_COCKATRIMON_ID, DM20_COCKATRIMON_FQID, DM20_COCKATRIMON_FQNAME, DM20_COCKATRIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_COCKATRIMON_NAME, DM20_COCKATRIMON_ID, "dm:cockatrimon", "dm:Cockatrimon", DM20_COCKATRIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Cockatrimon
        { DM20_COELAMON_NAME, DM20_COELAMON_ID, DM20_COELAMON_FQID, DM20_COELAMON_FQNAME, DM20_COELAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_COELAMON_NAME, DM20_COELAMON_ID, "dm:coelamon", "dm:Coelamon", DM20_COELAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Coelamon
        { DM20_COREDRAMON_BLUE_NAME, DM20_COREDRAMON_BLUE_ID, DM20_COREDRAMON_BLUE_FQID, DM20_COREDRAMON_BLUE_FQNAME, DM20_COREDRAMON_BLUE_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_COREDRAMON_BLUE_NAME, DM20_COREDRAMON_BLUE_ID, "dm:coredramon_blue", "dm:Coredramon (Blue)", DM20_COREDRAMON_BLUE_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Coredramon (Blue)
        { DM20_COREDRAMON_GREEN_NAME, DM20_COREDRAMON_GREEN_ID, DM20_COREDRAMON_GREEN_FQID, DM20_COREDRAMON_GREEN_FQNAME, DM20_COREDRAMON_GREEN_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_COREDRAMON_GREEN_NAME, DM20_COREDRAMON_GREEN_ID, "dm:coredramon_green", "dm:Coredramon (Green)", DM20_COREDRAMON_GREEN_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Coredramon (Green)
        { DM20_CORONAMON_NAME, DM20_CORONAMON_ID, DM20_CORONAMON_FQID, DM20_CORONAMON_FQNAME, DM20_CORONAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_CORONAMON_NAME, DM20_CORONAMON_ID, "dm:coronamon", "dm:Coronamon", DM20_CORONAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Coronamon
        { DM20_CRESCEMON_NAME, DM20_CRESCEMON_ID, DM20_CRESCEMON_FQID, DM20_CRESCEMON_FQNAME, DM20_CRESCEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_CRESCEMON_NAME, DM20_CRESCEMON_ID, "dm:crescemon", "dm:Crescemon", DM20_CRESCEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Crescemon
        { DM20_CRES_GARURUMON_NAME, DM20_CRES_GARURUMON_ID, DM20_CRES_GARURUMON_FQID, DM20_CRES_GARURUMON_FQNAME, DM20_CRES_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_CRES_GARURUMON_NAME, DM20_CRES_GARURUMON_ID, "dm:cres_garurumon", "dm:Cres Garurumon", DM20_CRES_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Cres Garurumon
        { DM20_CYCLOMON_NAME, DM20_CYCLOMON_ID, DM20_CYCLOMON_FQID, DM20_CYCLOMON_FQNAME, DM20_CYCLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_CYCLOMON_NAME, DM20_CYCLOMON_ID, "dm:cyclomon", "dm:Cyclomon", DM20_CYCLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Cyclomon
        { DM20_DARK_TYRANOMON_NAME, DM20_DARK_TYRANOMON_ID, DM20_DARK_TYRANOMON_FQID, DM20_DARK_TYRANOMON_FQNAME, DM20_DARK_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DARK_TYRANOMON_NAME, DM20_DARK_TYRANOMON_ID, "dm:dark_tyranomon", "dm:Dark Tyranomon", DM20_DARK_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Dark Tyranomon
        { DM20_DELTAMON_NAME, DM20_DELTAMON_ID, DM20_DELTAMON_FQID, DM20_DELTAMON_FQNAME, DM20_DELTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DELTAMON_NAME, DM20_DELTAMON_ID, "dm:deltamon", "dm:Deltamon", DM20_DELTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Deltamon
        { DM20_DEVIDRAMON_NAME, DM20_DEVIDRAMON_ID, DM20_DEVIDRAMON_FQID, DM20_DEVIDRAMON_FQNAME, DM20_DEVIDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DEVIDRAMON_NAME, DM20_DEVIDRAMON_ID, "dm:devidramon", "dm:Devidramon", DM20_DEVIDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Devidramon
        { DM20_DEVIMON_NAME, DM20_DEVIMON_ID, DM20_DEVIMON_FQID, DM20_DEVIMON_FQNAME, DM20_DEVIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DEVIMON_NAME, DM20_DEVIMON_ID, "dm:devimon", "dm:Devimon", DM20_DEVIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Devimon
        { DM20_DIANAMON_NAME, DM20_DIANAMON_ID, DM20_DIANAMON_FQID, DM20_DIANAMON_FQNAME, DM20_DIANAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DIANAMON_NAME, DM20_DIANAMON_ID, "dm:dianamon", "dm:Dianamon", DM20_DIANAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Dianamon
        { DM20_DIGITAMAMON_NAME, DM20_DIGITAMAMON_ID, DM20_DIGITAMAMON_FQID, DM20_DIGITAMAMON_FQNAME, DM20_DIGITAMAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DIGITAMAMON_NAME, DM20_DIGITAMAMON_ID, "dm:digitamamon", "dm:Digitamamon", DM20_DIGITAMAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Digitamamon
        { DM20_DODOMON_NAME, DM20_DODOMON_ID, DM20_DODOMON_FQID, DM20_DODOMON_FQNAME, DM20_DODOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DODOMON_NAME, DM20_DODOMON_ID, "dm:dodomon", "dm:Dodomon", DM20_DODOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Dodomon
        { DM20_DORIMON_NAME, DM20_DORIMON_ID, DM20_DORIMON_FQID, DM20_DORIMON_FQNAME, DM20_DORIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DORIMON_NAME, DM20_DORIMON_ID, "dm:dorimon", "dm:Dorimon", DM20_DORIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Dorimon
        { DM20_DORUGAMON_NAME, DM20_DORUGAMON_ID, DM20_DORUGAMON_FQID, DM20_DORUGAMON_FQNAME, DM20_DORUGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DORUGAMON_NAME, DM20_DORUGAMON_ID, "dm:dorugamon", "dm:DORUgamon", DM20_DORUGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for DORUgamon
        { DM20_DORUGUREMON_NAME, DM20_DORUGUREMON_ID, DM20_DORUGUREMON_FQID, DM20_DORUGUREMON_FQNAME, DM20_DORUGUREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DORUGUREMON_NAME, DM20_DORUGUREMON_ID, "dm:doruguremon", "dm:DORUguremon", DM20_DORUGUREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for DORUguremon
        { DM20_DORUMON_NAME, DM20_DORUMON_ID, DM20_DORUMON_FQID, DM20_DORUMON_FQNAME, DM20_DORUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DORUMON_NAME, DM20_DORUMON_ID, "dm:dorumon", "dm:DORUmon", DM20_DORUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for DORUmon
        { DM20_DRACOMON_NAME, DM20_DRACOMON_ID, DM20_DRACOMON_FQID, DM20_DRACOMON_FQNAME, DM20_DRACOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DRACOMON_NAME, DM20_DRACOMON_ID, "dm:dracomon", "dm:Dracomon", DM20_DRACOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Dracomon
        { DM20_DRIMOGEMON_NAME, DM20_DRIMOGEMON_ID, DM20_DRIMOGEMON_FQID, DM20_DRIMOGEMON_FQNAME, DM20_DRIMOGEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DRIMOGEMON_NAME, DM20_DRIMOGEMON_ID, "dm:drimogemon", "dm:Drimogemon", DM20_DRIMOGEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Drimogemon
        { DM20_DURAMON_NAME, DM20_DURAMON_ID, DM20_DURAMON_FQID, DM20_DURAMON_FQNAME, DM20_DURAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DURAMON_NAME, DM20_DURAMON_ID, "dm:duramon", "dm:Duramon", DM20_DURAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Duramon
        { DM20_DURANDAMON_NAME, DM20_DURANDAMON_ID, DM20_DURANDAMON_FQID, DM20_DURANDAMON_FQNAME, DM20_DURANDAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DURANDAMON_NAME, DM20_DURANDAMON_ID, "dm:durandamon", "dm:Durandamon", DM20_DURANDAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Durandamon
        { DM20_DURANDRAMON_NAME, DM20_DURANDRAMON_ID, DM20_DURANDRAMON_FQID, DM20_DURANDRAMON_FQNAME, DM20_DURANDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_DURANDRAMON_NAME, DM20_DURANDRAMON_ID, "dm:durandramon", "dm:Durandramon", DM20_DURANDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Durandramon
        { DM20_ELECMON_NAME, DM20_ELECMON_ID, DM20_ELECMON_FQID, DM20_ELECMON_FQNAME, DM20_ELECMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ELECMON_NAME, DM20_ELECMON_ID, "dm:elecmon", "dm:Elecmon", DM20_ELECMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Elecmon
        { DM20_ETEMON_NAME, DM20_ETEMON_ID, DM20_ETEMON_FQID, DM20_ETEMON_FQNAME, DM20_ETEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ETEMON_NAME, DM20_ETEMON_ID, "dm:etemon", "dm:Etemon", DM20_ETEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Etemon
        { DM20_EXAMON_NAME, DM20_EXAMON_ID, DM20_EXAMON_FQID, DM20_EXAMON_FQNAME, DM20_EXAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_EXAMON_NAME, DM20_EXAMON_ID, "dm:examon", "dm:Examon", DM20_EXAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Examon
        { DM20_EX_TYRANOMON_NAME, DM20_EX_TYRANOMON_ID, DM20_EX_TYRANOMON_FQID, DM20_EX_TYRANOMON_FQNAME, DM20_EX_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_EX_TYRANOMON_NAME, DM20_EX_TYRANOMON_ID, "dm:ex_tyranomon", "dm:Ex-Tyranomon", DM20_EX_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Ex-Tyranomon
        { DM20_FIRAMON_NAME, DM20_FIRAMON_ID, DM20_FIRAMON_FQID, DM20_FIRAMON_FQNAME, DM20_FIRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_FIRAMON_NAME, DM20_FIRAMON_ID, "dm:firamon", "dm:Firamon", DM20_FIRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Firamon
        { DM20_FLAREMON_NAME, DM20_FLAREMON_ID, DM20_FLAREMON_FQID, DM20_FLAREMON_FQNAME, DM20_FLAREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_FLAREMON_NAME, DM20_FLAREMON_ID, "dm:flaremon", "dm:Flaremon", DM20_FLAREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Flaremon
        { DM20_FLYMON_NAME, DM20_FLYMON_ID, DM20_FLYMON_FQID, DM20_FLYMON_FQNAME, DM20_FLYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_FLYMON_NAME, DM20_FLYMON_ID, "dm:flymon", "dm:Flymon", DM20_FLYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Flymon
        { DM20_GABUMON_NAME, DM20_GABUMON_ID, DM20_GABUMON_FQID, DM20_GABUMON_FQNAME, DM20_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GABUMON_NAME, DM20_GABUMON_ID, "dm:gabumon", "dm:Gabumon", DM20_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Gabumon
        { DM20_GARURUMON_NAME, DM20_GARURUMON_ID, DM20_GARURUMON_FQID, DM20_GARURUMON_FQNAME, DM20_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GARURUMON_NAME, DM20_GARURUMON_ID, "dm:garurumon", "dm:Garurumon", DM20_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Garurumon
        { DM20_GAZIMON_NAME, DM20_GAZIMON_ID, DM20_GAZIMON_FQID, DM20_GAZIMON_FQNAME, DM20_GAZIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GAZIMON_NAME, DM20_GAZIMON_ID, "dm:gazimon", "dm:Gazimon", DM20_GAZIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Gazimon
        { DM20_GIROMON_NAME, DM20_GIROMON_ID, DM20_GIROMON_FQID, DM20_GIROMON_FQNAME, DM20_GIROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GIROMON_NAME, DM20_GIROMON_ID, "dm:giromon", "dm:Giromon", DM20_GIROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Giromon
        { DM20_GIZAMON_NAME, DM20_GIZAMON_ID, DM20_GIZAMON_FQID, DM20_GIZAMON_FQNAME, DM20_GIZAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GIZAMON_NAME, DM20_GIZAMON_ID, "dm:gizamon", "dm:Gizamon", DM20_GIZAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Gizamon
        { DM20_GRACE_NOVAMON_NAME, DM20_GRACE_NOVAMON_ID, DM20_GRACE_NOVAMON_FQID, DM20_GRACE_NOVAMON_FQNAME, DM20_GRACE_NOVAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GRACE_NOVAMON_NAME, DM20_GRACE_NOVAMON_ID, "dm:grace_novamon", "dm:Grace Novamon", DM20_GRACE_NOVAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Grace Novamon
        { DM20_GREYMON_NAME, DM20_GREYMON_ID, DM20_GREYMON_FQID, DM20_GREYMON_FQNAME, DM20_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GREYMON_NAME, DM20_GREYMON_ID, "dm:greymon", "dm:Greymon", DM20_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Greymon
        { DM20_GROUNDRAMON_NAME, DM20_GROUNDRAMON_ID, DM20_GROUNDRAMON_FQID, DM20_GROUNDRAMON_FQNAME, DM20_GROUNDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_GROUNDRAMON_NAME, DM20_GROUNDRAMON_ID, "dm:groundramon", "dm:Groundramon", DM20_GROUNDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Groundramon
        { DM20_HACKMON_NAME, DM20_HACKMON_ID, DM20_HACKMON_FQID, DM20_HACKMON_FQNAME, DM20_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_HACKMON_NAME, DM20_HACKMON_ID, "dm:hackmon", "dm:Hackmon", DM20_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Hackmon
        { DM20_HI_ANDROMON_NAME, DM20_HI_ANDROMON_ID, DM20_HI_ANDROMON_FQID, DM20_HI_ANDROMON_FQNAME, DM20_HI_ANDROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_HI_ANDROMON_NAME, DM20_HI_ANDROMON_ID, "dm:hi_andromon", "dm:Hi Andromon", DM20_HI_ANDROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Hi Andromon
        { DM20_JESMON_NAME, DM20_JESMON_ID, DM20_JESMON_FQID, DM20_JESMON_FQNAME, DM20_JESMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_JESMON_NAME, DM20_JESMON_ID, "dm:jesmon", "dm:Jesmon", DM20_JESMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Jesmon
        { DM20_JIJIMON_NAME, DM20_JIJIMON_ID, DM20_JIJIMON_FQID, DM20_JIJIMON_FQNAME, DM20_JIJIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_JIJIMON_NAME, DM20_JIJIMON_ID, "dm:jijimon", "dm:Jijimon", DM20_JIJIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Jijimon
        { DM20_KABUTERIMON_NAME, DM20_KABUTERIMON_ID, DM20_KABUTERIMON_FQID, DM20_KABUTERIMON_FQNAME, DM20_KABUTERIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_KABUTERIMON_NAME, DM20_KABUTERIMON_ID, "dm:kabuterimon", "dm:Kabuterimon", DM20_KABUTERIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Kabuterimon
        { DM20_KING_ETEMON_NAME, DM20_KING_ETEMON_ID, DM20_KING_ETEMON_FQID, DM20_KING_ETEMON_FQNAME, DM20_KING_ETEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_KING_ETEMON_NAME, DM20_KING_ETEMON_ID, "dm:king_etemon", "dm:King Etemon", DM20_KING_ETEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for King Etemon
        { DM20_KOROMON_NAME, DM20_KOROMON_ID, DM20_KOROMON_FQID, DM20_KOROMON_FQNAME, DM20_KOROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_KOROMON_NAME, DM20_KOROMON_ID, "dm:koromon", "dm:Koromon", DM20_KOROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Koromon
        { DM20_KUNEMON_NAME, DM20_KUNEMON_ID, DM20_KUNEMON_FQID, DM20_KUNEMON_FQNAME, DM20_KUNEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_KUNEMON_NAME, DM20_KUNEMON_ID, "dm:kunemon", "dm:Kunemon", DM20_KUNEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Kunemon
        { DM20_KUWAGAMON_NAME, DM20_KUWAGAMON_ID, DM20_KUWAGAMON_FQID, DM20_KUWAGAMON_FQNAME, DM20_KUWAGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_KUWAGAMON_NAME, DM20_KUWAGAMON_ID, "dm:kuwagamon", "dm:Kuwagamon", DM20_KUWAGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Kuwagamon
        { DM20_LEKISMON_NAME, DM20_LEKISMON_ID, DM20_LEKISMON_FQID, DM20_LEKISMON_FQNAME, DM20_LEKISMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_LEKISMON_NAME, DM20_LEKISMON_ID, "dm:lekismon", "dm:Lekismon", DM20_LEKISMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Lekismon
        { DM20_LEOMON_NAME, DM20_LEOMON_ID, DM20_LEOMON_FQID, DM20_LEOMON_FQNAME, DM20_LEOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_LEOMON_NAME, DM20_LEOMON_ID, "dm:leomon", "dm:Leomon", DM20_LEOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Leomon
        { DM20_LUNAMON_NAME, DM20_LUNAMON_ID, DM20_LUNAMON_FQID, DM20_LUNAMON_FQNAME, DM20_LUNAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_LUNAMON_NAME, DM20_LUNAMON_ID, "dm:lunamon", "dm:Lunamon", DM20_LUNAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Lunamon
        { DM20_MAMEMON_NAME, DM20_MAMEMON_ID, DM20_MAMEMON_FQID, DM20_MAMEMON_FQNAME, DM20_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MAMEMON_NAME, DM20_MAMEMON_ID, "dm:mamemon", "dm:Mamemon", DM20_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Mamemon
        { DM20_MEGADRAMON_NAME, DM20_MEGADRAMON_ID, DM20_MEGADRAMON_FQID, DM20_MEGADRAMON_FQNAME, DM20_MEGADRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MEGADRAMON_NAME, DM20_MEGADRAMON_ID, "dm:megadramon", "dm:Megadramon", DM20_MEGADRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Megadramon
        { DM20_MEICOOMON_NAME, DM20_MEICOOMON_ID, DM20_MEICOOMON_FQID, DM20_MEICOOMON_FQNAME, DM20_MEICOOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MEICOOMON_NAME, DM20_MEICOOMON_ID, "dm:meicoomon", "dm:Meicoomon", DM20_MEICOOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Meicoomon
        { DM20_MEICRACKMON_NAME, DM20_MEICRACKMON_ID, DM20_MEICRACKMON_FQID, DM20_MEICRACKMON_FQNAME, DM20_MEICRACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MEICRACKMON_NAME, DM20_MEICRACKMON_ID, "dm:meicrackmon", "dm:Meicrackmon", DM20_MEICRACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Meicrackmon
        { DM20_MERAMON_NAME, DM20_MERAMON_ID, DM20_MERAMON_FQID, DM20_MERAMON_FQNAME, DM20_MERAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MERAMON_NAME, DM20_MERAMON_ID, "dm:meramon", "dm:Meramon", DM20_MERAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Meramon
        { DM20_METAL_GARURUMON_NAME, DM20_METAL_GARURUMON_ID, DM20_METAL_GARURUMON_FQID, DM20_METAL_GARURUMON_FQNAME, DM20_METAL_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_METAL_GARURUMON_NAME, DM20_METAL_GARURUMON_ID, "dm:metal_garurumon", "dm:Metal Garurumon", DM20_METAL_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Metal Garurumon
        { DM20_METAL_GREYMON_NAME, DM20_METAL_GREYMON_ID, DM20_METAL_GREYMON_FQID, DM20_METAL_GREYMON_FQNAME, DM20_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_METAL_GREYMON_NAME, DM20_METAL_GREYMON_ID, "dm:metal_greymon", "dm:Metal Greymon", DM20_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Metal Greymon
        { DM20_METAL_MAMEMON_NAME, DM20_METAL_MAMEMON_ID, DM20_METAL_MAMEMON_FQID, DM20_METAL_MAMEMON_FQNAME, DM20_METAL_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_METAL_MAMEMON_NAME, DM20_METAL_MAMEMON_ID, "dm:metal_mamemon", "dm:Metal Mamemon", DM20_METAL_MAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Metal Mamemon
        { DM20_METAL_TYRANOMON_NAME, DM20_METAL_TYRANOMON_ID, DM20_METAL_TYRANOMON_FQID, DM20_METAL_TYRANOMON_FQNAME, DM20_METAL_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_METAL_TYRANOMON_NAME, DM20_METAL_TYRANOMON_ID, "dm:metal_tyranomon", "dm:Metal Tyranomon", DM20_METAL_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Metal Tyranomon
        { DM20_MOJYAMON_NAME, DM20_MOJYAMON_ID, DM20_MOJYAMON_FQID, DM20_MOJYAMON_FQNAME, DM20_MOJYAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MOJYAMON_NAME, DM20_MOJYAMON_ID, "dm:mojyamon", "dm:Mojyamon", DM20_MOJYAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Mojyamon
        { DM20_MONCHROMON_NAME, DM20_MONCHROMON_ID, DM20_MONCHROMON_FQID, DM20_MONCHROMON_FQNAME, DM20_MONCHROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MONCHROMON_NAME, DM20_MONCHROMON_ID, "dm:monchromon", "dm:Monchromon", DM20_MONCHROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Monchromon
        { DM20_MONOCHROMON_NAME, DM20_MONOCHROMON_ID, DM20_MONOCHROMON_FQID, DM20_MONOCHROMON_FQNAME, DM20_MONOCHROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MONOCHROMON_NAME, DM20_MONOCHROMON_ID, "dm:monochromon", "dm:Monochromon", DM20_MONOCHROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Monochromon
        { DM20_MONZAEMON_NAME, DM20_MONZAEMON_ID, DM20_MONZAEMON_FQID, DM20_MONZAEMON_FQNAME, DM20_MONZAEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MONZAEMON_NAME, DM20_MONZAEMON_ID, "dm:monzaemon", "dm:Monzaemon", DM20_MONZAEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Monzaemon
        { DM20_MOZAEMON_NAME, DM20_MOZAEMON_ID, DM20_MOZAEMON_FQID, DM20_MOZAEMON_FQNAME, DM20_MOZAEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MOZAEMON_NAME, DM20_MOZAEMON_ID, "dm:mozaemon", "dm:Mozaemon", DM20_MOZAEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Mozaemon
        { DM20_MUGENDRAMON_NAME, DM20_MUGENDRAMON_ID, DM20_MUGENDRAMON_FQID, DM20_MUGENDRAMON_FQNAME, DM20_MUGENDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_MUGENDRAMON_NAME, DM20_MUGENDRAMON_ID, "dm:mugendramon", "dm:Mugendramon", DM20_MUGENDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Mugendramon
        { DM20_NANIMON_NAME, DM20_NANIMON_ID, DM20_NANIMON_FQID, DM20_NANIMON_FQNAME, DM20_NANIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_NANIMON_NAME, DM20_NANIMON_ID, "dm:nanimon", "dm:Nanimon", DM20_NANIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Nanimon
        { DM20_NANOMON_NAME, DM20_NANOMON_ID, DM20_NANOMON_FQID, DM20_NANOMON_FQNAME, DM20_NANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_NANOMON_NAME, DM20_NANOMON_ID, "dm:nanomon", "dm:Nanomon", DM20_NANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Nanomon
        { DM20_NUMEMON_NAME, DM20_NUMEMON_ID, DM20_NUMEMON_FQID, DM20_NUMEMON_FQNAME, DM20_NUMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_NUMEMON_NAME, DM20_NUMEMON_ID, "dm:numemon", "dm:Numemon", DM20_NUMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Numemon
        { DM20_NYAROMON_NAME, DM20_NYAROMON_ID, DM20_NYAROMON_FQID, DM20_NYAROMON_FQNAME, DM20_NYAROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_NYAROMON_NAME, DM20_NYAROMON_ID, "dm:nyaromon", "dm:Nyaromon", DM20_NYAROMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Nyaromon
        { DM20_OGREMON_NAME, DM20_OGREMON_ID, DM20_OGREMON_FQID, DM20_OGREMON_FQNAME, DM20_OGREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_OGREMON_NAME, DM20_OGREMON_ID, "dm:ogremon", "dm:Ogremon", DM20_OGREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Ogremon
        { DM20_OMEGAMON_ALTER_S_NAME, DM20_OMEGAMON_ALTER_S_ID, DM20_OMEGAMON_ALTER_S_FQID, DM20_OMEGAMON_ALTER_S_FQNAME, DM20_OMEGAMON_ALTER_S_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_OMEGAMON_ALTER_S_NAME, DM20_OMEGAMON_ALTER_S_ID, "dm:omegamon_alter_s", "dm:Omegamon Alter S", DM20_OMEGAMON_ALTER_S_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Omegamon Alter S
        { DM20_OMEGAMON_NAME, DM20_OMEGAMON_ID, DM20_OMEGAMON_FQID, DM20_OMEGAMON_FQNAME, DM20_OMEGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_OMEGAMON_NAME, DM20_OMEGAMON_ID, "dm:omegamon", "dm:Omegamon", DM20_OMEGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Omegamon
        { DM20_PAGUMON_NAME, DM20_PAGUMON_ID, DM20_PAGUMON_FQID, DM20_PAGUMON_FQNAME, DM20_PAGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PAGUMON_NAME, DM20_PAGUMON_ID, "dm:pagumon", "dm:Pagumon", DM20_PAGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Pagumon
        { DM20_PAKUMON_NAME, DM20_PAKUMON_ID, DM20_PAKUMON_FQID, DM20_PAKUMON_FQNAME, DM20_PAKUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PAKUMON_NAME, DM20_PAKUMON_ID, "dm:pakumon", "dm:Pakumon", DM20_PAKUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Pakumon
        { DM20_PALMON_NAME, DM20_PALMON_ID, DM20_PALMON_FQID, DM20_PALMON_FQNAME, DM20_PALMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PALMON_NAME, DM20_PALMON_ID, "dm:palmon", "dm:Palmon", DM20_PALMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Palmon
        { DM20_PATAMON_NAME, DM20_PATAMON_ID, DM20_PATAMON_FQID, DM20_PATAMON_FQNAME, DM20_PATAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PATAMON_NAME, DM20_PATAMON_ID, "dm:patamon", "dm:Patamon", DM20_PATAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Patamon
        { DM20_PETITMON_NAME, DM20_PETITMON_ID, DM20_PETITMON_FQID, DM20_PETITMON_FQNAME, DM20_PETITMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PETITMON_NAME, DM20_PETITMON_ID, "dm:petitmon", "dm:Petitmon", DM20_PETITMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Petitmon
        { DM20_PICCOLOMON_NAME, DM20_PICCOLOMON_ID, DM20_PICCOLOMON_FQID, DM20_PICCOLOMON_FQNAME, DM20_PICCOLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PICCOLOMON_NAME, DM20_PICCOLOMON_ID, "dm:piccolomon", "dm:Piccolomon", DM20_PICCOLOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Piccolomon
        { DM20_PINOCHIMON_NAME, DM20_PINOCHIMON_ID, DM20_PINOCHIMON_FQID, DM20_PINOCHIMON_FQNAME, DM20_PINOCHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PINOCHIMON_NAME, DM20_PINOCHIMON_ID, "dm:pinochimon", "dm:Pinochimon", DM20_PINOCHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Pinochimon
        { DM20_PITCHMON_NAME, DM20_PITCHMON_ID, DM20_PITCHMON_FQID, DM20_PITCHMON_FQNAME, DM20_PITCHMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PITCHMON_NAME, DM20_PITCHMON_ID, "dm:pitchmon", "dm:Pitchmon", DM20_PITCHMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Pitchmon
        { DM20_PIYOMON_NAME, DM20_PIYOMON_ID, DM20_PIYOMON_FQID, DM20_PIYOMON_FQNAME, DM20_PIYOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PIYOMON_NAME, DM20_PIYOMON_ID, "dm:piyomon", "dm:Piyomon", DM20_PIYOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Piyomon
        { DM20_PLOTMON_NAME, DM20_PLOTMON_ID, DM20_PLOTMON_FQID, DM20_PLOTMON_FQNAME, DM20_PLOTMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PLOTMON_NAME, DM20_PLOTMON_ID, "dm:plotmon", "dm:Plotmon", DM20_PLOTMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Plotmon
        { DM20_POYOMON_NAME, DM20_POYOMON_ID, DM20_POYOMON_FQID, DM20_POYOMON_FQNAME, DM20_POYOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_POYOMON_NAME, DM20_POYOMON_ID, "dm:poyomon", "dm:Poyomon", DM20_POYOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Poyomon
        { DM20_PUKAMON_NAME, DM20_PUKAMON_ID, DM20_PUKAMON_FQID, DM20_PUKAMON_FQNAME, DM20_PUKAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PUKAMON_NAME, DM20_PUKAMON_ID, "dm:pukamon", "dm:Pukamon", DM20_PUKAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Pukamon
        { DM20_PUNIMON_NAME, DM20_PUNIMON_ID, DM20_PUNIMON_FQID, DM20_PUNIMON_FQNAME, DM20_PUNIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_PUNIMON_NAME, DM20_PUNIMON_ID, "dm:punimon", "dm:Punimon", DM20_PUNIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Punimon
        { DM20_RAREMON_NAME, DM20_RAREMON_ID, DM20_RAREMON_FQID, DM20_RAREMON_FQNAME, DM20_RAREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_RAREMON_NAME, DM20_RAREMON_ID, "dm:raremon", "dm:Raremon", DM20_RAREMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Raremon
        { DM20_RASIELMON_NAME, DM20_RASIELMON_ID, DM20_RASIELMON_FQID, DM20_RASIELMON_FQNAME, DM20_RASIELMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_RASIELMON_NAME, DM20_RASIELMON_ID, "dm:rasielmon", "dm:Rasielmon", DM20_RASIELMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Rasielmon
        { DM20_RUST_TYRANOMON_NAME, DM20_RUST_TYRANOMON_ID, DM20_RUST_TYRANOMON_FQID, DM20_RUST_TYRANOMON_FQNAME, DM20_RUST_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_RUST_TYRANOMON_NAME, DM20_RUST_TYRANOMON_ID, "dm:rust_tyranomon", "dm:Rust Tyranomon", DM20_RUST_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Rust Tyranomon
        { DM20_SAKUMON_NAME, DM20_SAKUMON_ID, DM20_SAKUMON_FQID, DM20_SAKUMON_FQNAME, DM20_SAKUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SAKUMON_NAME, DM20_SAKUMON_ID, "dm:sakumon", "dm:Sakumon", DM20_SAKUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Sakumon
        { DM20_SAKUTTOMON_NAME, DM20_SAKUTTOMON_ID, DM20_SAKUTTOMON_FQID, DM20_SAKUTTOMON_FQNAME, DM20_SAKUTTOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SAKUTTOMON_NAME, DM20_SAKUTTOMON_ID, "dm:sakuttomon", "dm:Sakuttomon", DM20_SAKUTTOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Sakuttomon
        { DM20_SAVIOR_HACKMON_NAME, DM20_SAVIOR_HACKMON_ID, DM20_SAVIOR_HACKMON_FQID, DM20_SAVIOR_HACKMON_FQNAME, DM20_SAVIOR_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SAVIOR_HACKMON_NAME, DM20_SAVIOR_HACKMON_ID, "dm:savior_hackmon", "dm:Savior Hackmon", DM20_SAVIOR_HACKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Savior Hackmon
        { DM20_SCUMON_NAME, DM20_SCUMON_ID, DM20_SCUMON_FQID, DM20_SCUMON_FQNAME, DM20_SCUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SCUMON_NAME, DM20_SCUMON_ID, "dm:scumon", "dm:Scumon", DM20_SCUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Scumon
        { DM20_SEADRAMON_NAME, DM20_SEADRAMON_ID, DM20_SEADRAMON_FQID, DM20_SEADRAMON_FQNAME, DM20_SEADRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SEADRAMON_NAME, DM20_SEADRAMON_ID, "dm:seadramon", "dm:Seadramon", DM20_SEADRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Seadramon
        { DM20_SHELLMON_NAME, DM20_SHELLMON_ID, DM20_SHELLMON_FQID, DM20_SHELLMON_FQNAME, DM20_SHELLMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SHELLMON_NAME, DM20_SHELLMON_ID, "dm:shellmon", "dm:Shellmon", DM20_SHELLMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Shellmon
        { DM20_SKULL_GREYMON_NAME, DM20_SKULL_GREYMON_ID, DM20_SKULL_GREYMON_FQID, DM20_SKULL_GREYMON_FQNAME, DM20_SKULL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SKULL_GREYMON_NAME, DM20_SKULL_GREYMON_ID, "dm:skull_greymon", "dm:Skull Greymon", DM20_SKULL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Skull Greymon
        { DM20_SKULL_MAMMON_NAME, DM20_SKULL_MAMMON_ID, DM20_SKULL_MAMMON_FQID, DM20_SKULL_MAMMON_FQNAME, DM20_SKULL_MAMMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SKULL_MAMMON_NAME, DM20_SKULL_MAMMON_ID, "dm:skull_mammon", "dm:Skull Mammon", DM20_SKULL_MAMMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Skull Mammon
        { DM20_SLAYERDRAMON_NAME, DM20_SLAYERDRAMON_ID, DM20_SLAYERDRAMON_FQID, DM20_SLAYERDRAMON_FQNAME, DM20_SLAYERDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_SLAYERDRAMON_NAME, DM20_SLAYERDRAMON_ID, "dm:slayerdramon", "dm:Slayerdramon", DM20_SLAYERDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Slayerdramon
        { DM20_TAICHI_METAL_GREYMON_NAME, DM20_TAICHI_METAL_GREYMON_ID, DM20_TAICHI_METAL_GREYMON_FQID, DM20_TAICHI_METAL_GREYMON_FQNAME, DM20_TAICHI_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TAICHI_METAL_GREYMON_NAME, DM20_TAICHI_METAL_GREYMON_ID, "dm:taichi_metal_greymon", "dm:Taichi Metal Greymon", DM20_TAICHI_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Taichi Metal Greymon
        { DM20_TAICHIS_AGUMON_NAME, DM20_TAICHIS_AGUMON_ID, DM20_TAICHIS_AGUMON_FQID, DM20_TAICHIS_AGUMON_FQNAME, DM20_TAICHIS_AGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TAICHIS_AGUMON_NAME, DM20_TAICHIS_AGUMON_ID, "dm:taichis_agumon", "dm:Taichis Agumon", DM20_TAICHIS_AGUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Taichis Agumon
        { DM20_TAICHIS_GREYMON_NAME, DM20_TAICHIS_GREYMON_ID, DM20_TAICHIS_GREYMON_FQID, DM20_TAICHIS_GREYMON_FQNAME, DM20_TAICHIS_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TAICHIS_GREYMON_NAME, DM20_TAICHIS_GREYMON_ID, "dm:taichis_greymon", "dm:Taichis Greymon", DM20_TAICHIS_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Taichis Greymon
        { DM20_TAICHIS_METAL_GREYMON_NAME, DM20_TAICHIS_METAL_GREYMON_ID, DM20_TAICHIS_METAL_GREYMON_FQID, DM20_TAICHIS_METAL_GREYMON_FQNAME, DM20_TAICHIS_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TAICHIS_METAL_GREYMON_NAME, DM20_TAICHIS_METAL_GREYMON_ID, "dm:taichis_metal_greymon", "dm:Taichis Metal Greymon", DM20_TAICHIS_METAL_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Taichis Metal Greymon
        { DM20_TAICHIS_WAR_GREYMON_NAME, DM20_TAICHIS_WAR_GREYMON_ID, DM20_TAICHIS_WAR_GREYMON_FQID, DM20_TAICHIS_WAR_GREYMON_FQNAME, DM20_TAICHIS_WAR_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TAICHIS_WAR_GREYMON_NAME, DM20_TAICHIS_WAR_GREYMON_ID, "dm:taichis_war_greymon", "dm:Taichis War Greymon", DM20_TAICHIS_WAR_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Taichis War Greymon
        { DM20_TANEMON_NAME, DM20_TANEMON_ID, DM20_TANEMON_FQID, DM20_TANEMON_FQNAME, DM20_TANEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TANEMON_NAME, DM20_TANEMON_ID, "dm:tanemon", "dm:Tanemon", DM20_TANEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tanemon
        { DM20_TITAMON_NAME, DM20_TITAMON_ID, DM20_TITAMON_FQID, DM20_TITAMON_FQNAME, DM20_TITAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TITAMON_NAME, DM20_TITAMON_ID, "dm:titamon", "dm:Titamon", DM20_TITAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Titamon
        { DM20_TOKOMON_NAME, DM20_TOKOMON_ID, DM20_TOKOMON_FQID, DM20_TOKOMON_FQNAME, DM20_TOKOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TOKOMON_NAME, DM20_TOKOMON_ID, "dm:tokomon", "dm:Tokomon", DM20_TOKOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tokomon
        { DM20_TSUNOMON_NAME, DM20_TSUNOMON_ID, DM20_TSUNOMON_FQID, DM20_TSUNOMON_FQNAME, DM20_TSUNOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TSUNOMON_NAME, DM20_TSUNOMON_ID, "dm:tsunomon", "dm:Tsunomon", DM20_TSUNOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tsunomon
        { DM20_TUNOMON_NAME, DM20_TUNOMON_ID, DM20_TUNOMON_FQID, DM20_TUNOMON_FQNAME, DM20_TUNOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TUNOMON_NAME, DM20_TUNOMON_ID, "dm:tunomon", "dm:Tunomon", DM20_TUNOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tunomon
        { DM20_TUSKMON_NAME, DM20_TUSKMON_ID, DM20_TUSKMON_FQID, DM20_TUSKMON_FQNAME, DM20_TUSKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TUSKMON_NAME, DM20_TUSKMON_ID, "dm:tuskmon", "dm:Tuskmon", DM20_TUSKMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tuskmon
        { DM20_TYRANOMON_NAME, DM20_TYRANOMON_ID, DM20_TYRANOMON_FQID, DM20_TYRANOMON_FQNAME, DM20_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_TYRANOMON_NAME, DM20_TYRANOMON_ID, "dm:tyranomon", "dm:Tyranomon", DM20_TYRANOMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Tyranomon
        { DM20_UNIMON_NAME, DM20_UNIMON_ID, DM20_UNIMON_FQID, DM20_UNIMON_FQNAME, DM20_UNIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_UNIMON_NAME, DM20_UNIMON_ID, "dm:unimon", "dm:Unimon", DM20_UNIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Unimon
        { DM20_VADEMON_NAME, DM20_VADEMON_ID, DM20_VADEMON_FQID, DM20_VADEMON_FQNAME, DM20_VADEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_VADEMON_NAME, DM20_VADEMON_ID, "dm:vademon", "dm:Vademon", DM20_VADEMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Vademon
        { DM20_VEGIMON_NAME, DM20_VEGIMON_ID, DM20_VEGIMON_FQID, DM20_VEGIMON_FQNAME, DM20_VEGIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_VEGIMON_NAME, DM20_VEGIMON_ID, "dm:vegimon", "dm:Vegimon", DM20_VEGIMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Vegimon
        { DM20_WAR_GREYMON_NAME, DM20_WAR_GREYMON_ID, DM20_WAR_GREYMON_FQID, DM20_WAR_GREYMON_FQNAME, DM20_WAR_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_WAR_GREYMON_NAME, DM20_WAR_GREYMON_ID, "dm:war_greymon", "dm:War Greymon", DM20_WAR_GREYMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for War Greymon
        { DM20_WERE_GARURUMON_NAME, DM20_WERE_GARURUMON_ID, DM20_WERE_GARURUMON_FQID, DM20_WERE_GARURUMON_FQNAME, DM20_WERE_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_WERE_GARURUMON_NAME, DM20_WERE_GARURUMON_ID, "dm:were_garurumon", "dm:Were Garurumon", DM20_WERE_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Were Garurumon
        { DM20_WHAMON_NAME, DM20_WHAMON_ID, DM20_WHAMON_FQID, DM20_WHAMON_FQNAME, DM20_WHAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_WHAMON_NAME, DM20_WHAMON_ID, "dm:whamon", "dm:Whamon", DM20_WHAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Whamon
        { DM20_WINGDRAMON_NAME, DM20_WINGDRAMON_ID, DM20_WINGDRAMON_FQID, DM20_WINGDRAMON_FQNAME, DM20_WINGDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_WINGDRAMON_NAME, DM20_WINGDRAMON_ID, "dm:wingdramon", "dm:Wingdramon", DM20_WINGDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Wingdramon
        { DM20_YAMATO_GABUMON_NAME, DM20_YAMATO_GABUMON_ID, DM20_YAMATO_GABUMON_FQID, DM20_YAMATO_GABUMON_FQNAME, DM20_YAMATO_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YAMATO_GABUMON_NAME, DM20_YAMATO_GABUMON_ID, "dm:yamato_gabumon", "dm:Yamato Gabumon", DM20_YAMATO_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yamato Gabumon
        { DM20_YAMATOS_GABUMON_NAME, DM20_YAMATOS_GABUMON_ID, DM20_YAMATOS_GABUMON_FQID, DM20_YAMATOS_GABUMON_FQNAME, DM20_YAMATOS_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YAMATOS_GABUMON_NAME, DM20_YAMATOS_GABUMON_ID, "dm:yamatos_gabumon", "dm:Yamatos Gabumon", DM20_YAMATOS_GABUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yamatos Gabumon
        { DM20_YAMATOS_GARURUMON_NAME, DM20_YAMATOS_GARURUMON_ID, DM20_YAMATOS_GARURUMON_FQID, DM20_YAMATOS_GARURUMON_FQNAME, DM20_YAMATOS_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YAMATOS_GARURUMON_NAME, DM20_YAMATOS_GARURUMON_ID, "dm:yamatos_garurumon", "dm:Yamatos Garurumon", DM20_YAMATOS_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yamatos Garurumon
        { DM20_YAMATOS_METAL_GARURUMON_NAME, DM20_YAMATOS_METAL_GARURUMON_ID, DM20_YAMATOS_METAL_GARURUMON_FQID, DM20_YAMATOS_METAL_GARURUMON_FQNAME, DM20_YAMATOS_METAL_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YAMATOS_METAL_GARURUMON_NAME, DM20_YAMATOS_METAL_GARURUMON_ID, "dm:yamatos_metal_garurumon", "dm:Yamatos Metal Garurumon", DM20_YAMATOS_METAL_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yamatos Metal Garurumon
        { DM20_YAMATOS_WERE_GARURUMON_NAME, DM20_YAMATOS_WERE_GARURUMON_ID, DM20_YAMATOS_WERE_GARURUMON_FQID, DM20_YAMATOS_WERE_GARURUMON_FQNAME, DM20_YAMATOS_WERE_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YAMATOS_WERE_GARURUMON_NAME, DM20_YAMATOS_WERE_GARURUMON_ID, "dm:yamatos_were_garurumon", "dm:Yamatos Were Garurumon", DM20_YAMATOS_WERE_GARURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yamatos Were Garurumon
        { DM20_YUKIDARUMON_NAME, DM20_YUKIDARUMON_ID, DM20_YUKIDARUMON_FQID, DM20_YUKIDARUMON_FQNAME, DM20_YUKIDARUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YUKIDARUMON_NAME, DM20_YUKIDARUMON_ID, "dm:yukidarumon", "dm:Yukidarumon", DM20_YUKIDARUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yukidarumon
        { DM20_YUKIMI_BOTAMON_NAME, DM20_YUKIMI_BOTAMON_ID, DM20_YUKIMI_BOTAMON_FQID, DM20_YUKIMI_BOTAMON_FQNAME, DM20_YUKIMI_BOTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YUKIMI_BOTAMON_NAME, DM20_YUKIMI_BOTAMON_ID, "dm:yukimi_botamon", "dm:Yukimi Botamon", DM20_YUKIMI_BOTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yukimi Botamon
        { DM20_YURAMON_NAME, DM20_YURAMON_ID, DM20_YURAMON_FQID, DM20_YURAMON_FQNAME, DM20_YURAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_YURAMON_NAME, DM20_YURAMON_ID, "dm:yuramon", "dm:Yuramon", DM20_YURAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Yuramon
        { DM20_ZUBAEAGERMON_NAME, DM20_ZUBAEAGERMON_ID, DM20_ZUBAEAGERMON_FQID, DM20_ZUBAEAGERMON_FQNAME, DM20_ZUBAEAGERMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ZUBAEAGERMON_NAME, DM20_ZUBAEAGERMON_ID, "dm:zubaeagermon", "dm:Zubaeagermon", DM20_ZUBAEAGERMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Zubaeagermon
        { DM20_ZUBAMON_NAME, DM20_ZUBAMON_ID, DM20_ZUBAMON_FQID, DM20_ZUBAMON_FQNAME, DM20_ZUBAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ZUBAMON_NAME, DM20_ZUBAMON_ID, "dm:zubamon", "dm:Zubamon", DM20_ZUBAMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Zubamon
        { DM20_ZURUMON_NAME, DM20_ZURUMON_ID, DM20_ZURUMON_FQID, DM20_ZURUMON_FQNAME, DM20_ZURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },
        { DM20_ZURUMON_NAME, DM20_ZURUMON_ID, "dm:zurumon", "dm:Zurumon", DM20_ZURUMON_ANIM_INDEX, config::config_animation_dm_set_t::dm20, config::config_animation_sprite_sheet_layout_t::Dm },  // alt ids for Zurumon
    };

    config_animation_entry_t get_config_animation_name_dm20(size_t index) {
        return dm20_animation_table[index];
    }

    void config_parse_animation_name_dm20(config::config_t& config, const char *value) {
        for (const auto& entry : dm20_animation_table) {
            if (strcmp(value, entry.name) == 0 ||
                strcmp(value, entry.id) == 0 ||
                strcmp(value, entry.fqid) == 0 ||
                strcmp(value, entry.fqname) == 0) {
                config.animation_index = entry.anim_index;
                config.animation_dm_set = entry.set;
                config.animation_sprite_sheet_layout = entry.layout;
                break;
            }
        }
    }
}

