name: PR Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libinput-dev \
            libudev-dev \
            libwayland-dev \
            wayland-protocols

      - name: Configure CMake (Debug)
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cd build
          cmake --build . -- -j$(nproc)

      - name: Run tests (if any)
        run: |
          cd build
          ctest --output-on-failure || true
