name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libinput-dev \
            libudev-dev \
            libwayland-dev \
            wayland-protocols \
            locales \
            ninja-build \
            fakeroot \
            dpkg-dev \
            rpm \
            cpack

      - name: Configure CMake (Release)
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . -- -j$(nproc)

      - name: Package
        run: |
          cd build
          cpack  # Will generate DEB, RPM, ZIP according to your CPack setup

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload all packages
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*
          asset_name: bongocat-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
