#include "embedded_assets/embedded_image.h"
#include "embedded_assets/dmx/dmx.hpp"
#include "dmx_config_parse_animation_name.h"

namespace bongocat::assets {
    static const config_animation_entry_t dmx_animation_table[] = {
        { DMX_AGUMON_BLACK_X_NAME, DMX_AGUMON_BLACK_X_ID, DMX_AGUMON_BLACK_X_FQID, DMX_AGUMON_BLACK_X_FQNAME, DMX_AGUMON_BLACK_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_AGUMON_X_NAME, DMX_AGUMON_X_ID, DMX_AGUMON_X_FQID, DMX_AGUMON_X_FQNAME, DMX_AGUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ALLOMON_X_NAME, DMX_ALLOMON_X_ID, DMX_ALLOMON_X_FQID, DMX_ALLOMON_X_FQNAME, DMX_ALLOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ALPHAMON_OURYUKEN_NAME, DMX_ALPHAMON_OURYUKEN_ID, DMX_ALPHAMON_OURYUKEN_FQID, DMX_ALPHAMON_OURYUKEN_FQNAME, DMX_ALPHAMON_OURYUKEN_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ALPHAMON_NAME, DMX_ALPHAMON_ID, DMX_ALPHAMON_FQID, DMX_ALPHAMON_FQNAME, DMX_ALPHAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ANCIENT_SPHINXMON_NAME, DMX_ANCIENT_SPHINXMON_ID, DMX_ANCIENT_SPHINXMON_FQID, DMX_ANCIENT_SPHINXMON_FQNAME, DMX_ANCIENT_SPHINXMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ANGEWOMON_X_NAME, DMX_ANGEWOMON_X_ID, DMX_ANGEWOMON_X_FQID, DMX_ANGEWOMON_X_FQNAME, DMX_ANGEWOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ANOMALOCARIMON_X_NAME, DMX_ANOMALOCARIMON_X_ID, DMX_ANOMALOCARIMON_X_FQID, DMX_ANOMALOCARIMON_X_FQNAME, DMX_ANOMALOCARIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BAGRAMON_NAME, DMX_BAGRAMON_ID, DMX_BAGRAMON_FQID, DMX_BAGRAMON_FQNAME, DMX_BAGRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BARBAMON_X_NAME, DMX_BARBAMON_X_ID, DMX_BARBAMON_X_FQID, DMX_BARBAMON_X_FQNAME, DMX_BARBAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BEEL_STARMON_X_NAME, DMX_BEEL_STARMON_X_ID, DMX_BEEL_STARMON_X_FQID, DMX_BEEL_STARMON_X_FQNAME, DMX_BEEL_STARMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BEELZEBUMON_X_NAME, DMX_BEELZEBUMON_X_ID, DMX_BEELZEBUMON_X_FQID, DMX_BEELZEBUMON_X_FQNAME, DMX_BEELZEBUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BELIAL_VAMDEMON_NAME, DMX_BELIAL_VAMDEMON_ID, DMX_BELIAL_VAMDEMON_FQID, DMX_BELIAL_VAMDEMON_FQNAME, DMX_BELIAL_VAMDEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BELPHEMON_X_NAME, DMX_BELPHEMON_X_ID, DMX_BELPHEMON_X_FQID, DMX_BELPHEMON_X_FQNAME, DMX_BELPHEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_BLACK_WARGREYMON_X_NAME, DMX_BLACK_WARGREYMON_X_ID, DMX_BLACK_WARGREYMON_X_FQID, DMX_BLACK_WARGREYMON_X_FQNAME, DMX_BLACK_WARGREYMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CANNON_BEEMON_NAME, DMX_CANNON_BEEMON_ID, DMX_CANNON_BEEMON_FQID, DMX_CANNON_BEEMON_FQNAME, DMX_CANNON_BEEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CERBERUMON_X_NAME, DMX_CERBERUMON_X_ID, DMX_CERBERUMON_X_FQID, DMX_CERBERUMON_X_FQNAME, DMX_CERBERUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CHAOSDRAMON_X_NAME, DMX_CHAOSDRAMON_X_ID, DMX_CHAOSDRAMON_X_FQID, DMX_CHAOSDRAMON_X_FQNAME, DMX_CHAOSDRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CHERUBIMON_VICE_X_NAME, DMX_CHERUBIMON_VICE_X_ID, DMX_CHERUBIMON_VICE_X_FQID, DMX_CHERUBIMON_VICE_X_FQNAME, DMX_CHERUBIMON_VICE_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CHERUBIMON_VIRTUE_X_NAME, DMX_CHERUBIMON_VIRTUE_X_ID, DMX_CHERUBIMON_VIRTUE_X_FQID, DMX_CHERUBIMON_VIRTUE_X_FQNAME, DMX_CHERUBIMON_VIRTUE_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CHOCOMON_NAME, DMX_CHOCOMON_ID, DMX_CHOCOMON_FQID, DMX_CHOCOMON_FQNAME, DMX_CHOCOMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CHO_HAKKAIMON_NAME, DMX_CHO_HAKKAIMON_ID, DMX_CHO_HAKKAIMON_FQID, DMX_CHO_HAKKAIMON_FQNAME, DMX_CHO_HAKKAIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_COCOMON_NAME, DMX_COCOMON_ID, DMX_COCOMON_FQID, DMX_COCOMON_FQNAME, DMX_COCOMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CRANIUMMON_X_NAME, DMX_CRANIUMMON_X_ID, DMX_CRANIUMMON_X_FQID, DMX_CRANIUMMON_X_FQNAME, DMX_CRANIUMMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CRYS_PALEDRAMON_NAME, DMX_CRYS_PALEDRAMON_ID, DMX_CRYS_PALEDRAMON_FQID, DMX_CRYS_PALEDRAMON_FQNAME, DMX_CRYS_PALEDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_CYBERDRAMON_X_NAME, DMX_CYBERDRAMON_X_ID, DMX_CYBERDRAMON_X_FQID, DMX_CYBERDRAMON_X_FQNAME, DMX_CYBERDRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DAMEMON_NAME, DMX_DAMEMON_ID, DMX_DAMEMON_FQID, DMX_DAMEMON_FQNAME, DMX_DAMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DARK_KNIGHTMON_X_NAME, DMX_DARK_KNIGHTMON_X_ID, DMX_DARK_KNIGHTMON_X_FQID, DMX_DARK_KNIGHTMON_X_FQNAME, DMX_DARK_KNIGHTMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DARKNESS_BAGRAMON_NAME, DMX_DARKNESS_BAGRAMON_ID, DMX_DARKNESS_BAGRAMON_FQID, DMX_DARKNESS_BAGRAMON_FQNAME, DMX_DARKNESS_BAGRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DARK_TYRANOMON_X_NAME, DMX_DARK_TYRANOMON_X_ID, DMX_DARK_TYRANOMON_X_FQID, DMX_DARK_TYRANOMON_X_FQNAME, DMX_DARK_TYRANOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DEMON_X_NAME, DMX_DEMON_X_ID, DMX_DEMON_X_FQID, DMX_DEMON_X_FQNAME, DMX_DEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DIABLOMON_X_NAME, DMX_DIABLOMON_X_ID, DMX_DIABLOMON_X_FQID, DMX_DIABLOMON_X_FQNAME, DMX_DIABLOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DINOREXMON_NAME, DMX_DINOREXMON_ID, DMX_DINOREXMON_FQID, DMX_DINOREXMON_FQNAME, DMX_DINOREXMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DINOTIGERMON_NAME, DMX_DINOTIGERMON_ID, DMX_DINOTIGERMON_FQID, DMX_DINOTIGERMON_FQNAME, DMX_DINOTIGERMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DORUGAMON_NAME, DMX_DORUGAMON_ID, DMX_DORUGAMON_FQID, DMX_DORUGAMON_FQNAME, DMX_DORUGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DORUGUREMON_NAME, DMX_DORUGUREMON_ID, DMX_DORUGUREMON_FQID, DMX_DORUGUREMON_FQNAME, DMX_DORUGUREMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DORUMON_NAME, DMX_DORUMON_ID, DMX_DORUMON_FQID, DMX_DORUMON_FQNAME, DMX_DORUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DRACOMON_X_NAME, DMX_DRACOMON_X_ID, DMX_DRACOMON_X_FQID, DMX_DRACOMON_X_FQNAME, DMX_DRACOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DUFTMON_X_NAME, DMX_DUFTMON_X_ID, DMX_DUFTMON_X_FQID, DMX_DUFTMON_X_FQNAME, DMX_DUFTMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DUKEMON_X_NAME, DMX_DUKEMON_X_ID, DMX_DUKEMON_X_FQID, DMX_DUKEMON_X_FQNAME, DMX_DUKEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DUSKMON_NAME, DMX_DUSKMON_ID, DMX_DUSKMON_FQID, DMX_DUSKMON_FQNAME, DMX_DUSKMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_DYNASMON_X_NAME, DMX_DYNASMON_X_ID, DMX_DYNASMON_X_FQID, DMX_DYNASMON_X_FQNAME, DMX_DYNASMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_EBEMON_X_NAME, DMX_EBEMON_X_ID, DMX_EBEMON_X_FQID, DMX_EBEMON_X_FQNAME, DMX_EBEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_EXAMON_NAME, DMX_EXAMON_ID, DMX_EXAMON_FQID, DMX_EXAMON_FQNAME, DMX_EXAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_EXAMON_X_NAME, DMX_EXAMON_X_ID, DMX_EXAMON_X_FQID, DMX_EXAMON_X_FQNAME, DMX_EXAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_FILMON_NAME, DMX_FILMON_ID, DMX_FILMON_FQID, DMX_FILMON_FQNAME, DMX_FILMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GABUMON_X_NAME, DMX_GABUMON_X_ID, DMX_GABUMON_X_FQID, DMX_GABUMON_X_FQNAME, DMX_GABUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GAIOUMON_NAME, DMX_GAIOUMON_ID, DMX_GAIOUMON_FQID, DMX_GAIOUMON_FQNAME, DMX_GAIOUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GANKOOMON_X_NAME, DMX_GANKOOMON_X_ID, DMX_GANKOOMON_X_FQID, DMX_GANKOOMON_X_FQNAME, DMX_GANKOOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GARUDAMON_X_NAME, DMX_GARUDAMON_X_ID, DMX_GARUDAMON_X_FQID, DMX_GARUDAMON_X_FQNAME, DMX_GARUDAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GIGA_SEADRAMON_NAME, DMX_GIGA_SEADRAMON_ID, DMX_GIGA_SEADRAMON_FQID, DMX_GIGA_SEADRAMON_FQNAME, DMX_GIGA_SEADRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GINRYUMON_NAME, DMX_GINRYUMON_ID, DMX_GINRYUMON_FQID, DMX_GINRYUMON_FQNAME, DMX_GINRYUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GODDRAMON_X_NAME, DMX_GODDRAMON_X_ID, DMX_GODDRAMON_X_FQID, DMX_GODDRAMON_X_FQNAME, DMX_GODDRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GOMAMON_X_NAME, DMX_GOMAMON_X_ID, DMX_GOMAMON_X_FQID, DMX_GOMAMON_X_FQNAME, DMX_GOMAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GRADEMON_NAME, DMX_GRADEMON_ID, DMX_GRADEMON_FQID, DMX_GRADEMON_FQNAME, DMX_GRADEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GRAND_DARCUMON_NAME, DMX_GRAND_DARCUMON_ID, DMX_GRAND_DARCUMON_FQID, DMX_GRAND_DARCUMON_FQNAME, DMX_GRAND_DARCUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GRANDIS_KUWAGAMON_NAME, DMX_GRANDIS_KUWAGAMON_ID, DMX_GRANDIS_KUWAGAMON_FQID, DMX_GRANDIS_KUWAGAMON_FQNAME, DMX_GRANDIS_KUWAGAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GROWMON_X_NAME, DMX_GROWMON_X_ID, DMX_GROWMON_X_FQID, DMX_GROWMON_X_FQNAME, DMX_GROWMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_GUMMYMON_NAME, DMX_GUMMYMON_ID, DMX_GUMMYMON_FQID, DMX_GUMMYMON_FQNAME, DMX_GUMMYMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_HERISSMON_NAME, DMX_HERISSMON_ID, DMX_HERISSMON_FQID, DMX_HERISSMON_FQNAME, DMX_HERISSMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_HEXEBLAUMON_NAME, DMX_HEXEBLAUMON_ID, DMX_HEXEBLAUMON_FQID, DMX_HEXEBLAUMON_FQNAME, DMX_HEXEBLAUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_HISYARYUMON_NAME, DMX_HISYARYUMON_ID, DMX_HISYARYUMON_FQID, DMX_HISYARYUMON_FQNAME, DMX_HISYARYUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_HOLYDRAMON_X_NAME, DMX_HOLYDRAMON_X_ID, DMX_HOLYDRAMON_X_FQID, DMX_HOLYDRAMON_X_FQNAME, DMX_HOLYDRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_HOUOUMON_X_NAME, DMX_HOUOUMON_X_ID, DMX_HOUOUMON_X_FQID, DMX_HOUOUMON_X_FQNAME, DMX_HOUOUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_IMPMON_X_NAME, DMX_IMPMON_X_ID, DMX_IMPMON_X_FQID, DMX_IMPMON_X_FQNAME, DMX_IMPMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JARARCHIMON_NAME, DMX_JARARCHIMON_ID, DMX_JARARCHIMON_FQID, DMX_JARARCHIMON_FQNAME, DMX_JARARCHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JAZAMON_NAME, DMX_JAZAMON_ID, DMX_JAZAMON_FQID, DMX_JAZAMON_FQNAME, DMX_JAZAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JAZARDMON_NAME, DMX_JAZARDMON_ID, DMX_JAZARDMON_FQID, DMX_JAZARDMON_FQNAME, DMX_JAZARDMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JESMON_GX_NAME, DMX_JESMON_GX_ID, DMX_JESMON_GX_FQID, DMX_JESMON_GX_FQNAME, DMX_JESMON_GX_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JESMON_X_NAME, DMX_JESMON_X_ID, DMX_JESMON_X_FQID, DMX_JESMON_X_FQNAME, DMX_JESMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_JUSTIMON_X_NAME, DMX_JUSTIMON_X_ID, DMX_JUSTIMON_X_FQID, DMX_JUSTIMON_X_FQNAME, DMX_JUSTIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KAISER_LEOMON_NAME, DMX_KAISER_LEOMON_ID, DMX_KAISER_LEOMON_FQID, DMX_KAISER_LEOMON_FQNAME, DMX_KAISER_LEOMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KEEMON_NAME, DMX_KEEMON_ID, DMX_KEEMON_FQID, DMX_KEEMON_FQNAME, DMX_KEEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KERAMON_X_NAME, DMX_KERAMON_X_ID, DMX_KERAMON_X_FQID, DMX_KERAMON_X_FQNAME, DMX_KERAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KIIMON_NAME, DMX_KIIMON_ID, DMX_KIIMON_FQID, DMX_KIIMON_FQNAME, DMX_KIIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KOKUWAMON_X_NAME, DMX_KOKUWAMON_X_ID, DMX_KOKUWAMON_X_FQID, DMX_KOKUWAMON_X_FQNAME, DMX_KOKUWAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_KUWAGAMON_X_NAME, DMX_KUWAGAMON_X_ID, DMX_KUWAGAMON_X_FQID, DMX_KUWAGAMON_X_FQNAME, DMX_KUWAGAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LADY_DEVIMON_X_NAME, DMX_LADY_DEVIMON_X_ID, DMX_LADY_DEVIMON_X_FQID, DMX_LADY_DEVIMON_X_FQNAME, DMX_LADY_DEVIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LEOMON_X_NAME, DMX_LEOMON_X_ID, DMX_LEOMON_X_FQID, DMX_LEOMON_X_FQNAME, DMX_LEOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LEVIAMON_X_NAME, DMX_LEVIAMON_X_ID, DMX_LEVIAMON_X_FQID, DMX_LEVIAMON_X_FQNAME, DMX_LEVIAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LILIMON_X_NAME, DMX_LILIMON_X_ID, DMX_LILIMON_X_FQID, DMX_LILIMON_X_FQNAME, DMX_LILIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LILITHMON_X_NAME, DMX_LILITHMON_X_ID, DMX_LILITHMON_X_FQID, DMX_LILITHMON_X_FQNAME, DMX_LILITHMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LOPMON_X_NAME, DMX_LOPMON_X_ID, DMX_LOPMON_X_FQID, DMX_LOPMON_X_FQNAME, DMX_LOPMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LORD_KIGHTMON_X_NAME, DMX_LORD_KIGHTMON_X_ID, DMX_LORD_KIGHTMON_X_FQID, DMX_LORD_KIGHTMON_X_FQNAME, DMX_LORD_KIGHTMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_LUCEMON_X_NAME, DMX_LUCEMON_X_ID, DMX_LUCEMON_X_FQID, DMX_LUCEMON_X_FQNAME, DMX_LUCEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MAGIDRAMON_X_NAME, DMX_MAGIDRAMON_X_ID, DMX_MAGIDRAMON_X_FQID, DMX_MAGIDRAMON_X_FQNAME, DMX_MAGIDRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MAGNAMON_X_NAME, DMX_MAGNAMON_X_ID, DMX_MAGNAMON_X_FQID, DMX_MAGNAMON_X_FQNAME, DMX_MAGNAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MAMEMON_X_NAME, DMX_MAMEMON_X_ID, DMX_MAMEMON_X_FQID, DMX_MAMEMON_X_FQNAME, DMX_MAMEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MAME_TYRAMON_NAME, DMX_MAME_TYRAMON_ID, DMX_MAME_TYRAMON_FQID, DMX_MAME_TYRAMON_FQNAME, DMX_MAME_TYRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MAMMON_X_NAME, DMX_MAMMON_X_ID, DMX_MAMMON_X_FQID, DMX_MAMMON_X_FQNAME, DMX_MAMMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MANTARAYMON_X_NAME, DMX_MANTARAYMON_X_ID, DMX_MANTARAYMON_X_FQID, DMX_MANTARAYMON_X_FQNAME, DMX_MANTARAYMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MEGALO_GROWMON_X_NAME, DMX_MEGALO_GROWMON_X_ID, DMX_MEGALO_GROWMON_X_FQID, DMX_MEGALO_GROWMON_X_FQNAME, DMX_MEGALO_GROWMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MEGA_SEADRAMON_X_NAME, DMX_MEGA_SEADRAMON_X_ID, DMX_MEGA_SEADRAMON_X_FQID, DMX_MEGA_SEADRAMON_X_FQNAME, DMX_MEGA_SEADRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MEPHISMON_X_NAME, DMX_MEPHISMON_X_ID, DMX_MEPHISMON_X_FQID, DMX_MEPHISMON_X_FQNAME, DMX_MEPHISMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MERAMON_X_NAME, DMX_MERAMON_X_ID, DMX_MERAMON_X_FQID, DMX_MERAMON_X_FQNAME, DMX_MERAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_FANTOMON_NAME, DMX_METAL_FANTOMON_ID, DMX_METAL_FANTOMON_FQID, DMX_METAL_FANTOMON_FQNAME, DMX_METAL_FANTOMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_GARURUMON_X_NAME, DMX_METAL_GARURUMON_X_ID, DMX_METAL_GARURUMON_X_FQID, DMX_METAL_GARURUMON_X_FQNAME, DMX_METAL_GARURUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_GREYMON_VIRUS_X_NAME, DMX_METAL_GREYMON_VIRUS_X_ID, DMX_METAL_GREYMON_VIRUS_X_FQID, DMX_METAL_GREYMON_VIRUS_X_FQNAME, DMX_METAL_GREYMON_VIRUS_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_GREYMON_X_NAME, DMX_METAL_GREYMON_X_ID, DMX_METAL_GREYMON_X_FQID, DMX_METAL_GREYMON_X_FQNAME, DMX_METAL_GREYMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METALLICDRAMON_NAME, DMX_METALLICDRAMON_ID, DMX_METALLICDRAMON_FQID, DMX_METALLICDRAMON_FQNAME, DMX_METALLICDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_PIRANIMON_NAME, DMX_METAL_PIRANIMON_ID, DMX_METAL_PIRANIMON_FQID, DMX_METAL_PIRANIMON_FQNAME, DMX_METAL_PIRANIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_METAL_TYRANOMON_X_NAME, DMX_METAL_TYRANOMON_X_ID, DMX_METAL_TYRANOMON_X_FQID, DMX_METAL_TYRANOMON_X_FQNAME, DMX_METAL_TYRANOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MINERVAMON_X_NAME, DMX_MINERVAMON_X_ID, DMX_MINERVAMON_X_FQID, DMX_MINERVAMON_X_FQNAME, DMX_MINERVAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_MONZAEMON_X_NAME, DMX_MONZAEMON_X_ID, DMX_MONZAEMON_X_FQID, DMX_MONZAEMON_X_FQNAME, DMX_MONZAEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_NEFERTIMON_X_NAME, DMX_NEFERTIMON_X_ID, DMX_NEFERTIMON_X_FQID, DMX_NEFERTIMON_X_FQNAME, DMX_NEFERTIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_NOBLE_PUMPMON_NAME, DMX_NOBLE_PUMPMON_ID, DMX_NOBLE_PUMPMON_FQID, DMX_NOBLE_PUMPMON_FQNAME, DMX_NOBLE_PUMPMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_NUMEMON_X_NAME, DMX_NUMEMON_X_ID, DMX_NUMEMON_X_FQID, DMX_NUMEMON_X_FQNAME, DMX_NUMEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OGREMON_X_NAME, DMX_OGREMON_X_ID, DMX_OGREMON_X_FQID, DMX_OGREMON_X_FQNAME, DMX_OGREMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OGUDOMON_X_NAME, DMX_OGUDOMON_X_ID, DMX_OGUDOMON_X_FQID, DMX_OGUDOMON_X_FQNAME, DMX_OGUDOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OKUWAMON_X_NAME, DMX_OKUWAMON_X_ID, DMX_OKUWAMON_X_FQID, DMX_OKUWAMON_X_FQNAME, DMX_OKUWAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OMEGAMON_X_NAME, DMX_OMEGAMON_X_ID, DMX_OMEGAMON_X_FQID, DMX_OMEGAMON_X_FQNAME, DMX_OMEGAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OMEGA_SHOUTMON_X_NAME, DMX_OMEGA_SHOUTMON_X_ID, DMX_OMEGA_SHOUTMON_X_FQID, DMX_OMEGA_SHOUTMON_X_FQNAME, DMX_OMEGA_SHOUTMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OMEKAMON_NAME, DMX_OMEKAMON_ID, DMX_OMEKAMON_FQID, DMX_OMEKAMON_FQNAME, DMX_OMEKAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OPHANIMON_FALLDOWN_MODE_NAME, DMX_OPHANIMON_FALLDOWN_MODE_ID, DMX_OPHANIMON_FALLDOWN_MODE_FQID, DMX_OPHANIMON_FALLDOWN_MODE_FQNAME, DMX_OPHANIMON_FALLDOWN_MODE_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OPHANIMON_X_NAME, DMX_OPHANIMON_X_ID, DMX_OPHANIMON_X_FQID, DMX_OPHANIMON_X_FQNAME, DMX_OPHANIMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OTAMAMON_X_NAME, DMX_OTAMAMON_X_ID, DMX_OTAMAMON_X_FQID, DMX_OTAMAMON_X_FQNAME, DMX_OTAMAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_OURYUMON_NAME, DMX_OURYUMON_ID, DMX_OURYUMON_FQID, DMX_OURYUMON_FQNAME, DMX_OURYUMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PALEDRAMON_NAME, DMX_PALEDRAMON_ID, DMX_PALEDRAMON_FQID, DMX_PALEDRAMON_FQNAME, DMX_PALEDRAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PALMON_X_NAME, DMX_PALMON_X_ID, DMX_PALMON_X_FQID, DMX_PALMON_X_FQNAME, DMX_PALMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PEGASMON_X_NAME, DMX_PEGASMON_X_ID, DMX_PEGASMON_X_FQID, DMX_PEGASMON_X_FQNAME, DMX_PEGASMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PLATINUM_NUMEMON_NAME, DMX_PLATINUM_NUMEMON_ID, DMX_PLATINUM_NUMEMON_FQID, DMX_PLATINUM_NUMEMON_FQNAME, DMX_PLATINUM_NUMEMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PLESIOMON_X_NAME, DMX_PLESIOMON_X_ID, DMX_PLESIOMON_X_FQID, DMX_PLESIOMON_X_FQNAME, DMX_PLESIOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PLOTMON_X_NAME, DMX_PLOTMON_X_ID, DMX_PLOTMON_X_FQID, DMX_PLOTMON_X_FQNAME, DMX_PLOTMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PRINCE_MAMEMON_X_NAME, DMX_PRINCE_MAMEMON_X_ID, DMX_PRINCE_MAMEMON_X_FQID, DMX_PRINCE_MAMEMON_X_FQNAME, DMX_PRINCE_MAMEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PTERANMON_X_NAME, DMX_PTERANMON_X_ID, DMX_PTERANMON_X_FQID, DMX_PTERANMON_X_FQNAME, DMX_PTERANMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PUMPMON_NAME, DMX_PUMPMON_ID, DMX_PUMPMON_FQID, DMX_PUMPMON_FQNAME, DMX_PUMPMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_PUTTIMON_NAME, DMX_PUTTIMON_ID, DMX_PUTTIMON_FQID, DMX_PUTTIMON_FQNAME, DMX_PUTTIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RAFFLESIMON_NAME, DMX_RAFFLESIMON_ID, DMX_RAFFLESIMON_FQID, DMX_RAFFLESIMON_FQNAME, DMX_RAFFLESIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RAIHIMON_NAME, DMX_RAIHIMON_ID, DMX_RAIHIMON_FQID, DMX_RAIHIMON_FQNAME, DMX_RAIHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RAPIDMON_X_NAME, DMX_RAPIDMON_X_ID, DMX_RAPIDMON_X_FQID, DMX_RAPIDMON_X_FQNAME, DMX_RAPIDMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RASENMON_FURY_MODE_NAME, DMX_RASENMON_FURY_MODE_ID, DMX_RASENMON_FURY_MODE_FQID, DMX_RASENMON_FURY_MODE_FQNAME, DMX_RASENMON_FURY_MODE_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RASENMON_NAME, DMX_RASENMON_ID, DMX_RASENMON_FQID, DMX_RASENMON_FQNAME, DMX_RASENMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_REKAMON_X_NAME, DMX_REKAMON_X_ID, DMX_REKAMON_X_FQID, DMX_REKAMON_X_FQNAME, DMX_REKAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RHINOMON_X_NAME, DMX_RHINOMON_X_ID, DMX_RHINOMON_X_FQID, DMX_RHINOMON_X_FQNAME, DMX_RHINOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RIZE_GREYMON_X_NAME, DMX_RIZE_GREYMON_X_ID, DMX_RIZE_GREYMON_X_FQID, DMX_RIZE_GREYMON_X_FQNAME, DMX_RIZE_GREYMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ROSEMON_X_NAME, DMX_ROSEMON_X_ID, DMX_ROSEMON_X_FQID, DMX_ROSEMON_X_FQNAME, DMX_ROSEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_RYUDAMON_NAME, DMX_RYUDAMON_ID, DMX_RYUDAMON_FQID, DMX_RYUDAMON_FQNAME, DMX_RYUDAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SAKUYAMON_X_NAME, DMX_SAKUYAMON_X_ID, DMX_SAKUYAMON_X_FQID, DMX_SAKUYAMON_X_FQNAME, DMX_SAKUYAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SANGOUPMON_NAME, DMX_SANGOUPMON_ID, DMX_SANGOUPMON_FQID, DMX_SANGOUPMON_FQNAME, DMX_SANGOUPMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SEADRAMON_X_NAME, DMX_SEADRAMON_X_ID, DMX_SEADRAMON_X_FQID, DMX_SEADRAMON_X_FQNAME, DMX_SEADRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SHAKOMON_X_NAME, DMX_SHAKOMON_X_ID, DMX_SHAKOMON_X_FQID, DMX_SHAKOMON_X_FQNAME, DMX_SHAKOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SIESAMON_X_NAME, DMX_SIESAMON_X_ID, DMX_SIESAMON_X_FQID, DMX_SIESAMON_X_FQNAME, DMX_SIESAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SISTERMON_BLANC_NAME, DMX_SISTERMON_BLANC_ID, DMX_SISTERMON_BLANC_FQID, DMX_SISTERMON_BLANC_FQNAME, DMX_SISTERMON_BLANC_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SKULL_BALUCHIMON_NAME, DMX_SKULL_BALUCHIMON_ID, DMX_SKULL_BALUCHIMON_FQID, DMX_SKULL_BALUCHIMON_FQNAME, DMX_SKULL_BALUCHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SKULL_MAMMON_X_NAME, DMX_SKULL_MAMMON_X_ID, DMX_SKULL_MAMMON_X_FQID, DMX_SKULL_MAMMON_X_FQNAME, DMX_SKULL_MAMMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_SLEIPMON_X_NAME, DMX_SLEIPMON_X_ID, DMX_SLEIPMON_X_FQID, DMX_SLEIPMON_X_FQNAME, DMX_SLEIPMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_STIFFIMON_NAME, DMX_STIFFIMON_ID, DMX_STIFFIMON_FQID, DMX_STIFFIMON_FQNAME, DMX_STIFFIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TAILMON_X_NAME, DMX_TAILMON_X_ID, DMX_TAILMON_X_FQID, DMX_TAILMON_X_FQNAME, DMX_TAILMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TIERRIERMON_X_NAME, DMX_TIERRIERMON_X_ID, DMX_TIERRIERMON_X_FQID, DMX_TIERRIERMON_X_FQNAME, DMX_TIERRIERMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TIGER_VESPAMON_NAME, DMX_TIGER_VESPAMON_ID, DMX_TIGER_VESPAMON_FQID, DMX_TIGER_VESPAMON_FQNAME, DMX_TIGER_VESPAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TOBCATMON_NAME, DMX_TOBCATMON_ID, DMX_TOBCATMON_FQID, DMX_TOBCATMON_FQNAME, DMX_TOBCATMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TOGEMON_X_NAME, DMX_TOGEMON_X_ID, DMX_TOGEMON_X_FQID, DMX_TOGEMON_X_FQNAME, DMX_TOGEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TOKOMON_X_NAME, DMX_TOKOMON_X_ID, DMX_TOKOMON_X_FQID, DMX_TOKOMON_X_FQNAME, DMX_TOKOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TRICERAMON_X_NAME, DMX_TRICERAMON_X_ID, DMX_TRICERAMON_X_FQID, DMX_TRICERAMON_X_FQNAME, DMX_TRICERAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TYLOMON_X_NAME, DMX_TYLOMON_X_ID, DMX_TYLOMON_X_FQID, DMX_TYLOMON_X_FQNAME, DMX_TYLOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_TYRANOMON_X_NAME, DMX_TYRANOMON_X_ID, DMX_TYRANOMON_X_FQID, DMX_TYRANOMON_X_FQNAME, DMX_TYRANOMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ULFORCE_V_DRAMON_X_NAME, DMX_ULFORCE_V_DRAMON_X_ID, DMX_ULFORCE_V_DRAMON_X_FQID, DMX_ULFORCE_V_DRAMON_X_FQNAME, DMX_ULFORCE_V_DRAMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ULTIMATE_BRACHIMON_NAME, DMX_ULTIMATE_BRACHIMON_ID, DMX_ULTIMATE_BRACHIMON_FQID, DMX_ULTIMATE_BRACHIMON_FQNAME, DMX_ULTIMATE_BRACHIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_VALDURMON_NAME, DMX_VALDURMON_ID, DMX_VALDURMON_FQID, DMX_VALDURMON_FQNAME, DMX_VALDURMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_VAMDEMON_X_NAME, DMX_VAMDEMON_X_ID, DMX_VAMDEMON_X_FQID, DMX_VAMDEMON_X_FQNAME, DMX_VAMDEMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_VELGRMAN_NAME, DMX_VELGRMAN_ID, DMX_VELGRMAN_FQID, DMX_VELGRMAN_FQNAME, DMX_VELGRMAN_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_VOLTOBAUTAMON_NAME, DMX_VOLTOBAUTAMON_ID, DMX_VOLTOBAUTAMON_FQID, DMX_VOLTOBAUTAMON_FQNAME, DMX_VOLTOBAUTAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_WAR_GREYMON_X_NAME, DMX_WAR_GREYMON_X_ID, DMX_WAR_GREYMON_X_FQID, DMX_WAR_GREYMON_X_FQNAME, DMX_WAR_GREYMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_WERE_GARURUMON_X_NAME, DMX_WERE_GARURUMON_X_ID, DMX_WERE_GARURUMON_X_FQID, DMX_WERE_GARURUMON_X_FQNAME, DMX_WERE_GARURUMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_WIZARMON_X_NAME, DMX_WIZARMON_X_ID, DMX_WIZARMON_X_FQID, DMX_WIZARMON_X_FQNAME, DMX_WIZARMON_X_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_YAAMON_NAME, DMX_YAAMON_ID, DMX_YAAMON_FQID, DMX_YAAMON_FQNAME, DMX_YAAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_YATAGARAMON_NAME, DMX_YATAGARAMON_ID, DMX_YATAGARAMON_FQID, DMX_YATAGARAMON_FQNAME, DMX_YATAGARAMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
        { DMX_ZERIMON_NAME, DMX_ZERIMON_ID, DMX_ZERIMON_FQID, DMX_ZERIMON_FQNAME, DMX_ZERIMON_ANIM_INDEX, config::config_animation_dm_set_t::dmx, config::config_animation_sprite_sheet_layout_t::Dm },
    };

    config_animation_entry_t get_config_animation_name_dmx(size_t index) {
        // keep aliases in mind
        for (const auto& entry : dmx_animation_table) {
            assert(entry.anim_index >= 0);
            if (static_cast<size_t>(entry.anim_index) == index) return entry;
        }
        return dmx_animation_table[index];
    }

    int config_parse_animation_name_dmx(config::config_t& config, const char *value) {
        for (const auto& entry : dmx_animation_table) {
            if (strcmp(value, entry.name) == 0 ||
                strcmp(value, entry.id) == 0 ||
                strcmp(value, entry.fqid) == 0 ||
                strcmp(value, entry.fqname) == 0) {
                config.animation_index = entry.anim_index;
                config.animation_dm_set = entry.set;
                config.animation_sprite_sheet_layout = entry.layout;
                return entry.anim_index;
            }
        }
        return -1;
    }
}

